### ISSUE TITLE
Support padding instead of height/width dp

### ISSUE THREAD

**Issue by lolsheeplol** [skydoves/Balloon#1]
**Is your feature request related to a problem?**

For a balloon with multiple lines of text, having the balloon container scale with its height would be very useful. 

**Describe the solution you'd like:**

At the moment the `layout_balloon.xml` file uses dp values instead of "wrap_content".  If the layout uses "wrap_content" for height, the builder can drop `builder.setHeight()` and `builder.setWidth()`, and instead have something like `builder.setPaddingVert()` and `builder.setPaddingHoriz()`.  

Thoughts?

**Comment by skydoves** [comment]
@lolsheeplol 
It seems a good way to scaling container.

I will try to implement to scale container size using padding and  "wrap_content" layout attribute 
on the next version.

Thank you for giving a good issue! :)

**Comment by rgocal** [comment]
I was just going to ask about this. The problem i have right now is i have a list that changes size vertical depending on options available for the action. What i have to currently do is set a default height and add to that height when the listview has so many objects (1 action + add x height, 2 actions add xy height). I've even tried getting the view group height from tree observer to set that as the height but it adds to that value every time its calculated. Having a height option to wrap around the xml would be good.

**Comment by skydoves** [comment]
Hi, is there a better way to implement having a height option to wrap around the xml with keeping functionalities like [showAlignTop](https://github.com/skydoves/Balloon/blob/master/balloon/src/main/java/com/skydoves/balloon/Balloon.kt#L266)? It uses a fixed height with `bodyWindow.showAsDropDown`.
If the layout uses "wrap_content" option, we can't measure the specific height values.
Because of the popupWindow shows firstly and inflates the popupWindow 's content view.

**Comment by rgocal** [comment]
https://github.com/rgocal/Material_PopUp_Menu

You can check and see if there's anything helpful you could use in my popup menu library. (im actually replacing my library with yours for my project)

**Comment by rustyhamsterr** [comment]
@skydoves Hi, I am using your library right now and want to improve it. I think using wrap content is a very important function and I wanted to start with this. 
Did you make progress since this issue was opened? 
Greetings rusty

**Comment by skydoves** [comment]
#20

**Comment by skydoves** [comment]
It has been a long time! The first issue is resolved in the new release [1.1.2](https://github.com/skydoves/Balloon/releases/tag/1.1.2). 🎉
