### ISSUE TITLE
Support for XML animations

### ISSUE THREAD

**Issue by Nikola-Milovic** [skydoves/Balloon#10]
Basically just support for regular .startAnimations, I'd love to have some custom movement on my bubbles. Otherwise really useful <3

**Comment by skydoves** [comment]
@Nikola-Milovic 
Hi, It will be included in the [next version](https://github.com/skydoves/Balloon/commit/502e7786a8ab4089aebd05abb847ac4abc6825d5).
Thank you for your issue!

**Comment by skydoves** [comment]
@Nikola-Milovic 
It is released [1.0.7](https://github.com/skydoves/Balloon/releases/tag/1.0.7).
Thank toy for your good issue!
