### ISSUE TITLE
setElevation has shadow

### ISSUE THREAD

**Issue by BoumBam** [skydoves/Balloon#100]
How to remove the shadow arround the popover when setElevation is given ?

**Comment by skydoves** [comment]
Hi, `setElevation` gives the shadow to the popup.
If you want to remove the shadow, you can give 0.

**Comment by BoumBam** [comment]
The animation provide by  `.setElevation(100)`, the `.setBalloonAnimation(Ballonimation.OVERSHOOT)` onAis not the same like animation provided by  `.setElevation(0)`, the `.setBalloonAnimation(BalloonAnimation.OVERSHOOT)`.


I really want the animation for `.setElevation(100)`, the `.setBalloonAnimation(Ballonimation.OVERSHOOT)`.

You did great work on that library,  It is amazing.

Thanks.

**Comment by skydoves** [comment]
@BoumBam 
Ah, I understand now. Thank you for sharing your issue and I didn't expect those animations do not work the same.
I think this code will work in that case.
```kotlin
val card: CardView = balloon.getContentView().findViewById(R.id.balloon_card)
card.cardElevation = 0f
```

**Comment by BoumBam** [comment]
> ```kotlin
> 0f
> ```

I'm java user I don't use kotlin.
Any effort for java ?

Thanks.
