### ISSUE TITLE
Showing the popover make my activity scroll a little

### ISSUE THREAD

**Issue by BoumBam** [skydoves/Balloon#101]
When the anchor view is at extreme north or extreme south of the activity (like in my case), showing the popover make the activity scroll a little.

Is it normal ?
How to prevent the activity from scrolling when showing the popover ?

I'm detecting the scroll event, so I don't want the popover to scroll the activity.

**Comment by skydoves** [comment]
Hi, could you explain the details of your Activity?
Does it have a `ScrollView` in the layout?
I think It could be possible because the popup is another new window actually.
So adding a new window on the view means adding a new window on the bottom window.

**Comment by BoumBam** [comment]
I'm using a recyclerView in `NestedScrollView` view, I'm giving the possibility to users to react to posts like the react popover of facebook.

See the other issue here: https://github.com/skydoves/Balloon/issues/99#issue-701971336

**Comment by skydoves** [comment]
Hi, if you face this issue again in the latest version, please open again this issue.
Thanks!
