### ISSUE TITLE
Is that librabry compatible with FlexboxLayout library ?

### ISSUE THREAD

**Issue by BoumBam** [skydoves/Balloon#102]
I tried below code but not work.
`<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    tools:context=".MainActivity">

    <com.google.android.flexbox.FlexboxLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:flexWrap="wrap"
        app:alignItems="stretch"
        app:alignContent="stretch" >
        <ImageView
            android:id="@+id/liked"
            android:layout_width="wrap_content"
            android:layout_height="50dp"
            android:src="@drawable/react_liked" />
        <ImageView
            android:id="@+id/love"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/react_love"
            android:layout_toEndOf="@+id/liked" />
        <ImageView
            android:id="@+id/funny"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/react_funny"
            android:layout_toEndOf="@+id/love" />
        <ImageView
            android:id="@+id/whoua"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/react_whoua"
            android:layout_toEndOf="@+id/funny" />
        <ImageView
            android:id="@+id/scary"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/react_scary"
            android:layout_toEndOf="@+id/whoua" />
        <ImageView
            android:id="@+id/sad"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/react_sad"
            android:layout_toEndOf="@+id/scary" />
        <ImageView
            android:id="@+id/angry"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/react_angry"
            android:layout_toEndOf="@+id/sad" />
    </com.google.android.flexbox.FlexboxLayout>

</androidx.constraintlayout.widget.ConstraintLayout>`

with that:
```
`Balloon balloon_react = new Balloon.Builder(context)
                .setArrowVisible(false)
                .setLayout(R.layout.balloon_react_popover_layout)
                .build();`
```

But the popover not show.

**Comment by skydoves** [comment]
Hi,
If you want to show that sets the width size by the display screen size ratio, use `.setWidthRatio(1.0f)`.
Or If you want to make the popup that wraps your content, it should be updated  `android:layout_width="match_parent"` to `android:layout_width="wrap_content"` in yout ConstraintLayout and FlexboxLayout.
