### ISSUE TITLE
Unable to build balloon object

### ISSUE THREAD

**Issue by dduvedi** [skydoves/Balloon#104]
**Please complete the following information:**
- Library Version [e.g. v1.2..3]
- Affected Device(s) [e.g. One Plus 6 Android 10, Nexus S Android 8 Emulator]
 
**Describe the Bug:**

Add a clear description about the problem.
On tap of an icon i want to show tooltip but on build I am getting:
java.lang.NullPointerException: Missing required view with ID: balloon
**Expected Behavior:**

A clear description of what you expected to happen: I want to show the tooltip

**Comment by skydoves** [comment]
Hi, @dduvedi 
Could you build this [demo](https://github.com/skydoves/Balloon/tree/master/app) project in your environment?
And please let me know your Android Studio version and your project's `compileSdkVersion`.
Thanks.

**Comment by dduvedi** [comment]
compileSdkVersion = 29
Android Studio version = 4.0.1
Demo is working

**Comment by skydoves** [comment]
Do you use a custom layout and the XML has `include` tags?

**Comment by dduvedi** [comment]
it has include tags only

**Comment by skydoves** [comment]
There are two solutions.
- Make the view id to be the same as the id of the root view of the included layout.
- Removed the id inside the included layout

**Comment by dduvedi** [comment]
thanks, will try and update here.

**Comment by dduvedi** [comment]
but i have a doubt that it was working fine previously

**Comment by skydoves** [comment]
Because the issue is from using `ViewBinding`.
Balloon uses `ViewBinding` instead of Kotlin synthetic for increasing the performance of the inflating views since version `1.1.6`.

**Comment by dduvedi** [comment]
I tried version 1.0.3 i was getting the crash then i changed to version 1.2.3 but still the same

**Comment by dduvedi** [comment]
java.lang.IllegalStateException: bodyView.balloon_content must not be null
now i got this

**Comment by dduvedi** [comment]
none of the above said solution worked

**Comment by skydoves** [comment]
Does your layout XML's name is `layout_balloon`?
I think there is something issue with your custom layout. Because the demo is working.
Could you make your sample project or share the XML file?
