### ISSUE TITLE
Dismiss Balloon only on MOTION_UP event from outside

### ISSUE THREAD

**Issue by KonradSzewczuk** [skydoves/Balloon#106]
**Is your feature request related to a problem?**

When the Balloon is being shown on the screen I want to dismiss it by touching the screen and then release my finger from it. Currently as soon as I touch it the Balloon disappears. I want to have more control of when exactly it should disappear 

**Describe the solution you'd like:**

I want to customise dismiss event can happen only, when I release my finger from the screen (not as soon as i touched it)

**Describe alternatives you've considered:**

-

**Comment by skydoves** [comment]
Hi, 
`setOnBalloonTouchInterceptor(value: View.OnTouchListener)` function will be added in the next release.
Thank you for your issue :)

**Comment by KonradSzewczuk** [comment]
@skydoves hello, thanks for the info
Can you tell me when this next release will happen?

**Comment by skydoves** [comment]
Hi, @KonradSzewczuk 
It is released `1.2.4-alpha01`.
Thanks!
