### ISSUE TITLE
LifecycleOwner and Activity

### ISSUE THREAD

**Issue by S0und** [skydoves/Balloon#11]
This is more like a quick question. 

To use .setLifecycleOwner(this), i have to use AppCompatActivity, which i don't want to because it causes a ton of issue with themes, so i have to stick to Activity. 

My question, is it sufficient to call .dismiss() on onStop, to avoid memory leak?

**Comment by skydoves** [comment]
@S0und 
Yes, it is sufficient, If you call `.dismiss()` on onStop.
You can implement the `lifecycleOwner` or you can dismiss it manually on `onStop()`  or `onDismiss()`

**Comment by S0und** [comment]
Thank for your answer!

**Comment by dsuresh-ap** [comment]
Thanks, showing the Balloon from a Fragment without using `viewLifecycleOwner` causes a memory leak since the default logic takes the `lifecycleOwner` from `context.
