### ISSUE TITLE
Custom Layout Balloon does not adjust height to content

### ISSUE THREAD

**Issue by NikoBoerger** [skydoves/Balloon#112]
Hi,

I am using a custom layout resource with .setLayout(...). 

I expected the balloon to adjust to the height of my layout, but I experienced that the balloon has always the same height and cuts off my content, once my content gets too high. The option .setHeight() is not very helpful, because I don't know how high my content is gonna be because of different font sizes etc. 

Is that a bug? And if not, is it possible to change that anyways?

Thank you so much,
Niko

**Comment by skydoves** [comment]
#71, #91

**Comment by NikoBoerger** [comment]
Thanks, .measureTextWidth(myTextView) works!
I don't really get why it is the TextWidth and not TextHeight, but I'm glad it works.

Thanks for the quick answer and sorry for opening an already known issue.

**Comment by NikoBoerger** [comment]
I just saw, that it is not working for some text lengths as expected.

![Balloon](https://user-images.githubusercontent.com/8778527/97192091-dbd3cc00-17a7-11eb-9e1a-d52f8594243f.jpg)

My balloon looks like that. Two ImageViews on the sides and a TextView in the middle. All wrapped in a LinearLayout. However, even after calling .measureTextWidth(myTextView) which helped for some text lengths, one word gets cut off here.
Can't I use the fix with .measureTextWidth(myTextView), when I have other elements in my balloon as well?

**Comment by NikoBoerger** [comment]
Could that problem occur when setting paddings or margins around the TextView?

**Comment by NikoBoerger** [comment]
This is my layout:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/layout_balloon_with_button"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <ImageView
        android:id="@+id/ic_balloon"
        android:layout_width="@dimen/_20sdp"
        android:layout_height="@dimen/_20sdp"
        android:layout_weight="1"
        android:layout_gravity="center_vertical|center_horizontal"
        android:layout_marginStart="@dimen/_12sdp"
        android:src="@drawable/ic_not_in_leaderboard"
        />

    <TextView
        android:id="@+id/txt_balloon"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_weight="20"
        android:layout_gravity="center_vertical|center_horizontal"
        android:textAlignment="center"
        android:textColor="?android:attr/colorPrimaryDark"
        android:textSize="@dimen/_12sdp"
        />

    <LinearLayout
        android:id="@+id/btn_upload_to_leaderboard"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:layout_gravity="center_vertical"
        android:layout_marginStart="@dimen/_5sdp"
        android:visibility="gone"
        android:clickable="true"
        android:foreground="?android:attr/selectableItemBackground"
        >

        <ImageView
            android:layout_width="@dimen/_20sdp"
            android:layout_height="@dimen/_20sdp"
            android:layout_weight="1"
            android:layout_gravity="center_horizontal"
            android:src="@drawable/ic_retry"
            />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_weight="20"
            android:text="Retry"
            android:layout_gravity="center_horizontal"
            android:textAlignment="center"
            android:textColor="?android:attr/colorPrimaryDark"
            android:textSize="@dimen/_7sdp"
            />

    </LinearLayout>
    
    <View
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_weight="0"
        android:layout_marginEnd="@dimen/_12sdp"
        />
</LinearLayout>

**Comment by NikoBoerger** [comment]
Please tell me if you need additional information to reproduce the issue. :) Thanks

**Comment by skydoves** [comment]
I think in this case, the popup is not wrapping only the TextView, so you should set the `maxWidtth` manually.

```kotlin
myTextView.maxWidtth = balloon.getMeasureWidth() - getPxSize(@dimen/_20sdp) - getPxSize(@dimen/_20sdp)
```

**Comment by NikoBoerger** [comment]
Okay. I'm not very happy with handling it like that, but it works for now. Thanks for your support.

**Comment by skydoves** [comment]
Hi, I will think about a better way :)
