### ISSUE TITLE
Text is not being showed

### ISSUE THREAD

**Issue by restriglio** [skydoves/Balloon#113]
- Library Version 1.2.3/1.2.4
 
Issue:
I updated version 1.2.1 up to 1.2.4 ( and then I tried 1.2.3 ), and I found that the Balloon text is not being showed anymore. That issues is present in 1.2.3 and 1.2.4, but no in previous version 1.2.1.

Here the result:
<img width="437" alt="Captura de Pantalla 2020-10-29 a la(s) 12 37 14" src="https://user-images.githubusercontent.com/20705583/97603248-fc3f9880-19ea-11eb-8341-329aa97d558e.png">

Here is the code that I'm using:

```
createBalloon(this) {
            setArrowSize(10)
            setArrowOrientation(ArrowOrientation.TOP)
            setArrowVisible(true)
            setWidthRatio(1.0f)
            setHeight(65)
            setTextSize(14f)
            setArrowPosition(0.9f)
            setCornerRadius(4f)
            setPaddingResource(R.dimen...)
            setText(getString(textRes))
            setTextColor(getColorCompat(R.color.white))
            setIconDrawable(
                this@ChatActivity.getDrawableCompat(R.drawable...)
                    ?.tintWithColor(Color.WHITE)
            )
            setBackgroundColor(ContextCompat.getColor(this@ChatActivity, R.color...))
            lifecycleOwner = this
            dismissWhenClicked = true
            dismissWhenTouchOutside = true
            setBalloonAnimation(BalloonAnimation.FADE)
            iconGravity = IconGravity.RIGHT
        }
```

Any idea?
thanks.

**Comment by skydoves** [comment]
Hi, @restriglio
Is the same issue occur in the [demo project](https://github.com/skydoves/Balloon/tree/main/app)?

**Comment by restriglio** [comment]
Hi @skydoves, I tested that in demo project and it doesn't happen. 
I moved same piece of code to the demo and it is working, but then I copies some code from demo app to "my app" and I got same issue, not showing text at all. The weird thing is that  1.2.1 is working as expected, but in 1.2.2 ( and next versions) appears the issue.

any thoughts?
thanks!

**Comment by skydoves** [comment]
Hi, @restriglio 
It is difficult to represent this issue on my devices, could you please test without the `setPaddingResource()` option?
I was looked around the commit history between `1.2.1` and `1.2.2`, there is not much difference except paddings. 🤔

**Comment by skydoves** [comment]
Hi, @restriglio 
Is the issue still occur in the new version `1.2.6`?
This issue is a little weird because the icon is a `text-drawable`, so your screenshot actually showing the `TextView`.
Can you check your project's theme styles related to the text color?

**Comment by restriglio** [comment]
Hi @skydoves, I don't have access to that code anymore.
If I can find a way to contact someone to try that, I'll let you know.

Thanks!

**Comment by skydoves** [comment]
Thanks, then I will close this issue.
Please let me know if you get this issue later :)
