### ISSUE TITLE
arrow dose not showing

### ISSUE THREAD

**Issue by BongJaeChoi** [skydoves/Balloon#114]
**Please complete the following information:**
- Library Version 1.2.4
- Affected Device(s)  Samsung Galaxy s8+ with Android 8.0
 
**Describe the Bug:**
- when apply `setBackgroundDrawableResource` arrow dose not showing

**Code**
- drawable
```xml
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">

    <solid android:color="@color/white" />
    <stroke
        android:width="1dp"
        android:color="@color/navy_4" />
    <corners android:radius="4dp" />

</shape>
```
- balloon
```
createBalloon(context){
setBackgroundDrawableResourceoundColor(R.drawable.bg_draw)
setArrowSize(8)
...

}.showAlignTop(imageView)
```

**Comment by skydoves** [comment]
Hi, I just check out the issue using the demo project, it's not easy to represent that issue.
And the position of the arrow has no relations with the background resource, the color of the arrow is decided by the background color of the popup. Could you please add `setArrowColorResource(R.color.skyBlue)` to your `Balloon.Builder` and rebuild it?

**Comment by benjamin-prnd** [comment]
@skydoves arrow is showing but `setBackgroundDrawableResource` still not working.
I use `setLayout`. layout is just TextView. is that problem?

**Comment by skydoves** [comment]
Hi, @benjamin-prnd
If you use a customized layout using the `setLayout`,  `setBackgroundDrawableResource` will not work correctly.

Instead, try to set the drawable resource as background to your customized layout. Here is a testable [customized layout](https://github.com/skydoves/Balloon/blob/main/app/src/main/java/com/skydoves/balloondemo/factory/CustomListBalloonFactory.kt#L42) that could be changed as the `@drawable/round_button_skyblue`  drawable resource.

Additionally, there are some chores for measuring the height of a textView in the popup window, If you would face some measuring issues, please reference #112.

**Comment by BongJaeChoi** [comment]
thank you.  please close issue
