### ISSUE TITLE
How remove focus on View of setOverlayShape

### ISSUE THREAD

**Issue by caiolesk** [skydoves/Balloon#115]
How remove focus on view ? I want only setOverlayColorResource. I'm using a complex layout with CoordinatorLayout
![focus_wrong](https://user-images.githubusercontent.com/37921435/98165358-8644a100-1ec4-11eb-8b3a-f1bb6676bb4e.png)

Thank you. Wating for answer!!

**Comment by caiolesk** [comment]
Usage 

For item recyclerView
balloon?.showAlignBottom(root.fragmentProductBannersRv.getChildViewHolder(root.fragmentProductBannersRv.getChildAt(0)).itemView)

For BottomNavigation
balloon?.showAlignTop(requireActivity().bottom_navigation.rootView.findViewById(NavigationBottom.ACTION_QRCODE.id))

**Comment by caiolesk** [comment]
![recycler_focus](https://user-images.githubusercontent.com/37921435/98165771-35817800-1ec5-11eb-89e7-bf16a8101dd9.png)

On item of recyclerview

**Comment by skydoves** [comment]
Try this:
```kotlin
.setOverlayShape(BalloonOverlayCircle(radius = 0f))
```

**Comment by caiolesk** [comment]
Work nice, thanks for reply

**Comment by caiolesk** [comment]
I have other problem on lowers lvl api, 17, 19... balloon dons't display, on last 2 menu items of BottomNavigation, the overlay is displaying.
Factory create:
fun create(factory: TypeBalloonFactory): Balloon {
        typeBalloonFactory = factory
        return createBalloon(context) {
            setArrowSize(ARROW_DEFAULT)
            setWidthRatio(WIDTH_MEDIUM)
            setHeight(factory.height)
            setArrowPosition(INITIAL)
            setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
            setArrowOrientation(factory.arrowOrientation)
            setCornerRadius(CORNER_DEFAULT)
            setAlpha(ALPHA_DEFAULT)
            setText(context.getString(factory.bodyText))
            setTextSize(TEXT_SIZE_DEFAULT)
            setTextIsHtml(true)
            setTextColorResource(R.color.color_black)
            setBackgroundColorResource(R.color.color_white)
            setBalloonAnimation(BalloonAnimation.OVERSHOOT)
            setLifecycleOwner(fragmentLifeCycle)
            setIsVisibleOverlay(true)
            setOverlayColorResource(R.color.black_overlay)
            setBalloonOverlayAnimation(BalloonOverlayAnimation.FADE)
            setOverlayShape(BalloonOverlayCircle(radius = 0f))
            setOverlayColor(ContextCompat.getColor(context, R.color.black_overlay))
        }
    }

Reference of view:
    override fun onStepFive() {
        createBalloon(
                typeBalloonFactory = TypeBalloonFactory.STEP_FIVE,
                view = requireActivity().bottom_navigation.rootView.findViewById(NavigationBottom.ACTION_WINNERS.id),
                showAlign = ShowAlign.TOP
        )
    }

    override fun onStepSix() {
        createBalloon(
                typeBalloonFactory = TypeBalloonFactory.STEP_SIX,
                view = requireActivity().bottom_navigation.rootView.findViewById(NavigationBottom.ACTION_ACCOUNT.id),
                showAlign = ShowAlign.TOP
        )
    }

**Comment by caiolesk** [comment]
![balloon-not-display](https://user-images.githubusercontent.com/37921435/98242048-9901b900-1f4a-11eb-8b5e-b4ab9ea5eb24.png)

**Comment by skydoves** [comment]
Is the showing correctly to the other items?
