### ISSUE TITLE
Balloon dons't display on lowers apis 17,19 ...

### ISSUE THREAD

**Issue by caiolesk** [skydoves/Balloon#116]
**Please complete the following information:**
- Library Version [1.2.4]
- Affected Device(s) [Nexus 4 api 17, Nexus 5X api 19]
 
**Describe the Bug:**

Balloon dons't display, on last 2 menu items of BottomNavigation, the overlay is displaying.

**Expected Behavior:**

The first three menuitem works correctly, only the last two do not appear

![balloon-not-display](https://user-images.githubusercontent.com/37921435/98242465-4b398080-1f4b-11eb-8b86-548d640d4563.png)

**Comment by caiolesk** [comment]
Factory create:

fun create(factory: TypeBalloonFactory): Balloon {
typeBalloonFactory = factory
return createBalloon(context) {
setArrowSize(ARROW_DEFAULT)
setWidthRatio(WIDTH_MEDIUM)
setHeight(factory.height)
setArrowPosition(INITIAL)
setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
setArrowOrientation(factory.arrowOrientation)
setCornerRadius(CORNER_DEFAULT)
setAlpha(ALPHA_DEFAULT)
setText(context.getString(factory.bodyText))
setTextSize(TEXT_SIZE_DEFAULT)
setTextIsHtml(true)
setTextColorResource(R.color.color_black)
setBackgroundColorResource(R.color.color_white)
setBalloonAnimation(BalloonAnimation.OVERSHOOT)
setLifecycleOwner(fragmentLifeCycle)
setIsVisibleOverlay(true)
setOverlayColorResource(R.color.black_overlay)
setBalloonOverlayAnimation(BalloonOverlayAnimation.FADE)
setOverlayShape(BalloonOverlayCircle(radius = 0f))
setOverlayColor(ContextCompat.getColor(context, R.color.black_overlay))
}
}

Reference of view:

override fun onStepFive() {
createBalloon(
typeBalloonFactory = TypeBalloonFactory.STEP_FIVE,
view = requireActivity().bottom_navigation.rootView.findViewById(NavigationBottom.ACTION_WINNERS.id),
showAlign = ShowAlign.TOP
)
}

override fun onStepSix() {
    createBalloon(
            typeBalloonFactory = TypeBalloonFactory.STEP_SIX,
            view = requireActivity().bottom_navigation.rootView.findViewById(NavigationBottom.ACTION_ACCOUNT.id),
            showAlign = ShowAlign.TOP
    )
}

**Comment by skydoves** [comment]
Is the showing correctly to the other items?

**Comment by caiolesk** [comment]
Yes

![balloon1](https://user-images.githubusercontent.com/37921435/98243103-3dd0c600-1f4c-11eb-8968-d4316f19bcee.png)
![balloon2](https://user-images.githubusercontent.com/37921435/98243105-3f01f300-1f4c-11eb-8343-1a2d1ae7bfcb.png)

**Comment by skydoves** [comment]
How about removing the `setWidthRatio` or giving a small value?

**Comment by caiolesk** [comment]
Removing de  setWidthRatio dosn't work, using private const val WIDTH_MEDIUM = 0.5f work on 4 menu item, and using private const val WIDTH_MEDIUM = 0.2f work on last menu item. What I should do ? =s

![small-0 5](https://user-images.githubusercontent.com/37921435/98245151-41198100-1f4f-11eb-9c0f-264e121316c3.png)
![small-0 2](https://user-images.githubusercontent.com/37921435/98245156-42e34480-1f4f-11eb-85ea-6270e5255aa7.png)

**Comment by caiolesk** [comment]
Default config

companion object {
        private const val INITIAL = 0.5f
        private const val ARROW_DEFAULT = 10
        private const val CORNER_DEFAULT = 4f
        private const val ALPHA_DEFAULT = 1f
        private const val TEXT_SIZE_DEFAULT = 14f
        private const val WIDTH_MEDIUM = 0.5f
        private const val HEIGHT_MEDIUM = 70
    }

**Comment by skydoves** [comment]
Hi, @caiolesk sorry for the late reply.
In this case, we should show the Balloon over the NagivationView (an anchor view).
And regardless of the screen resolution, the positions of the menu are all the same.  (0.1 0.3 0.5 0.7 0.9)

```kotlin
.setArrowPosition(0.5f) //  (0.1 0.3 0.5 0.7 0.9)
```

**Comment by caiolesk** [comment]
Works nice! thanks for help!!
