### ISSUE TITLE
Add preference for showing balloons after N:th times

### ISSUE THREAD

**Issue by ptornhult** [skydoves/Balloon#117]
**Is your feature request related to a problem?**

No, this is only internal to my use case. 

I want to display the balloon only once the user has visited the feature N-number of times. Since there is an internal preferences store in Balloon this option would be easy to add there, but right now I had to create my own wrapper for this, bypassing the internal preferences entirely

**Describe the solution you'd like:**

Add another setting to `Balloon.Builder` called something like `setShowAfterCount` which would prevent the Balloon from appearing until the counter has been reached. (This should of course also delay the internal times counter in BalloonPreferences from being incremented until the Balloon is actually displayed)

**Describe alternatives you've considered:**

Writing an external wrapper lib with preferences that handles this. Here is an example for iOS/Swift which kind of explains the idea: https://github.com/danielsaidi/Tutti/blob/master/Sources/Tutti/Onboarding/DelayedOnboarding.swift

**Comment by ptornhult** [comment]
Do you accept pull request, I could probably fix this, but I didn't see any contributor doc so I'm not sure if you have any guide lines?

**Comment by skydoves** [comment]
Hi, thanks for leaving an issue.

In this case, I suggest using [this library](https://github.com/skydoves/only).
The [Only](https://github.com/skydoves/only) provides many kinds of APIs for handling the preferences in various situations, and I don't have any plans of integrating them into the Balloon yet.  I think this library should handle pop-ups purely, So this library provides only basic APIs for handling persistence.

Thanks!
