### ISSUE TITLE
Automatic positioning of arrow

### ISSUE THREAD

**Issue by ptornhult** [skydoves/Balloon#118]
**Is your feature request related to a problem?**

We'd like to have the arrow point to the center of the view it's anchored to. Having only an option of positioning the arrow on a fractional scale (0.0 - 1.0), while not knowing where the Balloon will appear is a huge problem when trying to support different screen densities.

Since the Balloon can both change size and position depending on the constraints we give it and the screen size, not being able to dynamically calculate the arrow position makes this impossible to support atm. 

**Describe the solution you'd like:**

Instead of using `setArrowPosition` I'd like for there to be a setting to automatically center the arrow relative to the Balloon and the `anchor` view. 

**Describe alternatives you've considered:**

Provide a callback with reference to both the Balloon and the `anchor` view (once the balloon view has been created and positioned, but it could be invisible at this point) which would allow us to return the arrow position in relation to these 2 views. I.e.
```
interface ArrowPositionCallback {
    fun getCalculatedArrowPosition(anchor: View, balloon: View)
}
```

**Comment by skydoves** [comment]
Hi, @ptornhult Thanks for your issue.
We can determine the constraints of the arrow positioning using the ArrowConstraints.

```koitlin
// if an arrowPosition is 0.5, the arrow will be positioned center of the anchor view.
.setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
.setArrowPosition(0.5f)
```

**Comment by skydoves** [comment]
#68
