### ISSUE TITLE
Preference name not working correctly

### ISSUE THREAD

**Issue by artalejo** [skydoves/Balloon#12]
**Please complete the following information:**
- Library Version -> v1.0.7
 
Preference name not working correctly due to the fact that is being retrieved from sharedPreferences with the following prefix `SHOWED_UP`, but when checking the actual sharedPreferences value, is actually saved with a double prefix like -> SHOWED_UP_SHOWED_UP<PREF_NAME>.

**Comment by skydoves** [comment]
@artalejo 
Hi, It will be fixed soon.
Thank you for your issue! :)

**Comment by skydoves** [comment]
@artalejo 
It is released a new version `1.0.8`.
Thank you for your issue!
