### ISSUE TITLE
ClassCastException: android.widget.RelativeLayout cannot be cast to android.widget.FrameLayout

### ISSUE THREAD

**Issue by MujammilAhamed** [skydoves/Balloon#120]
- Library-Version - 1.2.5
- Affected Device(s) Google Pixel 2XL 
OS - Android 11
 
The crash occurs when casting this,

java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to android.widget.FrameLayout
        at com.skydoves.balloon.databinding.LayoutBalloonBinding.bind(LayoutBalloonBinding.java:82)
        at com.skydoves.balloon.databinding.LayoutBalloonBinding.inflate(LayoutBalloonBinding.java:73)
        at com.skydoves.balloon.Balloon.<init>(Balloon.kt:97)
        at com.skydoves.balloon.Balloon$Builder.build(Balloon.kt:1677)

Material Version Used - 1.1.0
LifeCycle Version - 2.3.0-beta01

I was using 1.1.9 before this. After updating to 1.2.0+ versions the above crash appears

**Comment by skydoves** [comment]
Hi, this is included in the `1.2.5`. Could you refresh and redownload the `1.2.5` version?

```
./gradlew build --refresh-dependencies
```
or
```
rm -rf $HOME/.gradle/caches/
```

**Comment by MujammilAhamed** [comment]
@skydoves Tried re-downloading the dependencies

But still, the crash occurs

**Comment by skydoves** [comment]
Is it also happen in the [demo project](https://github.com/skydoves/Balloon/tree/main/app)?
I just tested in the Google Pixel 2XL, but it works fine for me. 🤔

**Comment by MujammilAhamed** [comment]
@skydoves I tried your sample project. But the crash doesn't occur for me.
I'm using your library inside a CustomView which extends ConstranintLayout. Can you give a try like this

**Comment by skydoves** [comment]
Do you use a custom layout with the name `layout_balloon`?
Or try to Clean -> Build your project again.
I think it seems something has problems processing ViewBinding in your IDE.

**Comment by MujammilAhamed** [comment]
No, I'm not using any layout name as "layout_balloon"
Tried Clean -> Re-Build. But still the crash occurs

**Comment by skydoves** [comment]
Hmm.. I need more information about your implementation of the `Builder`.

**Comment by MujammilAhamed** [comment]
Below is the usage
```
viewLifecycleOwner?.let {
            summaryBalloon = BalloonFactoryUtils.getBalloon(
                    context = this.context,
                    lifecycleOwner = it
                )
            }

fun getBalloon(context: Context, lifecycleOwner: LifecycleOwner): Balloon {
        return createBalloon(context) {
            setLayout(R.layout.control_summary)
            setBackgroundColor(ContextCompat.getColor(context, android.R.color.transparent))
            setArrowVisible(false)
            setWidthRatio(1.0f)
            setElevation(0)
            setCornerRadius(0.0F)
            setDismissWhenShowAgain(true)
            setDismissWhenTouchOutside(true)
            setHeight(120)
            setLifecycleOwner(lifecycleOwner)
        }
    }
```

**Comment by skydoves** [comment]
Thanks.
Does your `R.layout.control_summary` XML uses the `RelativeLayout` for the root?

**Comment by MujammilAhamed** [comment]
Using `ConstraintLayout` as the Parent. No `RelativeLayout` is used in that

**Comment by skydoves** [comment]
Can you test using this sample layout instead of your custom layout?
If the same issue occurs, the library should be re-released.

```gradle
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  xmlns:tools="http://schemas.android.com/tools"
  android:layout_width="240dp"
  android:layout_height="wrap_content"
  android:gravity="center"
  android:orientation="vertical"
  android:padding="12dp">

  <com.google.android.material.imageview.ShapeableImageView
    android:id="@+id/circleImageView"
    android:layout_width="55dp"
    android:layout_height="55dp"
    android:layout_gravity="center_horizontal"
    android:layout_marginTop="10dp"
    android:scaleType="centerCrop"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toTopOf="parent"
    app:shapeAppearanceOverlay="@style/CircleImageStyle" />

  <TextView
    android:id="@+id/text"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="center_horizontal"
    android:layout_marginTop="5dp"
    android:text="skydoves"
    android:textColor="@color/background900"
    android:textSize="16sp"
    android:textStyle="bold"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toBottomOf="@id/circleImageView"
    tools:ignore="HardcodedText" />

  <TextView
    android:id="@+id/text2"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="center_horizontal"
    android:layout_marginTop="5dp"
    android:gravity="center"
    android:text="Love coffee, music, magic tricks and writing poems."
    android:textColor="@color/background800"
    android:textSize="14sp"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toBottomOf="@id/text"
    tools:ignore="HardcodedText" />

  <Button
    android:id="@+id/button_edit"
    android:layout_width="match_parent"
    android:layout_height="36dp"
    android:layout_marginTop="16dp"
    android:background="@drawable/round_button_skyblue"
    android:text="Edit"
    android:textAllCaps="false"
    android:textColor="@color/white"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toBottomOf="@id/text2"
    tools:ignore="HardcodedText" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

**Comment by MujammilAhamed** [comment]
Tried your sample layout with my Custom View. But still, the same crash occurs

**Comment by skydoves** [comment]
@MujammilAhamed 
Just published a new version `1.2.6`.
If the same crash occurs in this version, It seems to need a sample project for getting specifications of this issue.

**Comment by MujammilAhamed** [comment]
Let me try with your latest version. If it doesn't work I'll upload a sample project

**Comment by skydoves** [comment]
@MujammilAhamed 
Any updates?

**Comment by MujammilAhamed** [comment]
Let me work on the Sample Project and get back to you

**Comment by MujammilAhamed** [comment]
I tried with the Sample Project with a Single CustomView. But the crash doesn't happen. But in my Project I'm using it inside Multiple Custom View's(CustomView1->CustomView2->CustomView3->CustomView4->Balloon). Last CustomView has the Balloon View.

**Comment by skydoves** [comment]
Hi, the new version `1.2.9` is released.
Please test with the [balloon extension](https://github.com/skydoves/Balloon/blob/main/app/src/main/java/com/skydoves/balloondemo/recycler/SampleAdapter.kt#L53) for the View and [Balloon.Factory](https://github.com/skydoves/Balloon/blob/main/app/src/main/java/com/skydoves/balloondemo/factory/ViewHolderBalloonFactory.kt) class.
The `balloon extension` will decide the lifecycleowner of the balloon depending on your view's lifecycle.
And you can initialize the instance of the Balloon like this in your `CustomView`.
```kotlin
private val viewHolderBalloon by balloon<ViewHolderBalloonFactory>()
```

**Comment by skydoves** [comment]
I will close this issue.
If you still face this issue again, please open it again. Thanks :)
