### ISSUE TITLE
Balloon on the list problem.

### ISSUE THREAD

**Issue by sqsong66** [skydoves/Balloon#122]
In the sample, set the balloon arrow on bottom, when click the bottom item of list and show the balloon, the balloon on the top,and the arrow on the top too. So can we auto detect the balloon position and change the arrow position?
![20201118114847.jpg](https://i.loli.net/2020/11/18/4JHP9TytqhgADmp.jpg)

**Comment by skydoves** [comment]
It has been released a new version [1.3.1](https://github.com/skydoves/Balloon/releases/tag/1.3.1)!
Please check about this issue :)
