### ISSUE TITLE
Arrow is hidden behind Balloon

### ISSUE THREAD

**Issue by osrl** [skydoves/Balloon#123]
**Please complete the following information:**
- Library Version v1.2.5
 
**Describe the Bug:**

Arrow is hidden behind the balloon. I'm using the same example as "Create using kotlin dsl" section
 
![screen](https://user-images.githubusercontent.com/781453/99909751-60f4c700-2cfb-11eb-9cfb-5fe6a486501f.png)

When I inspected the layout, I discovered that balloon_content's padding is 0, even if it's set on `initializeBalloonContent` function correctly.

![Screen Shot 2020-11-22 at 19 42 36](https://user-images.githubusercontent.com/781453/99909758-6d791f80-2cfb-11eb-8edc-c5bca788c2fb.png)

**Expected Behavior:**

balloon_content's padding should be set correctly

**Comment by osrl** [comment]
One more note: custom layout's paddings are somehow removed too

**Comment by skydoves** [comment]
@osrl 
Hmm... Can you let me show your implementation of the `createBalloon` ?

**Comment by osrl** [comment]
Sure, I got it from README and removed some irrelevant setup code.

```
val balloon = createBalloon(context) {
  setArrowSize(10)
  setWidthRatio(1.0f)
  setHeight(65)
  setArrowPosition(0.7f)
  setCornerRadius(4f)
  setAlpha(0.9f)
  setText("You can access your profile from now on.")
  setBackgroundColorResource(R.color.colorPrimary) //used a red color with alpha 
  setBalloonAnimation(BalloonAnimation.FADE)
  setLifecycleOwner(lifecycleOwner)
}
```

Also please note the two different colors on the balloon. I'm not sure why this happens. Layout inspector didn't even show the view with different color

**Comment by skydoves** [comment]
Um.. this is really difficult to track the issue.
Could you please create an example project?

**Comment by osrl** [comment]
It really depends on my style. This happens when `fitsSystemWindows` is true.

**Comment by skydoves** [comment]
Try this:

### styles.xml
```gradle
<style name="BalloonTheme" parent="Theme.AppCompat.Light">
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="colorAccent">@color/colorAccent</item>
    <item name="android:fitsSystemWindows">false</item>
  </style>
```
### Balloon.Builder
```kotlin
val styledContext: Context = ContextThemeWrapper(context, R.style.BalloonTheme)

    return Balloon.Builder(styledContext)
      .setText("You can edit your profile now!")
      .setArrowSize(10)
      .setWidthRatio(1.0f)
      .setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
      .setArrowPosition(0.5f)
      .setPadding(12)
      .setMarginRight(12)
```

**Comment by skydoves** [comment]
I feel the `android:fitsSystemWindows` attribute should be always `false` for this library, hence It will be included in the next release.
Thanks for your issue :)

**Comment by skydoves** [comment]
@osrl 

This issue is resolved in the new release [1.2.7](https://github.com/skydoves/Balloon/releases).
Thanks for your issue :)

**Comment by skydoves** [comment]
@osrl 
Any updates?

**Comment by osrl** [comment]
It's resolved thanks
