### ISSUE TITLE
After Dismiss First Popup Another is Not Open without Second Time Click

### ISSUE THREAD

**Issue by shreyushah** [skydoves/Balloon#124]
**Please complete the following information:**
- Library Version [e.g. v1.2.6]
- Affected Device(s) [e.g. Samsung Galaxy J7 Pro with Android 9.0]
 
**Describe the Bug:**
- I used This Lib in Bottom Navigation.when I click on any bottom navigation Tab it is open.when I click on second tab first popup dismiss but not open second one.After Click Second Time New PopUp open.please help me for same. 
![BottomPopUP](https://user-images.githubusercontent.com/14278469/100185822-c8cd2c80-2f0a-11eb-9426-bc0ef3b3699a.png)

**Expected Behavior:**
-I want when i click on tab that particular tab popup open and old one dismiss if it is open.

**Comment by skydoves** [comment]
Could you provide an example of the `Balloon.Builder` implementations?
And are two Balloon properties declared differently?

**Comment by shreyushah** [comment]
yes..Declare Differently.Create new instance for each tab.
`class CustomListHomeBalloonFactory : Balloon.Factory() {

    override fun create(context: Context, lifecycle: LifecycleOwner?): Balloon {
        return Balloon.Builder(context)
                .setLayout(R.layout.layout_custom_list)
                .setArrowOrientation(ArrowOrientation.BOTTOM)
                .setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR).setTextGravity(Gravity.CENTER)
                //.setArrowPosition(0.5f)
                .setArrowSize(20)
                .setTextSize(9f)
                .isRtlSupport(BalloonUtils.isRtlLayout())
                .setCornerRadius(6f)
                .setMarginRight(12).setMarginBottom(30)
                .setElevation(7).setWidth(230).setHeight(345)
                .setBackgroundColorResource(R.color.white).setTextGravity(Gravity.CENTER)
                .setBalloonAnimation(BalloonAnimation.FADE)
                .setDismissWhenShowAgain(true)
                .setLifecycleOwner(lifecycle)
                .build()
    }

}`

**Comment by shreyushah** [comment]
@skydoves Please help me for same.I stuck for same Issue.

**Comment by skydoves** [comment]
Hi, @shreyushah 
I just built the demo project using the below codes and it works well.
Could you run the demo project?

### CustomActivity.kt
```kotlin
bottomNavigationView.setOnNavigationItemSelectedListener {
        customTagBalloon.showAlignTop(bottomNavigationView, 130, 0)
        true
}

customTagBalloon.setOnBalloonClickListener {
        customTagBalloon.dismiss()
        editBalloon.showAlignTop(bottomNavigationView, 130, 0)
 }
```
Thanks.

**Comment by shreyushah** [comment]
yes I run..my issue is when one popup open click on another tab open popup should dismiss and new popup should open..in current if one popup open than->click second tab->first dismiss->when second time tab new popup open

**Comment by skydoves** [comment]
Ah, I got it!
Use this method for your `Balloon.Builder`.
```kotlin
setFocusable(false)
```

**Comment by skydoves** [comment]
@shreyushah 
Any updates?

**Comment by shreyushah** [comment]
Will check and let you know.

**Comment by skydoves** [comment]
I will close this issue now.
Please reopen if you would get any related issues.

**Comment by shreyushah** [comment]
@skydoves 
It is working fine now.Thanks for awesome library and support.

**Comment by skydoves** [comment]
Thanks for checking 👍
