### ISSUE TITLE
Arrow not showing if parent of anchor is rtl

### ISSUE THREAD

**Issue by sina-farahzadi** [skydoves/Balloon#125]
- Library Version: I've checked on v1.2.2+
- Affected Device(s): samsung a10/pixel 2
 
If the anchor view's parent layout direction is rtl the calculation for x position of the arrow is incorrect, causes the arrow not to be shown at all.

**Comment by sina-farahzadi** [comment]
Here is an [image](https://imgur.com/a/oOxTY9l) of it. Just add rtl layout direction to the root layout.

**Comment by skydoves** [comment]
Hi, @sina-farahzadi.
This issue is resolved in the new release `1.2.7`.
Thanks for your issue :)

**Comment by sina-farahzadi** [comment]
Hi, @skydoves.
Thank a lot!
