### ISSUE TITLE
Balloom with achor element at extreme right of the screen doesn't show up in android xhpi screens

### ISSUE THREAD

**Issue by jeethesh-kotian** [skydoves/Balloon#127]
**Please complete the following information:**
- Library Version 1.2.6
- Affected Device(s) [Moto G2 with Android 6.0]
 
I have a balloon created on Linear layout which is divided into 3 equal parts. The balloon is aligned to each of the 3 parts. The first 2 parts from the left work perfectly fine for all the screens, but the left anchored balloon works for all device having density above hdpi but doesn't work beyond that including hdpi screens like the Moto G2 screen.

**Providing the code used:**

MainActivity.kt

       productSyncBalloon = Balloon.Builder(this)
            .setArrowSize(10)
            .setArrowOrientation(ArrowOrientation.BOTTOM)
            .setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
            .setArrowVisible(true).setPaddingLeft(16).setPaddingRight(16).setPaddingTop(12).setPaddingBottom(12)
            .setTextSize(12f).setMarginRight(48)
            .setCornerRadius(4f)
            .setTextTypeface(Typeface.BOLD)
            .setText(getString(R.string.hint_product_sync))
            .setOnBalloonDismissListener(this)
            .setTextColor(ContextCompat.getColor(this, R.color.colorPrimary))
            .setBackgroundColor(ContextCompat.getColor(this, R.color.white))
            .setBalloonAnimation(BalloonAnimation.FADE)
            .setLifecycleOwner(this)
            .build()

       demoScheduleBalloon?.showAlignTop(it, product_hint_point, 0, 0)

activity_main.xml

       <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:weightSum="3">
            <View
                android:id="@+id/home_hint_point"
                android:layout_width="0dp"
                android:layout_height="1dp"
                android:layout_weight="1">
            </View>
            <View
                android:id="@+id/demo_hint_point"
                android:layout_width="0dp"
                android:layout_height="1dp"
                android:layout_weight="1">
            </View>
            <View
                android:id="@+id/product_hint_point"
                android:layout_width="0dp"
                android:layout_height="1dp"
                android:layout_weight="1">
            </View>
        </LinearLayout>

**Workaround:**

This thing actually worked when I used showAlignBottom instead of showAlignTop for devices between hdpi and xhdpi. So the hack I tried is as below and it worked:

       val density = resources.displayMetrics.density
       if(density in 1.5..2.0) {
           demoScheduleBalloon?.showAlignBottom(it, product_hint_point, 0, 0)
       }else{
           demoScheduleBalloon?.showAlignTop(it, product_hint_point, 0, 0)
       }

**Expected Behavior:**

I believe it should have worked on all the devices as this issue is only with extreme right-aligned anchors and on hdpi and xhdpi devices.

**Comment by skydoves** [comment]
Is the same issue still occur if you manipulate the sizes? Like below.

```kotlin
.setWidthRatio(1.0f)
```
or
```kotlin
.setWiwdth(600)
.setHeight(10)
```
