### ISSUE TITLE
Resize balloon with a custom layout

### ISSUE THREAD

**Issue by davva1966** [skydoves/Balloon#128]
Hello,

Not a bug but a question. How do I get the balloon to automatically resize to fit a custom layout? I have a custom layout that varies in height (wrap content) but the balloon height stays the same when displayed causing most of the text in the balloon to not be visible.

Thanks for a great library!

/David

**Comment by skydoves** [comment]
Hi, @davva1966 
It seems related to #112

**Comment by davva1966** [comment]
Thank you,

I will read through that and see if that fixes my problem. 

Best regards,

/David
