### ISSUE TITLE
setIconColor not setting icon color

### ISSUE THREAD

**Issue by EurigJones** [skydoves/Balloon#130]
**Please complete the following information:**
- Library Version 1.2.7
 
**Describe the Bug:**

Setting the icon color doesn't seem to work.

Code
    setIconColor(ContextCompat.getColor(context, R.color.white))
    setIconDrawable(ContextCompat.getDrawable(context, R.drawable.uicomponent_icon_info))

**Expected Behavior:**

The icon does not appear white.

**Comment by skydoves** [comment]
Side effect from #82, it will be fixed in the next release.
Thanks for providing this issue :)

**Comment by skydoves** [comment]
Fixed in the new version [1.2.8`](https://github.com/skydoves/Balloon/releases/tag/1.2.8).
Thanks for your issue!

**Comment by EurigJones** [comment]
Awesome. Thankyou 👍
