### ISSUE TITLE
When keyboard appears, is it possible to keep ballon anchored?

### ISSUE THREAD

**Issue by EurigJones** [skydoves/Balloon#132]
**Is your feature request related to a problem?**

I have a balloon anchored to a View (TextInputEditText in this case), but when the keyboard and balloon are on the screen, at the same time it pushes the balloon out of the way if there is not enough room. This makes my pointer point to the incorrect place.

My workaround for now is to dismiss the keyboard when the balloon appears, but ideally it would be good to get the bakloon to retain its position.

I have not set this as a bug, as I thought it may be desired behaviour or I might be missing something?

**Comment by skydoves** [comment]
Hi, @EurigJones sorry for the late reply.
In most cases, the balloon will not be affected by the keyboard.
The balloon only will be affected by the anchor view, so if your anchor view moves when the keyboard appears, the balloon will be moved together. If you face specific cases related to this issue again in the new version `1.3.3`, please describe details or provide some examples. Thanks!
