### ISSUE TITLE
Balloon with custom layout displaying out of the screen on Android SDK 21

### ISSUE THREAD

**Issue by vijtheveg** [skydoves/Balloon#133]
- com.github.skydoves:balloon v1.2.6
- Emulator, Android SDK 21

Using a custom layout is causing the balloon to display out of the screen on Android SDK 21. This happens consistently for some anchor views, but not for other anchor views (when the same custom layout is being used). The same code works correctly in both cases on API 30.

Please help!

### **Problem when Expense button is anchor**
![image](https://user-images.githubusercontent.com/8265580/102016476-40aeaa00-3d87-11eb-9720-360b738161da.png)

### **Working correctly when Income button is anchor**
![image](https://user-images.githubusercontent.com/8265580/102016571-a26f1400-3d87-11eb-954d-a44bea870e94.png)

The code I am using to display the balloon is below:
```java
        Resources resources = mContext.getResources();
        Balloon balloon = new Balloon.Builder(mContext)
            .setLayout(contentView)
            .setLifecycleOwner(mLifecycleOwner)
            .setBackgroundColor(mContext.getResources().getColor(R.color.colorTertiaryAccent))
            .setWidthRatio(1.0f)
            .setElevation(DimensionHelper.getDimensionInDp(resources, R.dimen.tiny_space))
            .setCornerRadius(DimensionHelper.getDimensionInDp(resources, R.dimen.tiny_space))
            .setMargin(DimensionHelper.getDimensionInDp(resources, R.dimen.small_space))
            .setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
            .setArrowOrientation(mArrowOrientation)
            .setArrowPosition(0.25f)
            .setArrowSize(DimensionHelper.getDimensionInDp(resources, R.dimen.medium_space))
            .build();

        balloon.measureTextWidth(captionTextView); // See https://github.com/skydoves/Balloon/issues/112
        if (mArrowOrientation == ArrowOrientation.TOP)
            balloon.showAlignBottom(anchorView);
        else
            balloon.showAlignTop(anchorView);
```

**Comment by maverick-sahil** [comment]
Getting same issue with Android 6.0. balloon.showAlignTop(anchorView) shows balloon at the bottom of anchorView instead of top.

**Comment by skydoves** [comment]
This issue has been resolve in the latest release.
The problem is the measuring exact height size for the custom layout that includes `TextView` was not correct.
