### ISSUE TITLE
Popover shadow is getting cut in case giving specific height/width ?

### ISSUE THREAD

**Issue by haliltprkk** [skydoves/Balloon#134]
- Library Version [1.2.8]

 I am using a custom layout which contains a scrollView(I tried to remove scrollView but it didn't solve)

```
      Balloon balloon = new Balloon.Builder(context)
                .setArrowSize(10)
                .setLayout(R.layout.custom_leg_info_dialog)
                .setArrowOrientation(ArrowOrientation.RIGHT)
                .setHeight(layoutHeightDp)
                .setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
                .setWidthRatio(0.7f)
                .setArrowDrawable(drawable)
                .setCornerRadius(6f)
                .setElevation(5)
                .setAlpha(1f)
                .setBalloonAnimation(BalloonAnimation.ELASTIC)
                .setBackgroundColor(ContextCompat.getColor(context, R.color.white))
                .setBalloonAnimation(BalloonAnimation.FADE)
                .build();
```
It looks like this,

<img width="354" alt="Screen Shot 2020-12-15 at 17 29 40" src="https://user-images.githubusercontent.com/24190349/102227880-1f6eca80-3efb-11eb-88b4-0cd7bc95bb7d.png">

Also, I have noticed that same thing happening for the case giving specific width

<img width="454" alt="Screen Shot 2020-12-15 at 17 30 46" src="https://user-images.githubusercontent.com/24190349/102228015-45946a80-3efb-11eb-9f12-6ec57b2a5e53.png">

I have tried lots of things but I couldn't  find a solution.

Thank you so much in advance!

**Comment by skydoves** [comment]
Released a new version `1.2.9`!
Thanks for your issue :)
