### ISSUE TITLE
Wrap content for custom drawable arrow size

### ISSUE THREAD

**Issue by SaikrishnaRajaraman** [skydoves/Balloon#135]
Please give an option for having wrap_content for custom drawable for arrow size.

**Comment by skydoves** [comment]
Hi, @SaikrishnaRajaraman 
It seems to need a new size spec for customizing the size of the arrow and icon.
I will include new specs related to this issue in the next version.
Thanks for your issue.

**Comment by skydoves** [comment]
Released a new version `1.2.9`.
You can resolve it using the below way.
```kotlin
.setArrowSize(BalloonSizeSpec.WRAP)
```
Thanks for your issue :)
