### ISSUE TITLE
Showing balloons automatically when calling show in onResume / onCreate

### ISSUE THREAD

**Issue by adrcotfas** [skydoves/Balloon#136]
**Please complete the following information:**
- Library Version [e.g. v1.2.9]
- Affected Device(s) Emulator with API level 30 and Samsung device with API level 26
 
**Describe the Bug:**
I'm not sure if this is a bug.
Balloons don't show automatically when calling the `show` methods inside `onCreate` or `onResume` but work just fine if I place the `show` inside of a button `onClickListener`

**Expected Behavior:**

Balloons should show automatically when `show` is called from `onResume` / `onCreate` inside Activities or Fragments.

**Comment by skydoves** [comment]
Hi, @adrcotfas 
Could you try to show the Balloon in the `post` method?
```kotlin
anchorView.post {
 // show balloon
}
```

**Comment by adrcotfas** [comment]
@skydoves Thank you for the quick answer!
Your suggestion is the solution.
