### ISSUE TITLE
There is an unintended space between the arrow and the message box.

### ISSUE THREAD

**Issue by eminuluyol** [skydoves/Balloon#139]
**Please complete the following information:**
- Library Version v1.2.9
- Affected Device Samsung Galaxy s8+ with Android 9.0
 
**Describe the Bug:**

My implementation is as below:

<img width="552" alt="Screenshot 2021-01-05 at 17 05 35" src="https://user-images.githubusercontent.com/15149506/103669131-40fe2780-4f78-11eb-8f04-07ed8427e7a9.png">

This is how it looks like:

<img width="78" alt="Screenshot 2021-01-05 at 17 01 41" src="https://user-images.githubusercontent.com/15149506/103668736-b7e6f080-4f77-11eb-8a45-60f2146ab9c1.png">

I thought maybe the elevation would cause the problem but even when I set it to 0 the result is the same.

**Comment by skydoves** [comment]
Hi, @eminuluyol 
Hmm.. Can you check if the same issue occurs when you give an `arrowPadding`?
```
setArrowTopPadding(4)
```
It seems to occur in some specific devices. 
I will check out the details soon. Thanks for your issue!

**Comment by eminuluyol** [comment]
Hey! @skydoves thank you very much for your fast response. Unfortunately, I have already tried setting padding-top to arrow and it only makes the arrow look smaller. I have also tested this on an emulator (Pixel XL API 29) and the result was identical.

**Comment by skydoves** [comment]
Hi, this issue has been fixed in the new release [1.3.0](https://github.com/skydoves/Balloon/releases/tag/1.3.0).
Thanks for your issue :)
