### ISSUE TITLE
Question: How to show on menuItem?

### ISSUE THREAD

**Issue by jrcacd** [skydoves/Balloon#142]

**Comment by skydoves** [comment]
I didn't try that, but if you can get a `View` from the `menu`, you can use it for showing the Balloon.

```java 
final MenuItem alertMenuItem = menu.findItem(R.id.activity_main_alerts_menu_item);
FrameLayout rootView = (FrameLayout) alertMenuItem.getActionView();
balloon.showAlignBottom(rootView)
```

**Comment by jrcacd** [comment]
Not working. Its crashing.

menu?.findItem(R.id.buy)?.apply {           
                createBalloon(this@GeralActivity) {
                    setArrowSize(10)
                    setWidth(BalloonSizeSpec.WRAP)
                    setHeight(65)
                    setArrowPosition(0.7f)
                    setCornerRadius(4f)
                    setAlpha(0.9f)
                    setText("Message.")
                    setTextColorResource(R.color.white)
                    setIconDrawableResource(R.drawable.ic_baseline_shopping_basket_24)
                    setBackgroundColorResource(R.color.colorPrimary)
                    setBalloonAnimation(BalloonAnimation.OVERSHOOT)
                    setLifecycleOwner(lifecycleOwner)
                }.show(this.actionView as FrameLayout)
        }

**Comment by skydoves** [comment]
For implementing this, you should override the `setActionView` and create your [own menu layout](https://developer.android.com/reference/android/view/MenuItem.html#setActionView(android.view.View)).
In your case, I guess the `actionView` will be returned null, so it will crashes.
The key solution is getting an anchor from your `ContextMenu` and show the balloon on your anchor.

**Comment by skydoves** [comment]
Hi, @jrcacd!
Please open this issue again if you occur the same issue.
Thanks :)

**Comment by raquezha** [comment]
This helped me get the view from the menu

```
/**
* pass toolbar and menu item id, i.e. R.id.menu_refresh
*/
@Nullable
@Throws(
    IllegalAccessException::class,
    NoSuchFieldException::class
)
fun getMenuItemView(toolbar: Toolbar?, @IdRes menuItemId: Int): View? {
    val mMenuView: Field = Toolbar::class.java.getDeclaredField("mMenuView")
    mMenuView.setAccessible(true)
    val menuView: Any? = mMenuView.get(toolbar)
    (menuView as ViewGroup).children.forEach {
        if(it.id == menuItemId) {
            return it
        }
    }
    return null
}
```

stackoverflow link: https://stackoverflow.com/a/62533513

usage:

```
val menuItemView: View? =  getMenuItemView(binding.toolbar, R.id.mBell)

menuItemView?.showAsDropDown(activeOrderBalloon)
```

I've used binding to access the toolbar, and passed the id of the menu item
