### ISSUE TITLE
getArrowConstraintPositionX may have a calculate mistake

### ISSUE THREAD

**Issue by amberkira** [skydoves/Balloon#146]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**
I don't know why there are 3 branches judgement here. 
         val position =
              (anchor.width) * builder.arrowPosition + anchorX - balloonX - arrowHalfSize
            when {
              position <= getDoubleArrowSize() -> minPosition
              position > getMeasureWidth() - getDoubleArrowSize() -> maxPosition
              else -> position
            }

 if my anchorView width is quite small， the position is definitely less then double ArrowSize then x = minPosition. but actually the position is alivalble and I don't need to show my arrow in minPostion  
**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Hi, could you attach some screenshots for showing this issue?

**Comment by skydoves** [comment]
If you did not resolve this issue, Please re-open this later.
Thanks.

**Comment by amberkira** [comment]
![F9F56DE93FF734593278230141BE5C19](https://user-images.githubusercontent.com/16331534/108708580-93a59a00-754c-11eb-9faf-4b848b7861f8.jpg)

like this the arrow is not at the correct position because the getArrowConstraintPositionX() method return 0 (which is minPosition) 

my code as below:
currentBubble = createBalloon(context) {
            setArrowSize(15)
            setArrowAlignAnchorPaddingRatio(0f)
            if (showAlignTop) {
                setArrowOrientation(ArrowOrientation.BOTTOM)
            }else {
                setArrowOrientation(ArrowOrientation.TOP)
            }
            setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
            setArrowAlignAnchorPaddingRatio(0.5f)
            setArrowAlignAnchorPadding(7.dp)
            setLayout(contentView)
            setArrowDrawableResource(R.drawable.ic_popup_arrow)
            setBackgroundColor(Color.TRANSPARENT)
            setElevation(0)
            setAlpha(1f)
            setCornerRadius(0f)
            setBalloonAnimation(BalloonAnimation.FADE)
            setFocusable(false)
            setDismissWhenTouchOutside(true)
            setDismissWhenClicked(true)
            setOnBalloonDismissListener { cb.invoke() }
            setLifecycleOwner(context as LifecycleOwner)
        }
