### ISSUE TITLE
Option to switch arrow orientation based on the tooltip position

### ISSUE THREAD

**Issue by anukmc** [skydoves/Balloon#147]
**Is your feature request related to a problem?**

It would be nice to be able to switch the arrow orientation if the tooltip is rendered above or below the anchor view.
So for example, if the tooltip is shown by using showAlignBottom() but it's actually shown on top of the anchor view because there is no space to display it, the arrow should switch as well.

**Describe the solution you'd like:**

Before showing tooltip for the first time detect wether the tooltip will be rendered above or below the anchor view by calculating the difference between the anchor position and the height of screen while taking into account the height of the tooltip. Based on that show the arrow with the correct orientation.

**Comment by skydoves** [comment]
It's been released a new version [1.3.1](https://github.com/skydoves/Balloon/releases/tag/1.3.1)!
Please check about this issue :)

**Comment by anukmc** [comment]
Thank you for this. Now it's working. 
But it seems that what _setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)_ did before (meaning, if an arrowPosition is 0.5, the arrow will be positioned center of the anchor view.) is not working anymore.
Is this an issue or there is a different setting for that and I am missing something?

**Comment by skydoves** [comment]
`ArrowConstraints` renamed to `ArrowPositionRules`.
Thanks :)

**Comment by anukmc** [comment]
Thank you so much.
