### ISSUE TITLE
Shadow gets cut at the bottom of the tooltip

### ISSUE THREAD

**Issue by anukmc** [skydoves/Balloon#150]
**Please complete the following information:**
- Library Version v1.3.0
 
**Describe the Bug:**
 
I am using a custom layout for the tooltip that contains a scrollView that has a textView inside. 
When I set elevation the shadow is cut at the bottom of the tooltip (see attached screenshot)

 val balloon: Balloon = Balloon.Builder(context)
                        .setLayout(R.layout.balloon_layout)
                        .setArrowSize(15)
                        .setWidth(400)
                        .setArrowColorResource(R.color.white)
                        .setBackgroundColorResource(R.color.white)
                        .setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
                        .setArrowOrientation(arrowOrientation)
                        .setArrowPosition(0.5f)
                        .setTextSize(15f)
                        .setCornerRadius(6f)
                        .setElevation(5)
                        .setAlpha(1.0f)
                        .setTextColor(ContextCompat.getColor(context, R.color.steel))
                        .setBalloonAnimation(BalloonAnimation.FADE)
                        .build()

<img width="8114" alt="Screen Shot 2021-01-27 at 3 59 43 PM" src="https://user-images.githubusercontent.com/78049085/106002690-18baa200-60ba-11eb-8fda-7b9aed77ef05.png">

**Comment by Canato** [comment]
This looks like you parent view is directly connect with it. Can you try to set `setMarginBottom(8)` and see if fix?

**Comment by anukmc** [comment]
Unfortunately this doesn't seem to fix the issue.

**Comment by skydoves** [comment]
Released a new version [1.3.1](https://github.com/skydoves/Balloon/releases/tag/1.3.1)!
Please check about this issue :)
