### ISSUE TITLE
Shadow is displayed around Ballon Pop up

### ISSUE THREAD

**Issue by chaitanya-vanapamala** [skydoves/Balloon#154]
**Please complete the following information:**
- Library Version : 1.3.1
- Tried on Affected Device(s) Android 10
 
**Describe the Bug:**

The balloon is surrounded by a shadow, I have used the code which is shown in the readme.
When I have tried sample app from the repo its working, But when I included the library in my application its showing with shadow.

<img width="229" alt="Screenshot 2021-02-02 155520" src="https://user-images.githubusercontent.com/20322203/106587155-45b1fd80-656f-11eb-89c5-c01e17111f8b.png">

Following the code :

> 
        val balloon = Balloon.Builder(mContext)
                .setText("You can edit your profile now!")
                .setArrowSize(10)
                .setWidthRatio(1.0f)
                .setHeight(BalloonSizeSpec.WRAP)
                .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
                .setArrowPosition(0.5f)
                .setPadding(12)
                .setMarginRight(12)
                .setMarginLeft(12)
                .setTextSize(15f)
                .setCornerRadius(0f)
                .setIsVisibleArrow(false)
                .setOverlayPadding(0f)
                .setTextColorResource(R.color.white)
                .setIconDrawableResource(R.drawable.ic_edit)
                .setBackgroundColorResource(R.color.azure)
                .setBalloonAnimation(BalloonAnimation.ELASTIC)
                .build()

**Expected Behavior:**

The shadow should be removed only the balloon should be displayed

**Comment by skydoves** [comment]
Hi, @chaitanya-vanapamala 
Could you try to use `1.3.2-alpha01`?

**Comment by chaitanya-vanapamala** [comment]
Hi, @skydoves ,
After updating to 1.3.2-alpha01, Balloon is not at displaying.

**Comment by skydoves** [comment]
Can I know your device information?

**Comment by skydoves** [comment]
I guess your `style.xml` influence that kind of result.
Please copy and paste your project's `style.xml` file :)

**Comment by rkrishnan2012** [comment]
Try setting `.setArrowElevation(0)`.
