### ISSUE TITLE
#74 reocccured

### ISSUE THREAD

**Issue by FreeHitoshiSuzuki** [skydoves/Balloon#155]
**Please complete the following information:**
- Library Version 1.3.1
- Affected Device(s)  HUWEI P10 lite with Android 7.0
 
**Describe the Bug:**

https://github.com/skydoves/Balloon/issues/74

This problem reocccured. 

It deleted the process after fixing it once, can you give me a reason?

This commit fixed commit.
https://github.com/skydoves/Balloon/commit/8e7df438249b7e410edfc9be40f6ca9ca7b36faf

This fixed change was removed below commit.
https://github.com/skydoves/Balloon/commit/590f1f1a64f95636269f907e4372890630237fde

**Comment by skydoves** [comment]
Thanks for reporting this issue :)
This issue is included in the `1.3.2-SNAPSHOT`.
You can check [here](https://github.com/skydoves/balloon#snapshot--) how to import the snapshot in your project.

**Comment by skydoves** [comment]
A new [1.3.2](https://github.com/skydoves/Balloon/releases/tag/1.3.2) stable is released.
Thanks for your issue :)
