### ISSUE TITLE
Square shadown in the arrow

### ISSUE THREAD

**Issue by epool** [skydoves/Balloon#156]
First of all thank you for all your work/help on this library.

**Please complete the following information:**
- Library Version: v1.3.1
- Affected Device(s): Emulator Pixel 3 API 29
 
**Describe the Bug:**

There is a weird square shadow in the arrow part

```java
binding.ivTooltip.setOnClickListener(tooltipView -> new Balloon.Builder(tooltipView.getContext())
        .setArrowSize(48)
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .setBackgroundColorResource(R.color.tooltip_background)
        .setTextColorResource(R.color.white)
        .setCornerRadiusResource(R.dimen.margin_md)
        .setWidthRatio(1f)
        .setPaddingResource(R.dimen.margin_xs)
        .setMarginLeftResource(R.dimen.margin_xl)
        .setMarginRightResource(R.dimen.margin_xl)
        .setTextSizeResource(R.dimen.font_mdl)
        .setDismissWhenClicked(true)
        .setTextResource(tooltipInfoRes)
        .setLifecycleOwner(getViewLifecycleOwner())
        .build()
        .showAlignTop(tooltipView)
);
```

<img width="151" alt="Screenshot 2021-02-10 at 14 19 19" src="https://user-images.githubusercontent.com/1973616/107569575-140fe680-6bae-11eb-9c31-ef63bd908f61.png">

**Expected Behavior:**

Shodow only for the arrow.

**Comment by skydoves** [comment]
Hmm.. the shadow is from the appcompat's `View.setElevation()` method.
I think some kinds of devices do not support correct shadowing.
Please add `setArrowElevation(0)` for removing it.

**Comment by epool** [comment]
that worked like a charm, thank you @skydoves!
