### ISSUE TITLE
AppCompat version affects the app using this library

### ISSUE THREAD

**Issue by tals-investing** [skydoves/Balloon#157]
- Library Version: 1.3.1
- Affected Device(s): at the moment tested on Xiaomi Mi A2, Android version 10
 
**Describe the Bug:**

The app is using an old AppCompat version (1.0.2). When adding the gradle dependancy to the app, the new AppCompat version (1.2.0) of the library takes over the whole app. One visible effect is the theme handling in the app (displays only the device mathing theme).

**Expected Behavior:**

No impact on the app using this library.

**Comment by skydoves** [comment]
You can exclude the library's appcompat like the below.

```gradle 
   implementation(Libraries.balloon)  {
        exclude("androidx.appcompat", "appcompat")
    }
```

**Comment by tals-investing** [comment]
Perfect, thank you!
