### ISSUE TITLE
Custom layout child view width change on 1.3.1

### ISSUE THREAD

**Issue by Bikeskin** [skydoves/Balloon#158]
Hi, sky, thanks for this library, it has made my job easier many times :)
- Library Version [1.3.1]
- Affected Device(s) [Pixel 4 API 29 Emulator]
 
**Describe the Bug:**

Just change lib version 1.2.9 to 1.3.1 
<img width="198" alt="skydoves-1 2 9" src="https://user-images.githubusercontent.com/17744411/107681502-2c682a00-6cb0-11eb-9210-3c7bad679829.png">
<img width="198" alt="skydoves-1 3 1" src="https://user-images.githubusercontent.com/17744411/107681546-3853ec00-6cb0-11eb-9836-5cb20833d987.png">

Custom Layout:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="@dimen/toolbar_more_width"
    android:layout_height="wrap_content">

    <TextView
        android:id="@+id/tv_more_share"
        android:layout_width="match_parent"
        android:layout_height="@dimen/toolbar_more_menu_center_item_height"
        android:fontFamily="@font/brandon_bold"
        android:background="@drawable/selector_more_list_item_center"
        android:gravity="center_vertical"
        android:layout_gravity="center"
        android:textSize="@dimen/text_size_small"
        app:drawableLeftCompat="@drawable/icon_more_share"
        android:drawablePadding="@dimen/padding_common_twice"
        android:paddingStart="@dimen/margin_large"
        android:textColor="@color/faq_result_header"
        android:text="@string/toolbar_more_share" />

    <View
        android:layout_width="wrap_content"
        android:layout_height="@dimen/game_profile_separator_height"
        android:layout_marginStart="@dimen/toolbar_icon_padding"
        android:layout_marginEnd="@dimen/toolbar_icon_padding"
        android:background="@color/gray_background" />

    <TextView
        android:id="@+id/tv_more_feedback"
        android:layout_width="match_parent"
        android:layout_height="@dimen/toolbar_more_menu_center_item_height"
        android:fontFamily="@font/brandon_bold"
        android:background="@drawable/selector_more_list_item_center"
        android:gravity="center_vertical"
        android:layout_gravity="center"
        android:textSize="@dimen/text_size_small"
        app:drawableLeftCompat="@drawable/icon_more_feedback"
        android:drawablePadding="@dimen/padding_common_twice"
        android:paddingStart="@dimen/margin_large"
        android:textColor="@color/faq_result_header"
        android:text="@string/toolbar_more_feedback" />

</LinearLayout>

fun ...(context: Context, layout: Int): Balloon {
        return Balloon.Builder(context)
                .setArrowSize(1)
                .setLayout(layout)
                .setMarginRight(10)
                .setMarginTop(15)
                .setIsVisibleOverlay(true)
                .setOverlayColorResource(R.color.transparent_color_dark)
                .setOverlayShape(BalloonOverlayRect)
                .setFocusable(false)
                .setBackgroundColor(ContextCompat.getColor(context, R.color.white))
                .setBalloonAnimation(BalloonAnimation.FADE)
                .build()
    }

**Comment by skydoves** [comment]
Hi, @Bikeskin!
Could you share the root layout of your custom layout?

**Comment by Bikeskin** [comment]
Hi, sky

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="180dp"
    android:layout_height="wrap_content">
...
</LinearLayout>

**Comment by Bikeskin** [comment]
Hi sky,
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="179dp"
    android:layout_height="wrap_content"
....
...

**Comment by skydoves** [comment]
Is it the same result if you use the below method?
```kotlin
setWidth(179)
```

**Comment by Bikeskin** [comment]
Yes, it isn't working.
But the problem was solved when i upgrade the version to 1.3.2. And we have a new problem :D
![Screenshot_1614081601](https://user-images.githubusercontent.com/17744411/108841076-42e37f00-75e8-11eb-884e-8b8e89e240d7.png)

**Comment by skydoves** [comment]
Can you explain the details of the problem?
And you can set the corner radius using the below method without setting the radius drawable on your custom layout.

```kotlin
setCornerRadius(14f)
```

**Comment by skydoves** [comment]
Hi, @Bikeskin
Please reopen this issue if you face same again :)
