### ISSUE TITLE
Rectangular shadow on arrow

### ISSUE THREAD

**Issue by znakeeye** [skydoves/Balloon#159]
Running version `1.3.1` on a `Pixel 5` device with `Android 11`. I initialize my balloon with some simple settings:

```java
new Balloon.Builder(context)
    .setTextColorResource(R.color.tooltip_foreground)
    .setBackgroundColorResource(R.color.tooltip_background)
    .setIconColorResource(R.color.tooltip_foreground)
    .setPadding(24)
    .setTextSize(18f)
    .setAutoDismissDuration(8000)
    .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
    .setArrowOrientation(ArrowOrientation.BOTTOM)
    .setArrowSize(16)
    .setCornerRadius(4f)
    .setLifecycleOwner(lifecycleOwner)
    .setDismissWhenLifecycleOnPause(true);
```

And I see this artifact. Look at the arrow, it has some weird border/shadow? Looks rectangular...

![arrow-bug](https://user-images.githubusercontent.com/958469/108439377-72ddfb80-7251-11eb-922f-9b06191c6a32.png)

Is there a setting to get rid of this shadow?

**Comment by skydoves** [comment]
#156
