### ISSUE TITLE
getArrowConstraintPositionX may have a calculate mistake

### ISSUE THREAD

**Issue by amberkira** [skydoves/Balloon#161]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**
I don't know why there are 3 branches judgement here.
val position =
(anchor.width) * builder.arrowPosition + anchorX - balloonX - arrowHalfSize
when {
position <= getDoubleArrowSize() -> minPosition
position > getMeasureWidth() - getDoubleArrowSize() -> maxPosition
else -> position
}
if my anchorView width is quite small， the position is definitely less then double ArrowSize then x = minPosition. but actually the position is alivalble and I don't need to show my arrow in minPostion

**Expected Behavior:**

here is the screenshot
![F9F56DE93FF734593278230141BE5C19](https://user-images.githubusercontent.com/16331534/108709479-b4222400-754d-11eb-9bb3-f5891933382a.jpg)

and beblow is my code:
` currentBubble = createBalloon(context) {
            setArrowSize(15)
            setArrowAlignAnchorPaddingRatio(0f)
            if (showAlignTop) {
                setArrowOrientation(ArrowOrientation.BOTTOM)
            }else {
                setArrowOrientation(ArrowOrientation.TOP)
            }
            setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
            setArrowAlignAnchorPaddingRatio(0.5f)
            setArrowAlignAnchorPadding(7.dp)
            setLayout(contentView)
            setArrowDrawableResource(R.drawable.ic_popup_arrow)
            setBackgroundColor(Color.TRANSPARENT)
            setElevation(0)
            setAlpha(1f)
            setCornerRadius(0f)
            setBalloonAnimation(BalloonAnimation.FADE)
            setFocusable(false)
            setDismissWhenTouchOutside(true)
            setDismissWhenClicked(true)
            setOnBalloonDismissListener { cb.invoke() }
            setLifecycleOwner(context as LifecycleOwner)
        }`

A clear description of what you expected to happen.

**Comment by andrewfarm** [comment]
I'm encountering the same problem. Limiting the arrow position to between `minPosition` and `maxPosition` would make more sense to me.

As a workaround, I'm calculating the arrow position myself and positioning it by setting `arrowAlignAnchorPadding`. But this gets more complicated if you don't know the balloon's position onscreen beforehand.

**Comment by amberkira** [comment]
> I'm encountering the same problem. Limiting the arrow position to between `minPosition` and `maxPosition` would make more sense to me.
> 
> As a workaround, I'm calculating the arrow position myself and positioning it by setting `arrowAlignAnchorPadding`. But this gets more complicated if you don't know the balloon's position onscreen beforehand.

as my scene using balloon is quit simple , I just set A fixed value using `setArrowAlignAnchorPadding`
