### ISSUE TITLE
arrow visibility does not respect setIsVisibleArrow(false)

### ISSUE THREAD

**Issue by m-sabeeh** [skydoves/Balloon#162]
**Please complete the following information:**
- Library Version 1.3.2 and 1.3.3-SNAPSHOT
- Affected Device(s) Google Pixel 3
 
**Describe the Bug:**

According to documentation, `setIsVisibleArrow(bool)` sets the visibility of the arrow, while arrow is always visible irrespective of the flag.

Following are arrow related api call that I make during balloon building
```
setArrowSize(14)
setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
setIsVisibleArrow(false)
```
and then 

`anchorView.showAlignBottom(myBalloon)
`

It should respect the false flag in the builder and should not show arrow, as per my understanding.

**Expected Behavior:**

arrow should be hidden if we call `setIsVisibleArrow(false)`

**Comment by skydoves** [comment]
Released a new stable `1.3.3`!
Thanks for your issue :)
