### ISSUE TITLE
OnBackPressed and setFocusable

### ISSUE THREAD

**Issue by tamir-rachamim** [skydoves/Balloon#170]
Hello and thank you for this library - very well done.

I have a question regarding the usage.

- Library Version 1.3.3

My problem is that the balloon doesn't fulfil the following demand:
1. Dismiss when pressing the back button, and have the fragment/activity stay as is.
2. Stay on the screen when pressing outside the balloon.

The following achieves behavior 1:
`setFocusable(true)`

The following achieves behavior 2:
```
setDismissWhenOverlayClicked(false)
setDismissWhenTouchOutside(false)
```
**I want to achieve both behaviors simultaneously.**

The expected behavior is for the balloon to dismiss when pressing back, and stay on the screen while pressing outside the balloon while the screen controls are disabled.

How can I achieve this behavior? Am I missing something?

**Comment by skydoves** [comment]
Hi, in this case use the `setDismissWhenOverlayClicked(false)` and just `dismiss` the balloon on the `onbackpressed()`.

```kotlin
override fun onBackPressed() {
  if (balloon.isShowing) {
    balloon.dismiss()
  } else {
    super.onBackPressed()
  }
}
```
Thanks.

**Comment by tamir-rachamim** [comment]
Thank you @skydoves
