### ISSUE TITLE
Balloon does not adapt to the height of a custom View on certain devices

### ISSUE THREAD

**Issue by cooltey** [skydoves/Balloon#171]
**Please complete the following information:**
- Library Version 1.3.3
- Affected Device(s) Pixel 3 XL with Android 11 and Pixel 2 with Android 10
 
**Describe the Bug:**

Addressed here:
https://github.com/skydoves/Balloon/issues/148#issuecomment-805262834

The previous fix works fine on Samsung S9 with Android 10, but not on Pixel 3 XL and Pixel 2 and possibly some other devices.

**Expected Behavior:**

Content should not be cutoff.

**Comment by skydoves** [comment]
Hi, @cooltey again.
Can I see the full code of XML and `Balloon.Builder` related to this issue?

**Comment by skydoves** [comment]
`1.3.4-SNAPSHOT` is released!
Please try to use this snapshot.

**Comment by cooltey** [comment]
> 
> 
> Hi, @cooltey again.
> Hmm, I guess it caused by the `drawableStartCompat`. If there is a `TextView` which is a single line and has a drawable (If the drawable's height is bigger than the TextView's height), the measured height will be adopted by TextView's one.
> Can I see the full code of XML and `Balloon.Builder` related to this issue?

Yes.
XML: https://github.com/wikimedia/apps-android-wikipedia/blob/master/app/src/main/res/layout/view_watchlist_page_tooltip.xml
Code: https://github.com/wikimedia/apps-android-wikipedia/blob/master/app/src/main/java/org/wikipedia/util/FeedbackUtil.kt#L217-L234

I'll try the SNAPSHOT version to see if it fixes the issue, thank you.

**Comment by skydoves** [comment]
Is it possible to use the `VectorTextView` from this library instead of the `MaterialTextView`?
And we have to use the `app:drawableLeft` attribute for putting the drawable with the text.

```gradle
<com.skydoves.balloon.vectortext.VectorTextView
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:fontFamily="sans-serif-medium"
    android:text="@string/page_watchlist_overflow_menu_onboarding_tooltip_title"
    android:textAllCaps="true"
    android:textSize="14sp"
    android:textColor="@android:color/white"
    android:letterSpacing="0.04"
    android:layout_marginBottom="4dp"
    android:gravity="center_vertical"
    android:drawablePadding="8dp"
    app:drawableLeft="@drawable/ic_baseline_star_outline_24"
    app:drawableTint="@android:color/white"/>
```

**Comment by cooltey** [comment]
The SNAPSHOT version works great on Samsung S9 and Pixel 3XL, but I am still waiting for my colleague to report whether the version works fine on other devices as well. It that didn't work, I'll follow your suggestion to use the `VectorTextView` to see if it helps.

**Comment by skydoves** [comment]
Thanks for checking! 
But I highly recommend using the `VectorTextView` because it measures the size of the drawable.

**Comment by cooltey** [comment]
Hi @skydoves 
I've tried to use `VectorTextView` with the `padding='16dp'` on its parent view, turns out it will have a huge space on the bottom of the content. If I change to `paddingTop='16dp' paddingStart='16dp' paddingEnd='8dp'`, some other devices will have the cutoff issue.

Also, the other test from my colleague, the bottom of the content has a slightly cutoff:
https://github.com/wikimedia/apps-android-wikipedia/pull/2247#issuecomment-808288299

**Comment by skydoves** [comment]
Hi, @cooltey

I've created [a new branch](https://github.com/skydoves/Balloon/blob/fix/wrap-vector-text/app/src/main/res/layout/layout_custom_edit.xml#L11) for testing this issue, and I just checked about the `VectorTextView` using a lot of devices. Could you please check again on your device using this branch? 🙏

### VectorTextVIew
<img width="1389" alt="vector" src="https://user-images.githubusercontent.com/24237865/112828472-b33f5d80-90ca-11eb-979e-56f21226503a.png">

### MaterialTextView and AppCompatTextView
<img width="1380" alt="non-vector" src="https://user-images.githubusercontent.com/24237865/112828477-b5092100-90ca-11eb-9f8f-ea1e88793818.png">

**Comment by cooltey** [comment]
Hi @skydoves
Thanks for creating the test branch, I really appreciate it. 
Simply change to the `VectorTextView` with `AppCompatTextView` does not solve the issue in the app, however, I added `android:minHeight="24dp"` to each `VectorTextView` to make sure they reserve the height of the drawable, and turned out it worked. 

Also, I removed the `setWidthRatio(if (isLandscape(context)) 0.4f else 0.8f)` and replaced with `BalloonSizeSpec.WRAP` on width and height, and now the content looks great on multiple devices. 

Now it looks good to me and I'll let you know when getting the test results from my colleagues. 👍 

Thank you!

**Comment by skydoves** [comment]
Hi @cooltey
Wow.. that's awesome. I was thinking that measuring the single line textView and calculating it.
But simply can be resolved using `android:minHeight`. 😮

**Comment by cooltey** [comment]
Hi @skydoves 
I have confirmed that the issue has been tested and resolved on multiple devices. Thanks for your help and really appreciate it.

**Comment by skydoves** [comment]
Hi, @cooltey 
Thanks for your confirmation. 🙏
A new stable version [1.3.4](https://github.com/skydoves/Balloon/releases/tag/1.3.4) has been released!

**Comment by cooltey** [comment]
Thank you!
