### ISSUE TITLE
regarding on the Arrow, I've read many closed ticket on this issue, but still,

### ISSUE THREAD

**Issue by farsuller** [skydoves/Balloon#183]
and spent hours to find the fix on previous issues here, yet still occur, regarding on the arrow,
![170362886_768154487217279_29643746204737055_n](https://user-images.githubusercontent.com/64140869/114019419-f5258c00-98a0-11eb-9212-5d4eb1ecc542.jpg)
<img width="294" alt="Capture2" src="https://user-images.githubusercontent.com/64140869/114019440-fd7dc700-98a0-11eb-8342-32d44196f148.PNG">
<img width="437" alt="Capture" src="https://user-images.githubusercontent.com/64140869/114019450-01114e00-98a1-11eb-9ad5-e372ff19fde7.PNG">

```
 return Balloon.Builder(context!!)
            .setArrowSize(20)
            .setArrowOrientation(ArrowOrientation.TOP)
            .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
            .setArrowPosition(0.74f)
            .setArrowColorResource(R.color.white)
            .setHeight(120)
            .setWidthRatio(.5f)
            .setPadding(12)
            .setCornerRadius(6f)
            .setTextSize(13f)
            .setText(messageToDisplay)
            .setTextColor(ContextCompat.getColor(context, R.color.black))
            .setBackgroundColor(ContextCompat.getColor(context, R.color.white))
            .setOnBalloonClickListener(onBalloonClickListener)
            .setBalloonAnimation(BalloonAnimation.FADE)
            .setLifecycleOwner(lifecycleOwner)
            .build()
```
[https://github.com/farsuller/sampleToolTip](url)

**Comment by skydoves** [comment]
Hi, I can't understand the main issue.
But I can see the arrow is not visible on the screenshot..?
Please change your background color of the Activity and re-build your app.

**Comment by farsuller** [comment]
the shadow or outline of the Arrow are not visible,, I used it as showAlignBottom, so the arrow is on Top, I made it really white coz I have a project that tooltip is a must white, the arrow is visible when I use other colors. But the shadow or the elevate effect are not visible.

**Comment by skydoves** [comment]
I see. It's duplicated from #38, but there is no solution yet for this issue.
I recommend using a custom arrow that has a border instead.
