### ISSUE TITLE
How to add Translate animation to Balloon?

### ISSUE THREAD

**Issue by zaaach** [skydoves/Balloon#185]
I want to add a loop translate animation to make Balloon float up and down, But I dont know how=。=

**Comment by skydoves** [comment]
Hi, @zaaach can you explain the details about the translates?

**Comment by zaaach** [comment]
like this
[https://github.com/sephiroth74/android-target-tooltip/raw/master/screenshots/video2.gif](https://github.com/sephiroth74/android-target-tooltip/raw/master/screenshots/video2.gif)

**Comment by skydoves** [comment]
Try this:
```kotlin
.setBalloonHighlightAnimation(BalloonHighlightAnimation.HEARTBEAT)
```

**Comment by zaaach** [comment]
Great! just what I was looking for, thanks a lot!
