### ISSUE TITLE
Elevation not showing over tooltip

### ISSUE THREAD

**Issue by Miteshmakwana73** [skydoves/Balloon#187]
![device-2021-04-30-121524](https://user-images.githubusercontent.com/38969602/116658666-f3397f00-a9ad-11eb-8e3e-9b9b05152d24.png)

Elevation not showing over tooltip so tooltip is not visible properly because app background is also white

How do i set this

**Comment by skydoves** [comment]
#165.
The elevation can not be applied when the arrow orientation is top.
So I recommend using a custom arrow resource or changing the color of the background or an arrow.
Thanks!
