### ISSUE TITLE
Lint shows error for dimen resource id

### ISSUE THREAD

**Issue by dsuresh-ap** [skydoves/Balloon#190]
**Please complete the following information:**
- Library Version 1.3.4
- Affected Device(s) Samsung Galaxy S9 Android 10
 
**Describe the Bug:**

Lint complains that instead of passing the resource id directly we should be calling `resources.getDimension()`.

`setMaxWidthResource(R.dimen.tutorial_tooltip_width)`
![image](https://user-images.githubusercontent.com/21132682/119399508-fb33c880-bca6-11eb-858e-0ec6253a6fc3.png)

**Expected Behavior:**

No lint error shows.

**Comment by skydoves** [comment]
Hi, thanks for reporting this issue :)
This issue is fixed in the snapshot `1.3.5-SNAPSHOT` and will be included in the next stable release.
Thanks !

**Comment by dsuresh-ap** [comment]
@skydoves Thanks!

**Comment by skydoves** [comment]
Released a new stable `1.3.5`!

**Comment by dsuresh-ap** [comment]
@skydoves Thanks it worked!
