### ISSUE TITLE
Dismiss when touching outside - without consuming the touch event?

### ISSUE THREAD

**Issue by znakeeye** [skydoves/Balloon#193]
Using `v1.3.4`. When showing a tooltip, it gets dismissed automatically when touching outside of it. However, there seems to be no way to **not** consume this touch event.

In my use case, I show a tooltip like *"Swipe down to refresh"*. So, as a user I try to swipe but nothing happens - the touch event closes the tooltip and then nothing. Obviously, the touch event got consumed so I need to swipe a second time. This is a bit confusing.

**Opt-in to not consume touch event**
Perhaps this could be improved. In some scenarios, it is desirable to allow the touch event to continue routing. Something like:

`.setConsumeTouchOutside(false)`

**Comment by skydoves** [comment]
Hi, you can implement it using the below codes.
```kotlin
.setDismissWhenTouchOutside(false)
```

**Comment by znakeeye** [comment]
> Hi, you can implement it using the below codes.
> 
> ```kotlin
> .setDismissWhenTouchOutside(false)
> ```

Nice. So I would explicitly dismiss it myself? On touch?

**Comment by skydoves** [comment]
Yes, you should invoke the `dismiss()` method explicitly if you want to close the popup.
Or you can set the `setOnBalloonClickListener` and close the Balloon when users touch the inside of the body.

**Comment by znakeeye** [comment]
Thanks. The suggested method works. Though, it would be even better if this could be built into the library :)
