### ISSUE TITLE
Unable to use arrow orientation at the bottom

### ISSUE THREAD

**Issue by Jilocasin** [skydoves/Balloon#194]
**Please complete the following information:**
- Library Version: 1.3.4
- Affected Device(s): OnePlus 5 (all devices though I guess)
 
**Describe the Bug:**

When using `ArrowOrientation.TOP` a centered balloon (presented in the center of an anchor view via `.show`) will have its arrow pointing upwards but will be located at an incorrect position relative to the anchor view. The position is calculated as if the arrow is pointing down not up.

```
Balloon balloon = new Balloon.Builder(context)
                .setArrowSize(20)
                .setArrowOrientationRules(ArrowOrientationRules.ALIGN_FIXED)
                .setArrowOrientation(ArrowOrientation.TOP)
                .setArrowColorResource(R.color.black)
                .setCornerRadius(0)
                .setText("Hello!")
                .setBalloonAnimation(BalloonAnimation.FADE)
                .setLifecycleOwner(this)
                .setSize(100, 100)
                .setElevation(5)
                .build();

balloon.show(buttonView);
```

**Result:**

![Screenshot 2021-06-21 230129](https://user-images.githubusercontent.com/4448294/122827534-c1290700-d2e4-11eb-9c21-e2fe7bc6e8d3.png)

**Expected Behavior:**

The balloon position should follow the arrow orientation, shifting the balloon downwards.

**Comment by skydoves** [comment]
Hi, could you explain more details about this issue?
From the screenshot If you want to show up a balloon over the view, use the below method instead.

```java
balloon.showAlignTop(buttonView);
```

**Comment by Jilocasin** [comment]
Sorry for wording. My intention is to show the balloon 'over' the view in terms of z-index, not vertically. Both views should overlap each other, the arrow tip pointing to the anchor center.

When using `showAlign____` the whole balloon will be shifted down *below* or *above* the anchor view, resulting in the arrow pointing directly at the edge.

![grafik](https://user-images.githubusercontent.com/4448294/122963211-5b8d5700-d386-11eb-9cb1-19e7e2994a48.png)

This is still **not** what I am looking for.
The desired behaviour is the arrow still pointing at the center of the anchor view, but the balloon itself expanding downwards.

What I am looking for is the following:

![grafik](https://user-images.githubusercontent.com/4448294/122963527-a4451000-d386-11eb-9e4d-d40ba886415f.png)

This is a mockup made in GIMP. I wasn't able to achieve this using any combination of config settings.

**Comment by skydoves** [comment]
Gotcha!
I usually implement it this way. (Using the y-off)

```kotlin
circleImageView.setOnClickListener {
  customProfileBalloon.showAlignBottom(it, 0, -(circleImageView.height / 2))
}
```

But I will find is there a better way.

**Comment by Jilocasin** [comment]
Thank you. This seems to work fine!

Funnily I have tried a similiar approach earlier using `balloon.show(anchorView, 0, anchorView.getHeight() / 2)` thinking I could simply offset the _center_ position by half the height _downwards_. Your solution is basically the same, but instead shifting it upwards from the bottom edge. 😀

Sadly my approach resulted in a weird behaviour. I suppose there's some bug in the position calculation when giving an offset to `balloon.show()`

The result was the following:

![grafik](https://user-images.githubusercontent.com/4448294/123133144-bb036980-d44f-11eb-8cbd-6b19d7ca0a9a.png)

This should be easily reproduced, even when given a zero offset to the call, like `balloon.show(anchorView, 0, 0)`
I would have assumed this should not change the position at all (being an _offset_). But it does.

Can you reproduce this?

**Comment by skydoves** [comment]
I think the solution that I've suggested should be used with the `showAlignBottom` or `showAlignTop`.
But I'm considering implementing a new method like a showAlignCenter with some constraints. 💭

**Comment by Jilocasin** [comment]
I still consider it a bug that show() with an offset of 0 does screw up the position calculation.

**Comment by skydoves** [comment]
I will consider adding a new function `showAtLocation` in the next release.
Thanks!

**Comment by skydoves** [comment]
Hi @Jilocasin, Sorry for the very late reply.
Here is the new function `showAtCenter` on the new release `1.3.8-SNAPSHOT`. This feature will be included in the next stable release.

```kotlin
balloon.showAtCenter(anchor, xOff = 0, yOff = 0, centerAlign = BalloonCenterAlign.BOTTOM)
```

### Specifications:

Shows the balloon over the anchor view (overlap) as the center aligns.
Even if you use with the [ArrowOrientationRules.ALIGN_ANCHOR], the alignment will not be guaranteed.
So if you use the function, use with [ArrowOrientationRules.ALIGN_FIXED] and fixed [ArrowOrientation].
@param anchor A target view which popup will be shown with overlap.
@param xOff A horizontal offset from the anchor in pixels.
@param yOff A vertical offset from the anchor in pixels.
@param centerAlign A rule for deciding the alignment of the balloon.

Thanks!

**Comment by skydoves** [comment]
A new stable `1.3.8` has been released!
