### ISSUE TITLE
Elevation can't be set when arrow is anywhere but the bottom

### ISSUE THREAD

**Issue by simonsickle** [skydoves/Balloon#196]
**Please complete the following information:**
- Library Version [e.g. v1.0.0] 1.3.4
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0] Simulator, Android 11 - likely others
 
**Describe the Bug:**

When I set the elevation of the tooltip, I see that the shadow is only working when I set the arrow direction to the bottom of the tooltip

**Expected Behavior:**

Elevation should be settable when the arrow is pointing to any direction.

**Notes:**
I think this behavior is because of this logic https://github.com/skydoves/Balloon/blob/c2d769e0ba7271909c92b070a43ec8c6e50b0658/balloon/src/main/java/com/skydoves/balloon/Balloon.kt#L235

**Comment by skydoves** [comment]
Hi @simonsickle ,
Thanks for your issue. Because If the arrow is over the balloon (orientation is top) then the elevation will be also positioned over the body of the balloon. So It was deliberated action. If you have a better idea to express naturally please share it on this thread! 👐

**Comment by skydoves** [comment]
I applied to the demo project. (elevation=21dp, arrowElevation=21dp)
The arrow elevation will over the body. I think if there are any ways to change the orientation of the elevation, this issue could be solved easily. 🤔 

<img src="https://user-images.githubusercontent.com/24237865/123798488-2e125180-d922-11eb-9964-6f6d7d42e79a.jpg" width="60%">

**Comment by simonsickle** [comment]
Thanks for trying that out! I will share a bit more of what we are trying to accomplish so that maybe that could give you some ideas as I think through it myself.

![Screen Shot 2021-06-29 at 8 55 02 AM](https://user-images.githubusercontent.com/51972200/123800923-c6272100-d8b7-11eb-9855-601fc1b9163b.png)

but this is what we get

![Screen Shot 2021-06-29 at 8 56 15 AM](https://user-images.githubusercontent.com/51972200/123801064-e656e000-d8b7-11eb-87e3-a7068c0e5d0c.png)

So the thing we are trying to figure out is how to get some drop shadow around the arrow to separate it from the background and keep it from looking strange
