### ISSUE TITLE
Arrow color not working

### ISSUE THREAD

**Issue by Harrybisht3** [skydoves/Balloon#198]
.setArrowColorResource(R.color.anycolor)
not working. the color of arrow remains black always.

**Comment by skydoves** [comment]
Hi, could you let me know about the library version and full code of the builder?

**Comment by Harrybisht3** [comment]
hi @skydoves 
this my full code:
fun getBalloon(context: Context, lifecycleOwner: LifecycleOwner, message: String): Balloon {
        return Balloon.Builder(context)
            .setText(message)
            .setArrowColorResource(R.color.black_40)
            .setArrowSize(6)
            .setWidthRatio(1.0f)
            .setHeight(BalloonSizeSpec.WRAP)
            .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
            .setArrowPosition(0.5f)
            .setPadding(12)
            .setMarginRight(12)
            .setMarginLeft(12)
            .setTextSize(15f)
            .setTextGravity(Gravity.START)
            .setCornerRadius(3f)
            .setTextColor(Color.WHITE)
            .setBackgroundColorResource(R.color.black_40)
            .setOnBalloonDismissListener {
                // Toast.makeText(context.applicationContext, "dismissed", Toast.LENGTH_SHORT).show()
            }
            .setBalloonAnimation(BalloonAnimation.ELASTIC)
            .setLifecycleOwner(lifecycleOwner)
            .build()
    }

**Comment by skydoves** [comment]
Hmm, If I test using the [demo project](https://github.com/skydoves/Balloon/tree/main/app) works fine for me. 🤔

**Comment by Harrybisht3** [comment]
.setalpha() is changing the opacity  of text as well. and .setArrowColorResource(R.color.anycolor) is not working for me on android 10.

**Comment by skydoves** [comment]
I think this issue is related to the alpha as you mentioned. 
Is that mean do you need to apply the different alpha values of the body and the arrow?

**Comment by Harrybisht3** [comment]
I need to apply alpha for body and arrow as same but not for the text in body.

**Comment by skydoves** [comment]
Sorry for the late reply.
Text is one of the body's contents. So it is not possible to separate the alpha value between body and text.
