### ISSUE TITLE
overley not visible for the first time the tooltip appears

### ISSUE THREAD

**Issue by ruthi-g** [skydoves/Balloon#199]
- Library Version [1.3.4]

when i open the fragment in the first time the overley dont visible only in second time, or in the In the second appearance of the tooltip.

 here is my code:

       val balloon: Balloon = Balloon.Builder(this.requireContext())
                .setIsVisibleOverlay(true) // sets the visibility of the overlay for highlighting an anchor.
                .setOverlayColorResource(R.color.colordisable) // background color of the overlay using a color resource.
                .setOverlayPadding(6f) // sets a padding value of the overlay shape internally.
               .setBalloonOverlayAnimation(BalloonOverlayAnimation.FADE)
                .setOverlayShape(BalloonOverlayRect)
                .setDismissWhenOverlayClicked(false)
                .setTextResource(R.string.new_Memorial_page)
                .setArrowSize(10)
                .setWidthRatio(1.0f)
                .setArrowOrientation(ArrowOrientation.BOTTOM)
                .setArrowOrientationRules(ArrowOrientationRules.ALIGN_FIXED)
                .setWidth(100)
                .setHeight(BalloonSizeSpec.WRAP)
                .setArrowPositionRules(ArrowPositionRules.ALIGN_BALLOON)
                .setArrowPosition(0.8f)
                .setPadding(12)
                .setMarginRight(12)
                .setMarginLeft(12).setMarginBottom(12)
                .setTextSize(15f)
                .setCornerRadius(0f)
                .setTextColorResource(com.skydoves.balloon.R.color.material_grey_900)
                .setIconDrawableResource(com.skydoves.balloon.R.drawable.abc_ic_clear_material)
                .setIconSize(17)
                .setBackgroundColorResource(android.R.color.white)
                .setBalloonAnimation(BalloonAnimation.FADE)
                .setDismissWhenTouchOutside(false)
                .build()

      placeDetails_buttonServices.showAlignTop(balloon2)

**Comment by ruthi-g** [comment]
hi , someone have a solution for me?

**Comment by skydoves** [comment]
Sorry for the late reply. 
Would you please execute the `showAlignTop(balloon2)` inside of the `post` method?

```kotlin
placeDetails_buttonServices.post {
  placeDetails_buttonServices.showAlignTop(balloon2)
}
```
