### ISSUE TITLE
Prevent tooltip dismiss on clicking Android hardware back button

### ISSUE THREAD

**Issue by praveenraikar** [skydoves/Balloon#202]
Thank you for the library.

We have one use case where we need to show a set of tooltips one by one without breaking. Currently if we tap on back button the flow is breaking.

Can we have some way to know whether the tooltip is being visible or some flag to block the back button as we have for dialog fragment (isCancelable)  
Or Do we need to override the onbackpressed?

**Comment by skydoves** [comment]
Hi, you can implement it using the `setOnBalloonDismissListener`.
Set the `setOnBalloonDismissListener` and call `dismiss()` manually.

Can we have some way to know whether the tooltip is being visible or some flag to block the back button as we have for dialog fragment (isCancelable)

=> You can check using the `isShowing()` method.

**Comment by praveenraikar** [comment]
Thank you for the inputs.
We used `isShowing()` method and it worked.
