### ISSUE TITLE
RecyclerView scroll required when the ViewHolder contains a TextView that can't be displayed on a single line

### ISSUE THREAD

**Issue by 4rthurRousseau** [skydoves/Balloon#208]
- Library Version : 1.3.5
- Affected Device(s) : OnePlus 7T Pro, Android 10 - Emulator, Android 6, 8, 9 (not tested on any other Android version)
 
**Describe the Bug:**
While running the demo application, I changed the first item returned by the `getCustomSamples` method from `Timeline` to `Timelineeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee`.

The menu looks like this :
![image](https://user-images.githubusercontent.com/7251970/126160631-0a3a7b4f-1714-4c95-bd95-d732fe77c886.png)

**Expected Behavior:**
It may not be a bug, but I was expecting the balloon to be taller so it can fit the whole list inside it, without having to scroll.

**Comment by 4rthurRousseau** [comment]
Hi everyone,

It looks like I'm only facing this behavior the first time I display the Balloon :
![image](https://user-images.githubusercontent.com/7251970/126295603-49d52898-a0cd-4553-84d0-50f12f49a505.png)

Any subsequent display shows the Balloon with the right height :
![image](https://user-images.githubusercontent.com/7251970/126295709-8416a6e1-ca14-483e-a5c9-211b46e06e4c.png)

The first time displaying the Balloon, the measured height evaluates to 206. Every further call to the `show` method with the same Balloon evaluates to 235.

```
this.binding.root.measure(View.MeasureSpec.UNSPECIFIED, View.MeasureSpec.UNSPECIFIED)
this.bodyWindow.width = getMeasuredWidth()
this.bodyWindow.height = getMeasuredHeight()
this.binding.balloonText.layoutParams = FrameLayout.LayoutParams(
    FrameLayout.LayoutParams.MATCH_PARENT,
    FrameLayout.LayoutParams.MATCH_PARENT
)
```

**Comment by skydoves** [comment]
Hey, @4rthurRousseau 
Unfortunately, we don't have any solutions for measuring the exact RecyclerView's height size until now. Also, the inconsistency of the height size of a list depending on its content is not a great UX design, so we might consider this issue again if we get any great solution. Anyway thanks for reporting this issue!
