### ISSUE TITLE
Handler not reset when i call dismiss method

### ISSUE THREAD

**Issue by spvince** [skydoves/Balloon#210]
**Please complete the following information:**
- Library Version v1.3.5
- Affected Device(s) pixel 2 xl android 11
 
**Describe the Bug:**

I have a custom tooltip. There is a progress bar indicating how many time the tooltip will show and there is a cross bar which close instantaneously the tooltip ( I call method dismiss of Balloon class). In Balloon builder i call method setAutoDismissDuration ( duration 5s). 

My problem is when i click on the cross bar tooltip is dismissed but the handler isn't reset. So when  the tooltip is show again it's displayed 2s instead of 5s

**Expected Behavior:**

I want the handler is reset when i call dimiss method.

**Comment by skydoves** [comment]
Hi @spvince, Thanks for your issue!
A new version `1.3.6-SNAPSHOT-210` has been released and this issue will be resolved in the next stable release.
Thanks!

**Comment by spvince** [comment]
Thanks @skydoves

**Comment by skydoves** [comment]
`1.3.6` stable has been released!
Thanks for your issue.

**Comment by spvince** [comment]
Works fine
