### ISSUE TITLE
Builder.setOverlayPaddingResource() results in a wrong overlay padding

### ISSUE THREAD

**Issue by vitkhudenko** [skydoves/Balloon#212]
**Environment:**
- Library Version: 1.3.6-SNAPSHOT
- My Device: Google Nexus 5X (Android 8.1)
 
**Describe the Bug:**

Assuming there is a dimen declaration:
`<dimen name="overlay_padding">2dp</dimen>`

Using the `Builder.setOverlayPaddingResource(R.dimen.overlay_padding)` results in a much bigger (in times) overlay padding. How much bigger most likely depends on the device's screen pixel density.

**Expected Behavior:**

Actual requested size is applied.

**Comment by vitkhudenko** [comment]
@skydoves, can I access the fixed version via any of the snapshot releases?

**Comment by skydoves** [comment]
Hi @vitkhudenko,
you can access the `1.3.6-212-SNAPSHOT` version. Thanks!

**Comment by skydoves** [comment]
`1.3.6` stable has been released!
Thanks for your issue.
