### ISSUE TITLE
Anchor view highlight

### ISSUE THREAD

**Issue by vitkhudenko** [skydoves/Balloon#213]
**Is your feature request related to a problem?**

It seems there is no possibility to "highlight" the anchor view (e.g. by surrounding the anchor view with a custom border).

**Describe the solution you'd like:**

Overlay padding is just a transparent space. Could it be colored with a custom color? E.g.:

![image](https://user-images.githubusercontent.com/198951/127064528-4c6d7ec3-bc95-4eb2-a983-60bf4855dd83.png)

P.S. Great library. 👍

**Comment by skydoves** [comment]
This feature will be included in the next stable, and you can use it early in the `1.3.7-SNAPHSOT`.

**Comment by skydoves** [comment]
A new stable `1.3.7` is released.
Thanks for your contribution @vitkhudenko !
