### ISSUE TITLE
Text Gravity is not working properly

### ISSUE THREAD

**Issue by deprecated-fun** [skydoves/Balloon#218]
I'm not sure if it's bug or not but it seems like you can't set text gravity and "textview" gravity separately.

- Library Version [1.3.5]
 
The Bug?:
  val balloon: Balloon? = context?.let {
            Balloon.Builder(it)
                //text
                .setTextSizeResource(R.dimen.fontl)
                .setText(getString(R.string.text))
                .setTextColor(ContextCompat.getColor(requireContext(), R.color.black))
                .setTextGravity(Gravity.LEFT)
                .setTextGravity(Gravity.CENTER_VERTICAL)
                .setPaddingVertical(paddingY)
                .setPaddingLeft(paddingL)
                //body
                .setWidth(width)
                .setHeight(BalloonSizeSpec.WRAP)
                .setCornerRadius(radius)
                .setBackgroundColor(ContextCompat.getColor(requireContext(), R.color.white))
                .build()

.setPaddingLeft() has padding on right side of balloon too. Same for setPaddingHorizontally. Is it happening because width of my balloon is set so there is some space left on right side. 

.setTextGravity(Gravity.CENTER_HORIZONTAL) aligns text to the center what I don't want.

I think it would be helpful if it was possible to set text gravity and "textview" gravity separately.

**Comment by skydoves** [comment]
Hi, do you mean you want to set a static width size for the balloon and change the gravity of `TextView`?
I think it should be implemented using a custom layout. Because measuring the width size of the `TextView` in the normal balloon will be decided by the width size of the body.

**Comment by skydoves** [comment]
For double-check, the textView has the `android:layout_width="match_parent"` attribute internally, so I recommend creating a custom view instead. Thanks!
