### ISSUE TITLE
Show balloon centered over anchor

### ISSUE THREAD

**Issue by holgerschlegel** [skydoves/Balloon#222]
I'm using version 1.3.6 of your great library.

Maybe this is somehow related to issue #194. Not sure about that.

I would like to show the balloon centered over the anchor view. So the center of the balloon (not the arrow tip) is at the same absolute location as the center of the anchor view. Of course, adjusted to always fully show the balloon on the screen.
Here 'over' is meant in terms of z-order and not as in top or bottom.

I tried to archive this using `show(anchor, xoff, yoff)` and calculations based on `measuredHeight` and `measuredWidth`. But is looks like the measured height/width is returned as zero before the balloon is shown.
And due to the dynamic content of the balloon I could not hard code the offsets to reach by goal.

Is this possible with the current version?

**Comment by skydoves** [comment]
Sorry for the very late reply.
Here is the new function `showAtCenter` on the new release `1.3.8-SNAPSHOT`. This feature will be included in the next stable release.

```kotlin
balloon.showAtCenter(anchor, xOff = 0, yOff = 0, centerAlign = BalloonCenterAlign.BOTTOM)
```

### Specifications:

Shows the balloon over the anchor view (overlap) as the center aligns.
Even if you use with the [ArrowOrientationRules.ALIGN_ANCHOR], the alignment will not be guaranteed.
So if you use the function, use with [ArrowOrientationRules.ALIGN_FIXED] and fixed [ArrowOrientation].
@param anchor A target view which popup will be shown with overlap.
@param xOff A horizontal offset from the anchor in pixels.
@param yOff A vertical offset from the anchor in pixels.
@param centerAlign A rule for deciding the alignment of the balloon.

Thanks!

**Comment by skydoves** [comment]
A new stable `1.3.8` has been released!
