### ISSUE TITLE
Is there an ability to click on the Anchor view when there is visible overLay around the Ballon popup?

### ISSUE THREAD

**Issue by preethambogadi** [skydoves/Balloon#225]
.setFocusable(false) Will let us touch all the views around Balloon PopUp view even when the Balloon Popup is present.

But when overLay is present .setFocusable(false) is of no use. Is there anyother way to achieve this?

Example: With single tap on the notification icon. I wanted to dismiss the BallonPopUp and also allow click event on the Notification icon
<img width="133" alt="Screen Shot 2021-08-02 at 11 58 33 PM" src="https://user-images.githubusercontent.com/20709206/127955560-92afc9e9-f185-4a85-93ce-5081baf5dc21.png">

**Comment by JoePaul** [comment]
I had the same problem in my project, I solved it like the code snippet below and then manually dismiss the Balloon in the notification icons click listener. I don't know if it is the best way to do it but it passes the event down to the anchor being highlighted 😄 

![image](https://user-images.githubusercontent.com/36191409/127968464-34edfd17-bcaf-4b5f-b022-b7129ee8ce76.png)

**Comment by preethambogadi** [comment]
Thanks @JoePaul

**Comment by abhimuktheeswarar** [comment]
Will there be proper support for this, or should we continue to use the above-mentioned workaround?

**Comment by JoePaul** [comment]
I don't think it should be so hard to implement. I can take a look and se if I could make a PR for it :)
