### ISSUE TITLE
Overlay is not redrawn on Balloon.update(anchor) call

### ISSUE THREAD

**Issue by vitkhudenko** [skydoves/Balloon#228]
**Please complete the following information:**
- Library Version: v1.3.6
- Affected Device(s): any device
 
**Describe the Bug:**
Whenever anchor view changes its position on the screen I call `balloon.update(anchor)`.
However if overlay is shown, there is a bug - the overlay view is not updated at all, highlighting the outdated anchor "hole".

**Expected Behavior:**
Implementation of the `balloon.update(anchor)` should also take under account a case when overlay is shown. And if shown - redraw the overlay to follow a new position of the anchor view.

**Comment by vitkhudenko** [comment]
I'm creating a fix for this. Please wait for a PR.

**Comment by vitkhudenko** [comment]
@skydoves , I guess the fix can be accessed within one of the 1.3.7-SNAPSHOT-XXX. Could you please point me to what XXX is?

**Comment by skydoves** [comment]
`1.3.7-228-SNAPSHOT` has been released.
Thanks, @vitkhudenko !
