### ISSUE TITLE
Overlay follow anchor view's shape

### ISSUE THREAD

**Issue by WenLonG12345** [skydoves/Balloon#232]
Hi, I come over here from `PowerMenu` since there is no overlay function in `PowerMenu`. 
`Balloon` is very awesome and thanks for this library! :)

However, I still have some problem, regarding to the overlay. 

![image](https://user-images.githubusercontent.com/39330565/129450260-86057883-fb0c-4ef8-9036-ff49cba9e588.png)

Is it possible that the overlay follow the anchor's view shape? since I have a custom background on the layout.

**Comment by skydoves** [comment]
Hi, @WenLonG12345,
Unfortunately, there is no way to implement the specific shape for highlighting now. (Applying different radius for each corner)

**Comment by WenLonG12345** [comment]
Will it be a feature request? or maybe I can try to do a PR for this. :)
