### ISSUE TITLE
Height overflows while using setHeight(BalloonSizeSpec.WRAP)

### ISSUE THREAD

**Issue by rulfox** [skydoves/Balloon#233]
The height of the balloon covers the entire screen even when the custom view height is approximately 300 dp.
How to use dynamic height?

Next to do: I need to include a recyclerview inside the balloon - Not done yet
Will recyclerview affect the height of popup ?
I have not yet added recyclerview.

**Comment by skydoves** [comment]
You should check the height size of the custom layout.
The `BalloonSizeSpec.WRAP` will follows the height of the internal custom layout.
Also, you can update the size of the `Balloon` using the below method.
```kotlin
fun update(anchor: View, xOff: Int = 0, yOff: Int = 0)
```
