### ISSUE TITLE
Spacing is not proper 

### ISSUE THREAD

**Issue by KishanVajani** [skydoves/Balloon#234]
**Please complete the following information:**
- Library Version 1.3.6
- Affected Device(s) Samsung Galaxy M30 with Android 10.0
 
I am using two text view in vertical manner for creating tooltip balloon but if the content of the 1st text view is grater then the below text view it is going to new line instead of giving more width for balloon.

I want both text view in single line by making more width of balloon 
![image](https://user-images.githubusercontent.com/84322875/131835826-b241ea35-9244-436a-ae0d-0ded54cfc455.png)

**Comment by skydoves** [comment]
Hi, could you share your `Balloon.Builder` codes?
