### ISSUE TITLE
Your balloon triggers the bottom navigation bar

### ISSUE THREAD

**Issue by iAmJuan550** [skydoves/Balloon#237]
When I execute the following code:

```
new Balloon.Builder(this)
                                        .setArrowSize(10)
                                        .setArrowOrientation(ArrowOrientation.TOP)
                                        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
                                        .setArrowPosition(0.5f)
                                        .setWidth(BalloonSizeSpec.WRAP)
                                        .setHeight(65)
                                        .setTextSize(15f)
                                        .setCornerRadius(4f)
                                        .setAlpha(0.9f)
                                        .setText("tap anywhere on the green surface to place an anchor")
                                        .setTextColor(ContextCompat.getColor(this,
                                                android.R.color.white))
                                        .setIconDrawable(ContextCompat.getDrawable(this,
                                                android.R.drawable.checkbox_on_background))
                                        .setBackgroundColor(ContextCompat.getColor(this,
                                                R.color.colorPrimary))
                                        .setBalloonAnimation(BalloonAnimation.FADE)
                                        .setAutoDismissDuration(2000)
                                        .setOnBalloonDismissListener(() ->
                                                promptIsShowing = false)
                                        .setLifecycleOwner(this)
                                        .build()
                                        .showAlignBottom(arSceneView);
```

The bottom navigation bar is triggered and it stays active for as long as the balloon popup is there and it goes away when the balloon popup is dismissed. Is there a way to disable that?

**Comment by skydoves** [comment]
Hi, do you have any simulated videos like a GIF image?

**Comment by sarimmehdi** [comment]
No. I am using your library with arcore though. Other dialog libraries also do the same for my arcore app, I have some obj files for 3D models

**Comment by iAmJuan550** [comment]
@sarimmehdi is my personal github, this is my work github (just in case that reply confused you)

**Comment by skydoves** [comment]
Do you show up the balloon over the arcoreview?
That would make a lot of unexpected issues.
Because showing a `Window` on the `arcoreview` is not a recommended way.

**Comment by iAmJuan550** [comment]
Hmm, any workaround for this then?

**Comment by skydoves** [comment]
Well, I just used a fake View for showing the balloon safely.
You can reference theses:
[activity_scene.xml](https://github.com/skydoves/Pokedex-AR/blob/b302785750e8d1194fe24a54ba019b1d947bcd0b/app/src/main/res/layout/activity_scene.xml): As you can see there is a fake `android:id="@+id/bindingView"` view and Balloon is shown over the view.
[bindShowBalloon](bindShowingBalloon)

**Comment by iAmJuan550** [comment]
Doesn't seem to work for me. I am using Sceneform with its SceneView (I created a fake view that displays on top of ArSceneView). I guess that could be the cause of this. If

**Comment by skydoves** [comment]
Could you check the DialogFragment also occur the same issue? 
I think this issue is not related to this library, I guess there is some issue between the internal SDK (PopupWindows) and ArSceneView.

**Comment by skydoves** [comment]
@iAmJuan550
Please reopen this issue if the same problem happens again.
