### ISSUE TITLE
Show balloon popupWindow below keyboard

### ISSUE THREAD

**Issue by KKitar** [skydoves/Balloon#238]
**Is your feature request related to a problem?**

We want to have the possibility to show the balloon tooltip below the keyboard.
Our balloon popup has setDismissWhenTouchOutside(false) and has custom layout with "X" to close it.
Our problem is that when the tooltip is shown and the first Editext gets focused, a part of it is displayed over the Keyboard on the screen, preventing the user to continue typing.

**Describe the solution you'd like:**

Provide access to "bodyWindow" or a function to define the InputMethodMode

**Describe alternatives you've considered:**

For now i'm doing it this way. Please let me know if there's a better way or if I missed something from docu.

`                            val bodyWindowField: Field = balloon.javaClass.getDeclaredField("bodyWindow")
                            bodyWindowField.isAccessible = true
                            val bodyWindow: PopupWindow = bodyWindowField.get(balloon) as PopupWindow
                            bodyWindow.inputMethodMode = PopupWindow.INPUT_METHOD_NEEDED
`

**Comment by skydoves** [comment]
Hi @KKitar, 

I think the public visibility getter functions should be provided for `bodyWindow` or `bodyWindow.inputMethodMode`.
I will provide the functions in the next release.
Thank you for your issue!

**Comment by skydoves** [comment]
Hi @KKitar,
A new stable `1.3.7` is released!
You can access the `balloon.bodyWindow` directly without using the reflection.
Thanks!
