### ISSUE TITLE
Material NavigationView stops working when balloon showed

### ISSUE THREAD

**Issue by sasagrujic** [skydoves/Balloon#24]
**Please complete the following information:**
- Library Version 1.1.2
- Affected Devices : Alcatel 5033D v8.1.0, Huawei P20 Pro v9.0.0, Samsung A20
 
Describe Bug: When the balloon is showed for the first time, menu items in Navigation view stops working in meaning, instead of opening desired activities they only close NavigationView. Problem then continues no matter if balloon is showed or not, I have to restart the app to work again.

Expected Behavior: I expect NavigationView to work as before showing balloon.

My code for creating balloon is:
```
val statusPopup = createBalloon(this) {
            setLayout(R.layout.popup_change_annoyed_status)
            setWidth(311)
            setArrowSize(10)
            setArrowOrientation(ArrowOrientation.TOP)
            setArrowPosition(0.85f)
            setCornerRadius(5f)
            setTextTypeface(R.font.montserrat_medium)
            setBackgroundColorResource(R.color.colorSecondary)
            setBalloonAnimation(BalloonAnimation.OVERSHOOT)
            setLifecycleOwner(lifecycleOwner)
        }

```

In image clicke event: 
```
if (!statusPopup.isShowing) {
                prepareBalloon(user, statusGoLayout, statusMaybeLayout, statusNoLayout)
                it.showAlignBottom(statusPopup)
            } else {
                dismissBalloon(statusPopup)
            }
```
dismissBalloon(balloon) function only calls balloon.dismiss()

**Comment by sasagrujic** [comment]
Hi! Still encountering the same problem. Could you take a look if you called some system function, since the behavior is really weird. Thanks.

**Comment by skydoves** [comment]
Hi, @sasagrujic!
I tested using a new project from Android Studio template (Navigation Drawer Activity) with Balloon,
But it seems to work fine for me.
Could you make a new example repository using the template with Balloon?
