### ISSUE TITLE
Clear SharedPreferences (preferenceName, showTimes)

### ISSUE THREAD

**Issue by utkualtas** [skydoves/Balloon#241]
**Is your feature request related to a problem?**
We have a logout feature in our app. The problem is that when the user logged out we need to clear the showTime but as far as I could see there is not a function for that. Am I wrong?

**Describe the solution you'd like:**
Actually, I can clear the preferences like this way;
`context.getSharedPreferences("com.skydoves.balloon", Context.MODE_PRIVATE).edit { clear() }`

But I prefer to do that `Balloon.clearAllPreferences()` as like with [Only](https://github.com/skydoves/Only#clear-data)

**Comment by skydoves** [comment]
Hi @utkualtas,
Thanks for your issue!
A new snapshot `1.3.8-SNAPSHOT` is released.

**Comment by utkualtas** [comment]
Thank you, that was fast @skydoves 👍

**Comment by utkualtas** [comment]
Hi again @skydoves,
I just noticed that we need a Balloon instance to call `clearAllPreferences()`. Do we have a chance convert `Balloon().clearAllPreferences()` to direct access without creating the `Balloon` instance `Balloon.clearAllPreferences()`  as like with [Only](https://github.com/skydoves/Only#clear-data)

**Comment by skydoves** [comment]
Oh, that's a good point.
You can use like this `BalloonPersistence.getInstance(context).clearAllPreferences()` in the new snapshot version `1.3.8.1-SNAPSHOT`.
If your project uses a design pattern like dependency injection, I recommend providing the instance of the `BalloonPersistence` on you class. Thanks for your feedback and sponsorship! 😄

**Comment by utkualtas** [comment]
I will consider the DI. Thanks again for the great works! 🙂
