### ISSUE TITLE
How to show Balloon immediately on Fragment or Activity?

### ISSUE THREAD

**Issue by orkndev** [skydoves/Balloon#243]
**Is your feature request related to a problem?**

A clear and concise description of what the problem is.

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

**Comment by skydoves** [comment]
You can just show up balloon immediately using the `show___` functions.
Activity: `onCreate`
Fragment: `onViewCreated`

**Comment by orkndev** [comment]
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val btn = findViewById<Button>(R.id.btn)
        val locationArray = IntArray(2)
        btn.getLocationOnScreen(locationArray)
        val hint =
                BalloonFactory(
                        btn,
                        "asdadsadasdasdasdasdasdasd",
                        locationArray[0]
                ).create(
                        btn.context,
                        this
                )
        hint.show(btn)
    }


do u mean this?

**Comment by orkndev** [comment]
it only works with setOnclickListener withoud doesnt

override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val btn = findViewById<Button>(R.id.btn)
        val balloon = createBalloon(this) {
            setArrowSize(10)
            setWidth(BalloonSizeSpec.WRAP)
            setHeight(65)
            setArrowPosition(0.7f)
            setCornerRadius(4f)
            setAlpha(0.9f)
            setText("You can access your profile from now on.")
            setTextColorResource(R.color.white)
            setTextIsHtml(true)
            setBackgroundColorResource(R.color.black)
            setBalloonAnimation(BalloonAnimation.FADE)
            setLifecycleOwner(lifecycleOwner)
        }
        btn.setOnClickListener {
            balloon.show(btn)
        }
    }

**Comment by skydoves** [comment]
```kotlin
btn.post {
  balloon.show(btn)
}
```

**Comment by orkndev** [comment]
thank you for your fast reply, you helped me a lot
