### ISSUE TITLE
IsStatusBarVisible is not working

### ISSUE THREAD

**Issue by vrsrohit** [skydoves/Balloon#250]
Hey I want the status bar to be invisible when opening the balloon 
But the variable you have provided is not working setIsStatusBarVisible(false)
Can you guide me here? 
Can I get the window object of the balloon so that I can modify its attributes.

Thanks for the amazing library!

![Screenshot 2021-09-28 at 10 00 54 PM](https://user-images.githubusercontent.com/18658206/135129497-7bb8f2e1-4cfe-4487-95ff-e068cacf9e82.png)

**Comment by skydoves** [comment]
Hi @vrsrohit,
The `setIsStatusBarVisible` method is only used to calculate the position of the arrow based on the parent Activity's status bar visibility. It doesn't change the visibility of the Activity's status bar.
