### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by zaaach** [skydoves/Balloon#260]
Library Version [v1.3.9]
Project [java]

can't import com.skydoves.balloon.Balloon;

build error:
import com.skydoves.balloon.Balloon;
                           ^
  ��������ļ�: F:\Android\gradle\caches\transforms-2\files-2.1\87138e7b65e172dd3beca46fa34a43b8\jetified-balloon-1.3.8-api.jar(com/skydoves/balloon/Balloon.class)
    ���ļ����д���İ汾 55.0, ӦΪ 52.0
    ��ɾ�����ļ���ȷ�����ļ�λ����ȷ����·����Ŀ¼�С�

**Comment by skydoves** [comment]
I guess your project does not use the [Jetifier](https://developer.android.com/studio/command-line/jetifier?hl=ko) or `androidX` options..? And the Gradle version seems too old.

**Comment by zaaach** [comment]
I upgrade studio version and use gradle version 7.0.2, then it works. Thanks! @skydoves

**Comment by Azazel** [comment]
Is there a way to keep using this library while still using Java 1.8? 
My project is very big and chaning java version is quite a challenge (even updating gradle is not an easy task).
