### ISSUE TITLE
When I use global class variable {  var balloon: Balloon? = null} , it throws this error, [My Project uses Java 1.8, gradle version 4.1.3/7.2] 

### ISSUE THREAD

**Issue by therealsanaullah** [skydoves/Balloon#264]
bad class file: /Users/Desktop/.gradle/caches/transforms-3/376dbd433db99e4745ea83/transformed/jetified-balloon-1.3.9-api.jar(com/skydoves/balloon/Balloon.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by skydoves** [comment]
Looks similar to #260

**Comment by skydoves** [comment]
I recommend using Java 11 and could you please build again after clean/sync Gradle?

**Comment by CzarMatt** [comment]
It seems version 1.3.7+ has been compiled against Java 11, is this correct?

I too have a very large project that is still on Java 8, we can't use the latest version of Balloon SDK.

**Comment by skydoves** [comment]
Hey @CzarMatt, please check the [new version](https://github.com/skydoves/Balloon/releases/tag/1.4.0).

**Comment by CzarMatt** [comment]
@skydoves  Oh!  🤦   I missed that that was released.  I will check it - thanks so much!  👍

**Comment by skydoves** [comment]
No problem! If you got the same error in the new version, please let me know :)
