### ISSUE TITLE
setBalloonHighlightAnimation default parameter?

### ISSUE THREAD

**Issue by znakeeye** [skydoves/Balloon#265]
Using `AGP 7.0.3` and `AS 2020.3.1`.

**build.gradle**
```gradle
implementation "com.github.skydoves:balloon:1.3.9"
```

Using `java` if that matters. I tried adding a highlight animation as shown below. For some reason I got a compilation error. I can see in the method declaration that the second parameter has a default value of `0L`. So why this compilation error?

**Java class**
```
.setBalloonHighlightAnimation(BalloonHighlightAnimation.SHAKE)
                ^
  required: BalloonHighlightAnimation,long
  found: BalloonHighlightAnimation
  reason: actual and formal argument lists differ in length
```

**Comment by skydoves** [comment]
Hi, you can resolve it using the below way, however, I will fix it on the next release.
```kotlin
.setBalloonHighlightAnimation(BalloonHighlightAnimation.SHAKE, 0L)
```
Thanks!
