### ISSUE TITLE
Align to Anchor showAlignTop/showAlignBottom not executing during orientation change 

### ISSUE THREAD

**Issue by RahulPilot** [skydoves/Balloon#267]
- Library Version - v1.3.4
- Affected Device- e.g. Redmi note 9 pro max with Android 11.0

The balloon is not respecting showAlignTop/showAlignBottom . This is happening only for the first time during orientation change and not subsequent times. 

    balloon = createBalloon(this) {
            setIsVisibleArrow(true)
            setArrowSize(BalloonSizeSpec.WRAP)
            setArrowPosition(0.5f)
            setArrowOrientation(if (isLandscape(this@activity)) ArrowOrientation.LEFT else 
            ArrowOrientation.BOTTOM)
            setArrowPositionRules(ArrowPositionRules.ALIGN_BALLOON)
            setArrowDrawable(
                ContextCompat.getDrawable(
                    this@activity,
                    R.drawable.xyz
                )
            )
            
            setLayout(R.layout.abc)
            setMargin(6)
            setCornerRadius(15f)
            setBackgroundColorResource(R.color.grey)
            setBalloonAnimation(BalloonAnimation.CIRCULAR)
            setLifecycleOwner(lifecycleOwner)
            setIsVisibleOverlay(true) // sets the visibility of the overlay for highlighting an anchor.
            setOverlayColorResource(R.color.overlay) // background color of the overlay using a color resource.
            setOverlayPadding(6f) // sets a padding value of the overlay shape internally.
            setOverlayShape(BalloonOverlayRoundRect(15f, 15f))
            setBalloonOverlayAnimation(BalloonOverlayAnimation.FADE) // default is fade.
            setDismissWhenOverlayClicked(false)
        }

     if (isLandscape(this)) {
            (landscape layout anchor)?.let { balloon.showAlignRight(it) }
        } else {
            (portrait layout anchor)?.let { balloon.showAlignTop(it) }
        }

        balloon.setOnBalloonOutsideTouchListener { _, _ ->
            viewmodel.setTooltipClicked(true)
        }
` 

https://user-images.githubusercontent.com/87669932/137732947-5748da17-b5e3-46f2-a8fc-11a559c64d0c.mp4

![D561AC48-39F6-4F92-B0A1-8BF405CBE038_1_105_c](https://user-images.githubusercontent.com/87669932/137734609-2fc17188-1070-4f06-bb6b-7d6b59ebedad.jpeg)

**It should respect the "align to anchor" code**

![BFA9634B-B857-43BD-BF63-FEC839267FAC_1_105_c](https://user-images.githubusercontent.com/87669932/137734416-3b07fc46-96ca-4d62-a4de-3e58f09514dc.jpeg)

**Comment by skydoves** [comment]
Hey @RahulPilot, sorry for the late response.
In this case, you must achieve this with the `savedInstanceState` as seen in the below:

```kotlin
  override fun onSaveInstanceState(outState: Bundle) {
    super.onSaveInstanceState(outState)

    if (editBalloon.isShowing) {
      outState.putBoolean("shouldBeShown", true)
    } else {
      outState.putBoolean("shouldBeShown", false)
    }
  }

  override fun onRestoreInstanceState(savedInstanceState: Bundle) {
    super.onRestoreInstanceState(savedInstanceState)

    if (savedInstanceState.getBoolean("shouldBeShown")) {
      binding.circleImageView.showAlignBottom(editBalloon)
    }
  }
```

If you keep facing this issue, feel free to re-open this issue. Thanks!
