### ISSUE TITLE
Corner radius doesn't work when using custom layout without padding

### ISSUE THREAD

**Issue by i-schuetz** [skydoves/Balloon#27]
**Please complete the following information:**
- Library Version 1.1.2
- Affected Device(s) Emulator
 
<img width="341" alt="Screen Shot 2020-03-24 at 15 59 55" src="https://user-images.githubusercontent.com/1381744/77440407-8e921500-6de8-11ea-867b-7baa654dbc6d.png">

```kotlin
setArrowSize(10)
//        setWidthRatio(1.0f)
setHeight(65)
setPadding(0)
//        setDismissWhenTouchOutside(true)
setPaddingLeft(10)
setPaddingRight(10)
//        setArrowPosition(.5f)
setSpace(10)
setCornerRadius(10f)
setAlpha(1f)
setTextColorResource(R.color.white)
setBackgroundColorResource(R.color.colorAccent)
setOnBalloonClickListener {
    onClick?.invoke()
}
setBalloonAnimation(BalloonAnimation.ELASTIC)
setLifecycleOwner(lifecycleOwner)
```

**Comment by i-schuetz** [comment]
I tried now setting the corner radius in the custom layout and setting the balloon's background to transparent, but the arrow shows black. I need the arrow to be blue (like the left part).

<img width="245" alt="Screen Shot 2020-03-24 at 16 18 33" src="https://user-images.githubusercontent.com/1381744/77443324-488a8080-6deb-11ea-8133-049c5632577d.png">

**Comment by skydoves** [comment]
Hi, the `cornerRadius` attribute works fine when using a custom layout.
You can check the [demo](https://github.com/skydoves/Balloon/blob/master/app/src/main/res/layout/layout_custom_list.xml) codes.
And there is the [builder](https://github.com/skydoves/Balloon/blob/master/app/src/main/java/com/skydoves/balloondemo/factory/CustomListBalloonFactory.kt).

**Comment by i-schuetz** [comment]
To me it works only if both the custom layout and the bubble have corner radius. I think your example works without radius in the custom layout, because you have inner padding. I can't use padding because of the design.

**Comment by skydoves** [comment]
You can test the [demo](https://github.com/skydoves/Balloon/blob/master/app/src/main/res/layout/layout_custom_list.xml#L9) without padding. And the padding on RecyclerView is for aligning center, not for corner radius.

```kotlin
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  xmlns:tools="http://schemas.android.com/tools"
  android:layout_width="wrap_content"
  android:layout_height="wrap_content"
  android:gravity="center"
  android:orientation="vertical">

  <androidx.recyclerview.widget.RecyclerView
    android:id="@+id/list_recyclerView"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
    tools:listitem="@layout/item_custom" />
</LinearLayout>
```

![KakaoTalk_20200327_154808078](https://user-images.githubusercontent.com/24237865/77729604-6867b180-7042-11ea-9f03-e07c7bc04c5e.jpg)

**Comment by skydoves** [comment]
You can test the [demo](https://github.com/skydoves/Balloon/blob/master/app/src/main/res/layout/layout_custom_list.xml) codes without padding. And the padding values in the RecyclerView is for aligning contents to the center, not for corner radius.

#### XML layout
```gradle
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  xmlns:tools="http://schemas.android.com/tools"
  android:layout_width="wrap_content"
  android:layout_height="wrap_content"
  android:gravity="center"
  android:orientation="vertical">

  <androidx.recyclerview.widget.RecyclerView
    android:id="@+id/list_recyclerView"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
    tools:listitem="@layout/item_custom" />
</LinearLayout>
```

#### Builder
```kotlin
Balloon.Builder(context)
      .setLayout(R.layout.layout_custom_list)
      .setArrowSize(40)
      .setArrowOrientation(ArrowOrientation.TOP)
      .setArrowPosition(0.85f)
      .setWidth(170)
      .setHeight(200)
      .setTextSize(12f)
      .isRtlSupport(BalloonUtils.isRtlLayout())
      .setCornerRadius(14f)
      .setBackgroundColorResource(R.color.background800)
      .setBalloonAnimation(BalloonAnimation.FADE)
      .setDismissWhenShowAgain(true)
      .setLifecycleOwner(lifecycle)
      .build()
  }
```

#### Result
![KakaoTalk_20200327_154808078](https://user-images.githubusercontent.com/24237865/77729914-1d9a6980-7043-11ea-8591-118b9160d38d.jpg)

**Comment by skydoves** [comment]
@i-schuetz 
Hi, It is fixed in the new release [1.1.3](https://github.com/skydoves/Balloon/releases).

**Comment by i-schuetz** [comment]
Confirm that it's working 👍

**Comment by i-schuetz** [comment]
Is it not possible to do a single time payment with sponsors? 🤔 Wanted to "buy you a coffee" but I'm not doing a "subscription"...

**Comment by skydoves** [comment]
Hi, If you cancel sponsoring right after sponsoring via GitHub Sponsors, the subscription will be canceled automatically after next month. Or another [platform](https://www.buymeacoffee.com/skydoves). 
Anyway, thank you for your contributions to make grow the quality of the library. 🙏
