### ISSUE TITLE
overlay alignment issue

### ISSUE THREAD

**Issue by gangadharashettypj** [skydoves/Balloon#272]
- Library Version [e.g. v1.3.8]
- all devices
 
**Describe the Bug:**

> fun showAtCenter(
    anchor: View,
    xOff: Int = 0,
    yOff: Int = 0,
    centerAlign: BalloonCenterAlign = BalloonCenterAlign.TOP
  ) {
    val halfAnchorWidth = (anchor.measuredWidth * 0.5f).roundToInt()
    val halfAnchorHeight = (anchor.measuredHeight * 0.5f).roundToInt()
    val halfBalloonWidth = (getMeasuredWidth() * 0.5f).roundToInt()
    val halfBalloonHeight = (getMeasuredHeight() * 0.5f).roundToInt()
    show(anchor) {
      when (centerAlign) {
        BalloonCenterAlign.TOP ->
          bodyWindow.showAsDropDown(
            anchor,
            builder.supportRtlLayoutFactor * (halfAnchorWidth - halfBalloonWidth + xOff),
            -(getMeasuredHeight() + halfAnchorHeight) + yOff
          )
        BalloonCenterAlign.BOTTOM ->
          bodyWindow.showAsDropDown(
            anchor,
            builder.supportRtlLayoutFactor * (halfAnchorWidth - halfBalloonWidth + xOff),
            -halfBalloonHeight + halfAnchorWidth + yOff
          )
        BalloonCenterAlign.START ->
          bodyWindow.showAsDropDown(
            anchor,
            builder.supportRtlLayoutFactor * (halfAnchorWidth - getMeasuredWidth() + xOff),
            (-getMeasuredHeight() + halfAnchorHeight) + yOff
          )
        BalloonCenterAlign.END ->
          bodyWindow.showAsDropDown(
            anchor,
            builder.supportRtlLayoutFactor * (halfAnchorWidth + getMeasuredWidth() + xOff),
            (-getMeasuredHeight() + halfAnchorHeight) + yOff
          )
      }
    }
  }

I am using the showAtCentre() to display the overlay, since its internally using getMeasuredWidth(), it's always returning 0, because of this the overlay is not centre aligned. 

**Expected Behavior:**

getMeasuredWidth() has to return the width of the overlay. So that the overlay is centre aligned with the anchor view given

**Comment by skydoves** [comment]
Hey @gangadharashettypj,
Could you expand on this? `showAtCenter` is not related to the overlay, it adjusts only the location of the balloon.
And it would be easier to analyze this issue if you can provide the code snippets of your builder. 😄
