### ISSUE TITLE
Error inflating AppCompatImageView

### ISSUE THREAD

**Issue by nazarabd3005** [skydoves/Balloon#276]
**Please complete the following information:**
- Library Version 1.3.9
- Affected Device(s) Galaxy A32 with Android 11
 
**Describe the Bug:**

crash on Binary XML file line #65 in com.forest_interactive.walletcodes.b2c:layout/layout_balloon_library_skydoves: Error inflating class androidx.appcompat.widget.AppCompatImageView

Caused by android.content.res.Resources$NotFoundException

**Expected Behavior:**

can inflate the AppCompatImageView without crash

**Comment by skydoves** [comment]
Hey @nazarabd3005 ,
Do you have a custom `layout_balloon_library_skydoves` file in your project?

**Comment by skydoves** [comment]
Please re-open this issue if you face this issue continuously. :)

**Comment by nazarabd3005** [comment]
Hi @skydoves sorry for late replying , currently still getting the issue with version: 1.3.9
there's no custom layout you mention so iam wondering it is already fixed in latest versions?

**Comment by skydoves** [comment]
I guess your project does not include the `implementation "androidx.appcompat:appcompat:1.4.0"`?

**Comment by nazarabd3005** [comment]
owh so the minimum appCompat version is 1.4.0? because my project still using 1.3.1

**Comment by ismailrohaga** [comment]
but how about if i have a custom balloon layout? is there anything that i sould consider other than to pass it in `.setLayout` [this](https://github.com/skydoves/Balloon#custom-balloon-layout). because in my view i use ImageView for closing the balloon by getting it from `getContentView`

**Comment by skydoves** [comment]
@nazarabd3005, @ismailrohaga
I'm wondering does your project includes the code below on your build.gradle file.

```
vectorDrawables.useSupportLibrary = true
```

**Comment by nazarabd3005** [comment]
@skydoves the code is already include on build.gradle

**Comment by skydoves** [comment]
You should check out the two things below:
- The balloon dependency is the latest. `1.4.5`.
- Your app's style is under the `Theme.AppCompat`.
