### ISSUE TITLE
setShouldPassTouchEventToAnchor doesn't pass touch event to anchor

### ISSUE THREAD

**Issue by TylerMcCraw** [skydoves/Balloon#288]
**Please complete the following information:**
- Library Version: 1.4.0
- Affected Device(s): Pixel 6 Pro, Android 12
 
**Describe the Bug:**

When setting `setShouldPassTouchEventToAnchor(true)`, no touch event is passed to the anchor view.
Specifically, within 
```private fun passTouchEventToAnchor(anchor: View)```,
the `setOnBalloonOverlayTouchListener` listener is never called
https://github.com/skydoves/Balloon/blob/857882d58e3ee4e7bdb00faa4b25c848d810da0c/balloon/src/main/kotlin/com/skydoves/balloon/Balloon.kt#L1285

**Expected Behavior:**
If calling `setShouldPassTouchEventToAnchor(true)`, all touch events should be passed to the anchor view so that the anchor view properly receives a touch event.

**Comment by ultrah** [comment]
I can reproduce, looks like the listener is never called.

I found a workaround by attaching a touch listener to `bodyWindow`:

```kotlin
balloon.bodyWindow.setTouchInterceptor { view, event ->
      view.performClick()
      val rect = Rect()
      myAnchorView.getGlobalVisibleRect(rect)
      if (rect.contains(event.rawX.toInt(), event.rawY.toInt())) {
        balloon.dismiss()
        myAnchorView.dispatchTouchEvent(event)
        true
      } else false
    }
```

**Comment by skydoves** [comment]
Hi, in this case, you should use the `setDismissWhenTouchOutside` method like the below:

```kotlin
.setIsVisibleOverlay(true)
.setDismissWhenTouchOutside(false)
.setShouldPassTouchEventToAnchor(true)
```

If you keep facing the same issue, feel free to re-open this issue. Thanks!
