### ISSUE TITLE
Proper support of RTL positioning of balloons

### ISSUE THREAD

**Issue by javernaut-hs** [skydoves/Balloon#289]
**Is your feature request related to a problem?**

An app I'm developing right now relies on RTL features and the Balloon library doesn't support it properly.

**Describe the solution you'd like:**

I would like methods like Balloon.showAlignStart() and Balloon.showAlignEnd() introduced which would properly position the Balloons and direct the arrow.
Also setting margins, paddings for start/end will be appreciated.
And the arrowPosition should consider the RTL mode too (even if the balloon was shown to the bottom or the top of its anchor view).

**Describe alternatives you've considered:**

Don't think there can be an elegant alternative here.
I ended up writing a poor code for manual computing of xOffset for RTL cases, which is definitely not the good way of displaying the balloons.

**Comment by skydoves** [comment]
#316

**Comment by skydoves** [comment]
#317

**Comment by skydoves** [comment]
Hi @javernaut-hs, the new **1.4.3** version has been released.
The RTL layout mode will be enabled by default. Please try the code below:

```kotlin
balloon.showAlign(
    align = BalloonAlign.START, // this alignment will be changed to END if the device is in the RTL mode.
    mainAnchor = circleImageView,
  )
```
Thanks!
