### ISSUE TITLE
Tooltips don't disappear when leaving fragment

### ISSUE THREAD

**Issue by i-schuetz** [skydoves/Balloon#29]
**Please complete the following information:**
- Library Version 1.1.2
- Affected Device(s) Emulator
 
**Describe the Bug:**

Settings:
```kotlin
setArrowSize(10)
//        setWidthRatio(1.0f)
setHeight(65)
setPadding(0)
setDismissWhenTouchOutside(true)
setPaddingLeft(10)
setPaddingRight(10)
//        setArrowPosition(.5f)
setSpace(10)
setCornerRadius(10f)
setAlpha(1f)
setTextColorResource(R.color.white)
setBackgroundColorResource(R.color.colorAccent)
setOnBalloonClickListener {
    onClick?.invoke()
}
setBalloonAnimation(BalloonAnimation.ELASTIC)
setLifecycleOwner(lifecycleOwner)
```

When I leave the fragment (e.g. to navigate to a new fragment). The tooltips stay on the screen.

**Expected Behavior:**

The tooltips disappear when navigating away (backwards or forwards) from fragment.

**Comment by skydoves** [comment]
Unfortunately, the balloon popup is not a view. It is a popup [window](https://developer.android.com/reference/android/view/Window). So the window can't be related to fragments back stacks or viewpager.

**Comment by i-schuetz** [comment]
Okay, I'd store the tooltips in a variable and close them manually when leaving the fragment.

**Comment by i-schuetz** [comment]
@skydoves is there a way to dismiss the tooltip without animating it? The close animation makes the tooltip stay a while on the screen while navigating away, which looks weird.

**Comment by skydoves** [comment]
@i-schuetz 
You can write customized animation styles.
Add below codes in your `styles.xml`.

```gradle
<style name="BalloonDispose">
  <item name="android:windowEnterAnimation">@anim/elastic_center</item>
  <item name="android:windowExitAnimation">@null</item>
</style>
```
There are [seven types](https://github.com/skydoves/Balloon/tree/master/balloon/src/main/res/anim) of default customized styles.

Remove `setBalloonAnimation` method and use `setBalloonAnimationStyle(R.style.BalloonDispose)` method. Thanks.

**Comment by i-schuetz** [comment]
The problem is that I want to disable the animation only when dismissing as part of leaving the screen. I want to keep them for normal usage.
