### ISSUE TITLE
Version 1.2.4+ doesn't show balloon on first startup

### ISSUE THREAD

**Issue by skywalkerdude** [skydoves/Balloon#290]
**Please complete the following information:**
- Library Version 1.2.4+
- Affected Device(s) All devices AFAIK (tested on API 23 Emulator and API 30 Pixel 5 device)
 
**Describe the Bug:**

Repository with reproduction of bug: https://github.com/skywalkerdude/TestRepo

1) Create a dummy repo from Android Studio wizard
2) Import [`com.github.skydoves:balloon:1.2.4`](https://github.com/skywalkerdude/TestRepo/blob/main/app/build.gradle#L34). I used 1.2.4 because that was the earliest version for which this issue appeared (works on 1.2.3). However, this is incorrect behavior also appears on the latest (1.4.1) version.
3) Follow [documentation](https://github.com/skydoves/Balloon#basic-example-for-java) in [creating and showing a balloon tooltip](https://github.com/skywalkerdude/TestRepo/blob/main/app/src/main/java/com/example/testrepo/FirstFragment.java#L35-L47)
4) Run the app, observe that the balloon does not appear until you hit "Next" then go back:
<img src="https://user-images.githubusercontent.com/1427524/147371653-28723b20-0a64-440d-b013-d46bfc3a96b1.gif" height="30%" width="30%"/>

5) Change library version to [`com.github.skydoves:balloon:1.2.3`](https://github.com/skywalkerdude/TestRepo/blob/1.2.3/app/build.gradle#L34)
6) Run app again and observe that it works as expected:
<img src="https://user-images.githubusercontent.com/1427524/147371709-be0dd5d1-034c-4697-82be-2bd291898f25.gif" height="30%" width="30%"/>

**Expected Behavior:**

Let me know if I am creating the balloon incorrectly, but I would expect it to show up as soon as I open the app

**Comment by skydoves** [comment]
Hey, could you try the codes below with the Balloon `1.4.1`?

```java
binding.textView.post(new Runnable() {
      @Override
      public void run() {
            balloon.show(binding.textviewFirst);
      }
    });
```

**Comment by skywalkerdude** [comment]
That seems to work! Is the right long-term solution, though? To post it in a runnable every time we need to show it? Or is this just a temporary workaround?

**Comment by skydoves** [comment]
Yes, that's the long-term solution. The balloon should be shown up after inflating the anchor view to calculate the expected position. So if you need to show up the balloon without listeners, it should be used with the `post` method.
On the other hand, if you need to show up the balloon inside of listeners such as `OnClickListener`, you don't need to use the `post` method, because it's already finished inflating your anchor view.
