### ISSUE TITLE
Top App Bar's Action Item Balloon Shows Inconsistent Color Fill-up On The Items.

### ISSUE THREAD

**Issue by itsnitish22** [skydoves/Balloon#298]
**Please complete the following information:**
- Library-Version: v1.4.1
- Affected Device: Realme C1 with Android 9.0
 
**Describe the Bug:**

Top App Bar has an action item, on which when we click a balloon appears, showing 4 items in it. When we long tap on each item a color fills up showing the touch. But the color fillup is inconsistent in all the items. Refer the attached screenshots for more clarification.
![Screenshot_2022-01-01-18-09-49-26_e721f2bb171a194dd4d07450abd1e101](https://user-images.githubusercontent.com/73310532/147852559-27540192-d88c-4e32-964d-6c5aab3bf73c.png)
![Screenshot_2022-01-01-18-18-54-22_e721f2bb171a194dd4d07450abd1e101](https://user-images.githubusercontent.com/73310532/147852571-468a2845-0be2-4300-a7a7-16a3f495c84f.png)
![Screenshot_2022-01-01-18-18-59-35_e721f2bb171a194dd4d07450abd1e101](https://user-images.githubusercontent.com/73310532/147852573-c6c4c23e-d60c-4493-bde2-1445007242d0.png)
![Screenshot_2022-01-01-18-19-03-65_e721f2bb171a194dd4d07450abd1e101](https://user-images.githubusercontent.com/73310532/147852576-513f1232-0689-4d43-af06-454cf89845b9.png)

**Expected Behavior:**

On a long tap of each item, the color fill-up must be consistent or the same.

**Comment by itsnitish22** [comment]
I think this bug is a good first issue and I would like to work on it. It'll be great if I get some guidance.

**Comment by skydoves** [comment]
Hey @itsnitish22!
Sorry for my late response. Would you like to work on this? I'll assign this issue to you if you'd like to resolve this. 😄

**Comment by itsnitish22** [comment]
Hi @skydoves 
Yes, I would definitely like to work on this issue. 
You can assign this to me :)

**Comment by itsnitish22** [comment]
Hey @skydoves, I went through the code but wasn't able to find the function where it focuses on the item when it is tapped.
Could you please tell that exactly where can I find it.

**Comment by skydoves** [comment]
The `android:background="?android:selectableItemBackground"` implements ripple effect on [the item](https://github.com/skydoves/Balloon/blob/main/app/src/main/res/layout/item_custom.xml#L7).

**Comment by itsnitish22** [comment]
@skydoves I have created a pull request. You can review it :)
