### ISSUE TITLE
There is no way to set OnBalloonOutsideTouchListener (Java). No dismiss on outside click.

### ISSUE THREAD

**Issue by wseme-kiswe** [skydoves/Balloon#3]
- Library version 1.0.0
- All devices
- Java 1.8

**Describe the Bug:**
There is an interface called ```OnBalloonOutsideTouchListener``` in this library. There is no listener or callback setter function for this to be set in the Balloon class. What is the purpose of this interface?
I am looking for a way to make the popup dismiss when there is a click outside of the popup. Similar to I have found no way enable this in the library.
This would be similar functionality to doing: ```DialogFragment.getDialog().setCanceledOnTouchOutside(true);```

**Expected Behavior:**
I would expect the Balloon class to have a ```setOnBalloonOutsideTouchListener(OnBalloonOutsideTouchListener listener)```  and ```setOnBalloonOutsideTouchListener(OnBalloonOutsideTouchListener listener)```  functions to enable the listener to be get and set.
If this feature is not supported, then I would expect this class to be removed.

**Comment by skydoves** [comment]
@wseme-kiswe 
Hi,
It is not implemented yet.
It will be implemented in the next release.
Thank you for your issue!

**Comment by skydoves** [comment]
@wseme-kiswe 
Hi, below methods are added newly in version `1.0.1`.
- `setOnBalloonOutsideTouchListener(value: OnBalloonOutsideTouchListener)`
- `setDismissWhenTouchOutside(value: Boolean)`

Thank you for your issue :)
