### ISSUE TITLE
Button to open tooltip not interactive after opening/closing

### ISSUE THREAD

**Issue by i-schuetz** [skydoves/Balloon#30]
**Please complete the following information:**

- Library Version 1.1.2
- Affected Device(s) Emulator

**Describe the Bug:**

When using `setDismissWhenTouchOutside`, after the tooltip has been opened once, it doesn't open again. Sometimes it works. Happens in a `RecyclerView` (see other issues for screenshots). I don't know if it happens when not in a `RecyclerView`.

```kotlin
setTextResource(text)
setPaddingLeft(10)
setPaddingRight(10)
setBackgroundColorResource(colorAccent)
setTextColorResource(white)
setCornerRadius(15f)
setArrowSize(10)
//        setWidthRatio(1.0f)
setHeight(65)
//        setPadding(0)
setDismissWhenTouchOutside(true)
//        setArrowPosition(.5f)
setSpace(-10)
setAlpha(1f)
setOnBalloonClickListener {
    onClick?.invoke()
}
setBalloonAnimation(ELASTIC)
setLifecycleOwner(lifecycleOwner)
```

**Expected Behavior:**

The tooltip can be opened again.

**Comment by skydoves** [comment]
#25

**Comment by skydoves** [comment]
It's duplicated. I will notify you if the issue will be resolved.

**Comment by i-schuetz** [comment]
It's working in 1.1.4. Thanks for fixing it so quickly!
