### ISSUE TITLE
1.4.2 module contains AgpVersionAttr and causes build failures

### ISSUE THREAD

**Issue by G00fY2** [skydoves/Balloon#307]
**Please complete the following information:**
- Library Version 1.4.2
 
**Describe the Bug:**

Seems like you updated to AGP 7.1 but did not update Kotlin to contain the fix about [AgpVersionAttr](https://youtrack.jetbrains.com/issue/KT-49798) ([1.5.32](https://github.com/JetBrains/kotlin/releases/tag/v1.5.32) or [1.6.10](https://github.com/JetBrains/kotlin/releases/tag/v1.6.10)). Because of that there is the following attribute in your [ballon-1.4.2.module](https://repo1.maven.org/maven2/com/github/skydoves/balloon/1.4.2/balloon-1.4.2.module) file (which did not exist in 1.4.1):
```
"com.android.build.api.attributes.AgpVersionAttr": "7.1.0"
```

This causes builds with a different AGP version to fail with the following message:
> Using multiple versions of the Android Gradle plugin(7.1.0, 7.1.1) in the same build is not allowed.

**Expected Behavior:**

The AgpVersionAttr should not leak and the library should be compatible across different AGP version.

**Comment by skydoves** [comment]
Hi @G00fY2!
Thanks for reporting this and great description! 
I just released `1.4.3-SNAPSHOT` on the maven with Kotlin `1.5.32`. Please check it work on your project and let me know if the same issue happens. Thanks!

**Comment by skydoves** [comment]
@G00fY2 Thank you for checking this!
They will be included in the next stable release. 🎉

**Comment by okarakose** [comment]
Is there any release date for new version for this fix? @skydoves

**Comment by skydoves** [comment]
Hi everyone, the new version **1.4.3** has been released.
Please check out the new version. Thanks!
