### ISSUE TITLE
`setSpace` seems not to work?

### ISSUE THREAD

**Issue by i-schuetz** [skydoves/Balloon#31]
**Please complete the following information:**
- Library Version 1.1.2
- Affected Device(s) Emulator
 
**Describe the Bug:**

I want to add some space between the arrow and the view it points too. It seems that I should use `setSpace` for this. But any value I enter here has no effect. Not sure if this is the correct setting. Note: Using in a `RecyclerView`

```swift
setTextResource(text)
setPaddingLeft(10)
setPaddingRight(10)
setTextColorResource(white)
setArrowSize(10)
setHeight(65)
setDismissWhenTouchOutside(true)
setBackgroundColorResource(colorAccent)
setCornerRadius(15f)
setSpace(100)
setAlpha(1f)
setDismissWhenShowAgain(true)
setOnBalloonClickListener {
    onClick?.invoke()
}
setBalloonAnimation(ELASTIC)
setLifecycleOwner(lifecycleOwner)
```

**Expected Behavior:**

I can set the space.

**Comment by skydoves** [comment]
`setSpace` sets the side space between popup and display.
It only works when used with `widthRatio`.
```kotlin
 /** sets the side space between popup and display. */
fun setSpace(@Dp value: Int): Builder = apply { this.space = context.dp2Px(value) }
```
You should use show the balloon with `xOff` and `yOff`.
```kotlin
balloon.show(anchor: View, xOff: Int, yOff: Int) // shows the balloon on an anchor view with x-off and y-off.
balloon.showAlignTop(anchor: View, xOff: Int, yOff: Int) // shows top alignment with x-off and y-off.
balloon.showAlignBottom(anchor: View, xOff: Int, yOff: Int) // shows bottom alignment with x-off and y-off.
balloon.showAlignRight(anchor: View, xOff: Int, yOff: Int) // shows right alignment with x-off and y-off.
balloon.showAlignLeft(anchor: View, xOff: Int, yOff: Int) // shows left alignment with x-off and y-off.
```
Same #28

**Comment by i-schuetz** [comment]
Ok, I tried:
```kotlin
packageTitle.showBalloon(this, xOff = 0, yOff = yOffset)
````
With different values for `yOffset`, `5`, `-2`, and the bubble always shows ~20dp to the bottom:

<img width="261" alt="Screen Shot 2020-03-25 at 08 34 20" src="https://user-images.githubusercontent.com/1381744/77512601-a4005100-6e73-11ea-89d3-0f2c9e2d5cd6.png">

(In the screenshot I clicked the pen at the top)

I understand that I don't need to set `widthRatio` for `yOff`.

**Comment by skydoves** [comment]
It seems you should use `balloon.showAlignTop(anchor: View, xOff: Int, yOff: Int) // shows top alignment with x-off and y-off.` with adjusting `y-off`. You can put a negative value of the `y-off`.

**Comment by i-schuetz** [comment]
It works with `showAlignTop`, thanks!
