### ISSUE TITLE
balloon display issue

### ISSUE THREAD

**Issue by traiyani** [skydoves/Balloon#310]
**Please complete the following information:**
- Library Version 1.4.2
- Affected Device(s) One plus 6T
 
**Describe the Bug:**

![image](https://user-images.githubusercontent.com/8299117/157203889-4c81d904-4c38-4945-9e47-d762083c40f6.png)

**Expected Behavior:**

not getting valid balloon arrow position in arabic layout

**Comment by skydoves** [comment]
Hi @traiyani, sorry for the late response.
Could you expand on this? It would be helpful to analyze this issue if you could attach your `Balloon.Builder`.
Thanks!

**Comment by skydoves** [comment]
Please re-open this issue again if you reproduce this issue again.
