### ISSUE TITLE
Bad maven deployment after updating publish-plugin

### ISSUE THREAD

**Issue by G00fY2** [skydoves/Balloon#318]
Hi,

with the release of 1.4.3 the deployment on maven central is somewhat "broken" and e.g. our dependency update plugin does not recognise the latest version.

You uploaded variant specific artifacts **balloon-1.4.3-debug.aar** & **balloon-1.4.3-release.aar** instead of **balloon-1.4.2.aar**.

This is probably because you updated the gradle-maven-publish-plugin to [0.19.0](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/CHANGELOG.md#version-0190-2022-02-26) and did not adjust the library variant configuration (which was a behaviour change in this update, see changelog).

You can see this when looking at the [artifactes for 1.4.2](https://repo1.maven.org/maven2/com/github/skydoves/balloon/1.4.2/) on maven central vs the [artifacts for 1.4.3](https://repo1.maven.org/maven2/com/github/skydoves/balloon/1.4.3/).

This is also true for all other Android libraries you maintain and where you updated to gradle-maven-publish-plugin 0.19.0.

**Comment by skydoves** [comment]
Hi @G00fY2, this issue will be fixed in the next release and you can use earlier snapshot builds.
Thank for reporting this!
