### ISSUE TITLE
Set Arrow seems to not working

### ISSUE THREAD

**Issue by pcharbonnier** [skydoves/Balloon#32]
**Please complete the following information:**
- Library Version v1.1.2
- Affected Device(s) (Tablet Samsung) Galaxy TAB A 2016
 
**Describe the Bug:**

I'm trying to add my custom arrow to the balloon but it only show the default one.
I tried with both methods

> setArrowDrawableResource
> setArrowDrawable

```
 val balloon = Balloon.Builder(this)
                .setLayout(R.layout.popup_qty)
                .setArrowSize(15)
                .setArrowOrientation(ArrowOrientation.TOP)
                .setArrowPosition(0.5f)
                .setCornerRadius(10f)
                .setArrowVisible(true)
                .setArrowDrawable(ContextCompat.getDrawable(this, R.drawable.ic_custom_arrow))
                .setBalloonAnimation(BalloonAnimation.OVERSHOOT)
                .setDismissWhenTouchOutside(true)
                .setLifecycleOwner(this)
                .build()

 balloon.showAlignBottom(view)
```

**Expected Behavior:**

Displaying my custom arrow

**Comment by skydoves** [comment]
@pcharbonnier 
Hi, could you test again with using the `.setBackgroundColorResource(R.color.colorPrimary)`?

**Comment by pcharbonnier** [comment]
hi @skydoves 

```
val balloon = Balloon.Builder(activity!!)
                .setLayout(R.layout.popup_plus_less_quantity)
                .setArrowSize(15)
                .setArrowOrientation(ArrowOrientation.TOP)
                .setArrowPosition(0.5f)
                .setCornerRadius(10f)
                .setDismissWhenTouchOutside(true)
                .setArrowVisible(true)
                .setArrowDrawable(ContextCompat.getDrawable(activity!!, R.drawable.ic_arrow_gray))
                .setBackgroundColorResource(R.color.colorPrimary)                       .setBalloonAnimation(BalloonAnimation.OVERSHOOT)
                .setLifecycleOwner(activity)
                .build()
```

I have test with `.setBackgroundColorResource(R.color.colorPrimary)`

Doesn't work
Except that my arrow have now the same color of as **colorPrimary**

**Comment by skydoves** [comment]
@pcharbonnier 
Hi, I released a new release [1.1.3](https://github.com/skydoves/Balloon/releases). You can test in the [demo](https://github.com/skydoves/Balloon/blob/master/app/src/main/java/com/skydoves/balloondemo/factory/ProfileBalloonFactory.kt) codes,
You can use `setArrowDrawableResource` with `setArrowColor` or `setArrowColorResource`. 

```kotlin
.setArrowDrawableResource(R.drawable.ic_arrow_gray)
.setArrowColorResource(R.color.yellow)
```

**Comment by pcharbonnier** [comment]
AAAh
Maybe I missed something but

` val balloon = Balloon.Builder(activity!!)
                .setLayout(R.layout.popup_plus_less_quantity)
                .setArrowOrientation(ArrowOrientation.TOP)
                .setCornerRadius(4f)
                .setDismissWhenTouchOutside(true)
                .setAlpha(0.9f)
                .isRtlSupport(isRtlLayout())
                .setBackgroundColorResource(R.color.transparent)
                .setArrowDrawable(ContextCompat.getDrawable(activity!!, R.drawable.ic_arrow_gray))
                .setBalloonAnimation(BalloonAnimation.CIRCULAR)
                .setLifecycleOwner(activity)
                .build()`

now I have my arrow drawable.
I removed some line and it's working.
Maybe `setArrowDrawable ` where incompatible with some methods.

So, sorry, MY BAD, sorry for the issue that is not really an issue

**Comment by skydoves** [comment]
Ah that's okay.
I'm glad your problem is solved.
Thank you :)
