### ISSUE TITLE
why your aar require the mincompileSdkVersion 31？？？？？？？？

### ISSUE THREAD

**Issue by amberkira** [skydoves/Balloon#322]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Hi, which version do you use?
The [current min SDK version](https://github.com/skydoves/Balloon/blob/main/buildSrc/src/main/kotlin/com/github/skydoves/balloon/Configuration.kt#L22) is 17.

**Comment by skydoves** [comment]
Please check out your current Compile SDK version is 31 and the corresponding Gradle version.

**Comment by amberkira** [comment]
this is my config
compileSdk 30
buildToolsVersion "30.0.3"

which is available when I compile your lib 1.2.3. but when I upgrade it to 1.4.4 then the ide tells me aar need minCompileSDKVersion 31

**Comment by amberkira** [comment]
gradleVersion:4.1.3
