### ISSUE TITLE
Can I use Balloon for some popupwindow or dialog functionality?

### ISSUE THREAD

**Issue by SaltedFish999** [skydoves/Balloon#326]

**Comment by skydoves** [comment]
Hi @SaltedFish999,
Yes, you can access the `bodyWindow` as the below:

```kotlin
val popupWindow = balloon.bodyWindow
```

public val bodyWindow: PopupWindow

**Comment by SaltedFish999** [comment]
Thank you so much

> Hi @SaltedFish999, Yes, you can access the `bodyWindow` as the below:
> 
> ```kotlin
> val popupWindow = balloon.bodyWindow
> ```
> 
> public val bodyWindow: PopupWindow

Thank you so much, this helped me a lot.
