### ISSUE TITLE
setArrowSize not working

### ISSUE THREAD

**Issue by kkhura** [skydoves/Balloon#33]
I am setting arrow size using factory 
Balloon.Builder(context)
            .setLayout(R.layout.layout)
            .setArrowSize(40)
            .setArrowOrientation(ArrowOrientation.TOP)
            .setArrowPosition(0.5f)
            .setCornerRadius(4f)
            .setBackgroundColor(ContextCompat.getColor(context, R.color.white_20))
            .setDismissWhenTouchOutside(true)
            .setLifecycleOwner(lifecycleOwner)
            .build()

**Comment by skydoves** [comment]
Hi, @kkhura!
It is fixed in the new release [1.1.3](https://github.com/skydoves/Balloon/releases).
Thank you four your issue ;)
