### ISSUE TITLE
After Migrate Library to Latest Version 1.4.5 , Ballon is not showing 

### ISSUE THREAD

**Issue by Maxwell6635** [skydoves/Balloon#332]
**Please complete the following information:**
Previous Library Version : 1.3.4
Library Version : 1.4.5
Affected Device(s) : Sony Xperia XZ Premium G8142 with Android 9
 
**Describe the Bug:**
After creation ballon, and using showAtCenter function , the tooltips wasnt show at specific anchor.

Code Implementation : 

```
fun getTooltipsBalloon(context: Context, tooltipsText: String, arrowOrientation: ArrowOrientation, onBalloonDismissListener: OnBalloonDismissListener): Balloon {
        return getBaseBalloonBuilder(context)
                .setArrowOrientation(arrowOrientation)
                .setText(tooltipsText)
                .setOnBalloonDismissListener(onBalloonDismissListener)
                .build()
    }

private fun getBaseBalloonBuilder(context: Context): Balloon.Builder {
        return Balloon.Builder(context)
                .setArrowSize(12)
                .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
                .setArrowPosition(0.2f)
                .setWidth(200)
                .setHeight(BalloonSizeSpec.WRAP)
                .setTextSize(14f)
                .setCornerRadius(6f)
                .setPadding(16)
                .setTextColor(ContextCompat.getColor(context, R.color.white))
                .setTextIsHtml(true)
                .setMarginLeft(16)
                .setTextGravity(Gravity.START)
                .setTextTypeface(Utils.getCustomTypeface(context, ConstantsKt.FONT.RALEWAY.REGULAR))
                .setBackgroundColor(ContextCompat.getColor(context, R.color.red2))
                .setBalloonAnimation(BalloonAnimation.FADE)
                .setDismissWhenClicked(true)
                .setAutoDismissDuration(5000L)
    }

    toolTipBalloon = TooltipsUtils.getTooltipsBalloon(
                        context,
                        formConfigList[position].tooltip!!,
                        ArrowOrientation.TOP
                    ) {
                        toolTipBalloon?.dismiss()
                    }
                    toolTipBalloon?.showAtCenter(holder.getBalloonAnchor())
```

**Expected Behavior:**
The tooltips should show above or top of the view.

**Comment by skydoves** [comment]
Hi, you can display the balloon before inflating your views.
Try the codes below:

```kotlin
holder.getBalloonAnchor().showAtCenter(toolTipBalloon) // use showAtCenter extension instead of the function.
```

or 

```kotlin
holder.getBalloonAnchor().post {
  // show your balloon
}
```

**Comment by chintanrparmar** [comment]
val balloon = Balloon.Builder(this)
                .setLayout(R.layout.custom_profile_tooltip)
//                .setAutoDismissDuration(10000L)
                .setArrowOrientation(ArrowOrientation.BOTTOM)
                .setBackgroundColor(ContextCompat.getColor(this, R.color.tooltip_bg))
                .setBalloonAnimation(BalloonAnimation.FADE)
                .setDismissWhenTouchOutside(false)
                .setArrowPosition(0.85f)
                .setArrowTopPadding(5)
                .setCornerRadius(15f)
                .setBalloonHighlightAnimation(BalloonHighlightAnimation.SHAKE)
                .setLifecycleOwner(this)
                .build()
            balloon.setOnBalloonClickListener {
                balloon.dismiss()
                prefManager.setProfileToolTipStatus(true)
            }
            balloon.showAlignTop(activityHomeBinding.activityHomeBottomNavigation, 230, -5)

**Comment by skydoves** [comment]
Hi @chintanrparmar, please try to change to `showAlignTop` with the below:

```kotlin
activityHomeBinding.activityHomeBottomNavigation.showAlignTop(balloon, 230, -5)
```

Or use the `post` function as I mentioned above.
Thanks.

**Comment by skydoves** [comment]
Hey all, please re-open this issue if you face it again. Thanks!
