### ISSUE TITLE
DismissWhenLifecycleOnPause causes sequential balloon to show up when the life cycle owner is paused.

### ISSUE THREAD

**Issue by ozaneb** [skydoves/Balloon#337]
**Please complete the following information:**
- Library Version : 1.4.5
- Affected Device(s) Samsung Galaxy S10 Lite Android 12 and all the other devices i tested with
 
**Describe the Bug:**

This bug happens when there are balloons that should show up sequentially and `dissmissWhenLifecycleOnPause` is set to `true` for each of them.  The next balloon shows up when the current balloon is dismissed due to the lifecycle owner's on pause event.

**Expected Behavior:**

The next balloon should not show up if the current one is dismissed due to the lifecycle owner's on pause event.

Here is the code I use to build a balloon

```    val builder = Balloon.Builder(context)
        .setWidth(BalloonSizeSpec.WRAP)
        .setMaxWidth(300)
        .setHeight(BalloonSizeSpec.WRAP)
        .setBackgroundColor(resources.getColor(R.color.white_a90))
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .setArrowSize(10)
        .setArrowPosition(0.5f)
        .setCornerRadius(12f)
        .setMargin(8)
        .setLayout(R.layout.my_balloon_layout)
        .setArrowColorMatchBalloon(true)
        .setBalloonAnimation(BalloonAnimation.OVERSHOOT)
        .setLifecycleOwner(lifecycleOwner)
        .setDismissWhenClicked(true)
        .setDismissWhenTouchOutside(false)
        .setDismissWhenLifecycleOnPause(true)
```

and this is how I add the sequential balloons:

```
 it.balloon.relayShowAlign(
    nextBalloon.align,
    nextBalloon.balloon,
    nextBalloon.view,
    nextBalloon.xOff,
    nextBalloon.yOff
)
```

**Comment by skydoves** [comment]
Hey, @ozaneb . I'm so sorry for the delayed response. In the next release, you'll able to use a very nice relay function with Coroutines like the example below:

```kotlin
balloon.awaitAlignTop(anchor)
balloon.awaitAlignBottom(anchor)
..
```

So it will be much more convenient to manage the sequence of balloons regardless of the lifecycle. Thank you for filing this issue!

**Comment by skydoves** [comment]
I think this issue should be fixed on your side, not on the library side. The `dissmissWhenLifecycleOnPause` property should be `false` or you may need to continue Balloons by using [SavedStateHandle](https://developer.android.com/reference/androidx/lifecycle/SavedStateHandle).
