### ISSUE TITLE
Setting a time out to show a balloon again

### ISSUE THREAD

**Issue by ozaneb** [skydoves/Balloon#339]
I think it would be useful to set a time out, after which the balloon can be shown again. For example in my case, I want to show a balloon 3 times in total, but I want to show the next one after 1 hour has passed and so on.

**Comment by skydoves** [comment]
Hi @ozaneb, thanks for suggesting this issue.
Unfortunately, I don't have any plans for supporting time-relevant features for now.
But I'm considering adding a similar feature to [Only](https://github.com/skydoves/only) in the future. Thanks!
