### ISSUE TITLE
Create balloon without highlight keeping overlay

### ISSUE THREAD

**Issue by mutual-arildo** [skydoves/Balloon#340]
**Is your feature request related to a problem?**

I need to be able to create a balloon on a photo (entire screen) not highlighting anything and keeping the overlay. It's like creating a balloon for a specific point (x, y) on the screen, thus no need for highlight because it's related to the entire photo and not to a specific view, like a button.

**Describe the solution you'd like:**

Be able to create a balloon to a specific point (x, y), without highlight keeping overlay.

**Describe alternatives you've considered:**

None, because it seems it's not possible disabling the highlight. Right now when I try to do it, I create the balloon from the photo (entire screen) then the entire screen is highlighted and overlay is out of bounds and doesn't show. I want no highlight, the balloon with overlay on the rest of the screen.

**Comment by skydoves** [comment]
Since version `1.4.6`, you can use the `BalloonOverlayEmpty` for preventing drawing highlights on the overview.

```kotlin
.setOverlayShape(BalloonOverlayEmpty)
```
