### ISSUE TITLE
App crash - OutOfMemoryError

### ISSUE THREAD

**Issue by mutual-arildo** [skydoves/Balloon#341]
**Please complete the following information:**
- Library Version: v1.4.5
- Affected Device(s): Samsung devices with Android 12
 
**Describe the Bug:**

It seems to be crashing in the inner code of the library when showing the balloon.

``

java.lang.reflect.Constructor.newInstance0 (Constructor.java)
java.lang.reflect.Constructor.newInstance (Constructor.java:343)
android.view.LayoutInflater.createView (LayoutInflater.java:858)
android.view.LayoutInflater.createView (LayoutInflater.java:780)
com.android.internal.policy.PhoneLayoutInflater.onCreateView (PhoneLayoutInflater.java:58)
android.view.LayoutInflater.onCreateView (LayoutInflater.java:934)
android.view.LayoutInflater.onCreateView (LayoutInflater.java:954)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:1008)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:965)
android.view.LayoutInflater.inflate (LayoutInflater.java:663)
android.view.LayoutInflater.inflate (LayoutInflater.java:538)
com.skydoves.balloon.databinding.BalloonLayoutBodyBinding.inflate (BalloonLayoutBodyBinding.java:69)
com.skydoves.balloon.Balloon.<init> (Balloon.kt:144)
com.skydoves.balloon.Balloon.<init>
com.skydoves.balloon.Balloon$Builder.build (Balloon.kt:2629)
com.mutualapp.helper.mutualcommonandnetworking.ui.TooltipExtensionsKt.showTooltip (TooltipExtensions.kt:103)
com.mutualapp.helper.mutualcommonandnetworking.ui.TooltipExtensionsKt.showTooltip$default (TooltipExtensions.kt:65)
com.mutualapp.home.HomeFragment.showTapHoldCoachmark (HomeFragment.kt:840)
com.mutualapp.home.HomeFragment.onItemSwipedPhotos$lambda-87 (HomeFragment.kt:1438)
com.mutualapp.home.HomeFragment.$r8$lambda$y1-oelNUDR9BaMhB3IG5z24jSK4
com.mutualapp.home.HomeFragment$$ExternalSyntheticLambda61.run (Unknown Source:2)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)
android.app.ActivityThread.main (ActivityThread.java:8641)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:567)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1133)

**Caused by java.lang.OutOfMemoryError
Failed to allocate a 16 byte allocation with 92952 free bytes and 90KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.**
libcore.util.NativeAllocationRegistry.registerNativeAllocation (NativeAllocationRegistry.java:269)
android.graphics.RenderNode.<init> (RenderNode.java:227)
android.graphics.RenderNode.create (RenderNode.java:242)
android.view.View.<init> (View.java:5570)
android.view.View.<init> (View.java:5742)
android.view.ViewGroup.<init> (ViewGroup.java:720)
android.widget.FrameLayout.<init> (FrameLayout.java:99)
android.widget.FrameLayout.<init> (FrameLayout.java:94)
android.widget.FrameLayout.<init> (FrameLayout.java:89)
java.lang.reflect.Constructor.newInstance0 (Constructor.java)
java.lang.reflect.Constructor.newInstance (Constructor.java:343)
android.view.LayoutInflater.createView (LayoutInflater.java:858)
android.view.LayoutInflater.createView (LayoutInflater.java:780)
com.android.internal.policy.PhoneLayoutInflater.onCreateView (PhoneLayoutInflater.java:58)
android.view.LayoutInflater.onCreateView (LayoutInflater.java:934)
android.view.LayoutInflater.onCreateView (LayoutInflater.java:954)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:1008)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:965)
android.view.LayoutInflater.inflate (LayoutInflater.java:663)
android.view.LayoutInflater.inflate (LayoutInflater.java:538)
com.skydoves.balloon.databinding.BalloonLayoutBodyBinding.inflate (BalloonLayoutBodyBinding.java:69)
com.skydoves.balloon.Balloon.<init> (Balloon.kt:144)
com.skydoves.balloon.Balloon.<init>
com.skydoves.balloon.Balloon$Builder.build (Balloon.kt:2629)
com.mutualapp.helper.mutualcommonandnetworking.ui.TooltipExtensionsKt.showTooltip (TooltipExtensions.kt:103)
com.mutualapp.helper.mutualcommonandnetworking.ui.TooltipExtensionsKt.showTooltip$default (TooltipExtensions.kt:65)
com.mutualapp.home.HomeFragment.showTapHoldCoachmark (HomeFragment.kt:840)
com.mutualapp.home.HomeFragment.onItemSwipedPhotos$lambda-87 (HomeFragment.kt:1438)
com.mutualapp.home.HomeFragment.$r8$lambda$y1-oelNUDR9BaMhB3IG5z24jSK4
com.mutualapp.home.HomeFragment$$ExternalSyntheticLambda61.run (Unknown Source:2)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)
android.app.ActivityThread.main (ActivityThread.java:8641)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:567)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1133)
``

**Expected Behavior:**

Do not crash.

**Comment by skydoves** [comment]
Hi, can you share the custom XML layout and the implementation of the builder class?

**Comment by mutual-arildo** [comment]
> Hi, can you share the custom XML layout and the implementation of the builder class?

@skydoves please check following:
```
fun View.showTooltip(tooltip: Tooltip,
                     lifecycleOwner: LifecycleOwner? = null,
                     overlayShape: BalloonOverlayShape = BalloonOverlayRoundRect(12f, 12f),
                     arrowOrientation: ArrowOrientation = ArrowOrientation.TOP,
                     preferenceEnabled: Boolean = true,
                     offsetTop: Point? = null,
                     offsetBottom: Point? = null,
                     offsetLeft: Point? = null,
                     offsetRight: Point? = null,
                     onDismissListener: (() -> Unit)? = null) {
    if (isVisible) {
        Timber.d("showTooltip(): tooltip = $tooltip")

        val balloon = tooltip.balloon ?: createBalloon(context) {
            setWidthRatio(.65f)
            setHeight(BalloonSizeSpec.WRAP)
            setCornerRadiusResource(R.dimen.default_tooltip_corner_radius)
            setText(tooltip.text)
            setTextSize(14f)
            setTextColor(tooltip.textColor)
            setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
            setArrowOrientation(arrowOrientation)
            setArrowSize(10)
            setArrowPosition(0.5f)
            setBackgroundColor(tooltip.backgroundColor)
            setArrowColor(tooltip.backgroundColor)
            setOverlayShape(overlayShape)
            setOverlayPadding(6f)
            setOverlayColorResource(R.color.black_scrim_color)
            setIsVisibleOverlay(true)
            setFocusable(false)
            setPadding(12)
            setCornerRadius(8f)
            setBalloonAnimation(BalloonAnimation.FADE)
            setLifecycleOwner(lifecycleOwner)
            ResourcesCompat.getFont(context, R.font.lato_regular)?.let {
                setTextTypeface(it)
            }
            if (preferenceEnabled) {
                setPreferenceName(tooltip.id)
            }
            build()
        }
        onDismissListener?.let {
            balloon.setOnBalloonDismissListener(it)
        }
        offsetTop?.let {
            showAlignTop(balloon, it.x, it.y)
        } ?: offsetBottom?.let {
            showAlignBottom(balloon, it.x, it.y)
        } ?: offsetLeft?.let {
            showAlignLeft(balloon, it.x, it.y)
        } ?: offsetRight?.let {
            showAlignRight(balloon, it.x, it.y)
        } ?: run {
            show(balloon, arrowOrientation)
        }
        tooltip.balloon = balloon
    }
}

private fun Context.createTooltipView(tooltip: Tooltip): View =
    inflate(R.layout.tooltip).also {
        it.findViewById<TextView>(R.id.title).apply {
            setTextColor(tooltip.textColor)
            text = tooltip.text
            gravity = tooltip.textGravity
        }

        it.findViewById<TextView>(R.id.subtitle).apply {
            setTextColor(tooltip.textColor)
            text = tooltip.confirmText
            gravity = tooltip.textGravity
            isGone = tooltip.confirmText.isNullOrEmpty()
        }
    }

private fun Context.inflate(@LayoutRes layoutRes: Int): View =
    LayoutInflater.from(this).inflate(layoutRes, null, false)

private fun View.show(balloon: Balloon, arrowOrientation: ArrowOrientation) {
    post {
        if (isActivityFinishing) {
            return@post
        }

        when (arrowOrientation) {
            ArrowOrientation.LEFT -> showAlignRight(balloon)
            ArrowOrientation.RIGHT -> showAlignLeft(balloon)
            ArrowOrientation.TOP -> showAlignBottom(balloon)
            ArrowOrientation.BOTTOM -> showAlignTop(balloon)
        }
    }
}
```

**Comment by skydoves** [comment]
As your report, the OutOfMemoryError occurred during inflating the body view of the balloon.
I guess you're using kind of huge memory resource in your XML layouts such as image, font, or something.
I would recommend building your project without any heavy resources that I mentioned above.

**Comment by skydoves** [comment]
For now, I will close this issue. Please re-open this issue if you keep facing the same issue. Thanks!
