### ISSUE TITLE
Separate animations for show and dismiss

### ISSUE THREAD

**Issue by massivemadness** [skydoves/Balloon#348]
Provide different animations for show and dismiss. As example, I would like to use `BalloonAnimation.OVERSHOOT` animation when the balloon is showing up, but I want to use `BalloonAnimation.FADE` animation when the user dismisses it

**Describe the solution you'd like:**

```kotlin
.setBalloonAnimation(value: BalloonAnimation) // current behavior, both show and dismiss
.setBalloonShowAnimation(value: BalloonAnimation)
.setBalloonDismissAnimation(value: BalloonAnimation)
```

**Comment by skydoves** [comment]
Hey @massivemadness, sorry for the late response.
For now, you can achieve this by adding your custom animation like the below:

```xml
  <style name="My_Balloon_Animation">
    <item name="android:windowEnterAnimation">@anim/balloon_show_up_center</item>
    <item name="android:windowExitAnimation">@anim/balloon_show_down_center</item>
  </style>
```

```kotlin
balloon.setBalloonAnimationStyle(R.style.My_Balloon_Animation)
```

But let me consider if there's a great way to achieve what you've proposed. 
Thanks!
