### ISSUE TITLE
Error building the project after adding lib dependency

### ISSUE THREAD

**Issue by LMituiti** [skydoves/Balloon#361]
**Please complete the following information:**
- Library Version 1.4.7 (also tested with 1.4.5 and 1.4.6)
- Affected Device(s): None since I can't even build the project
 
**Describe the Bug:**

I can't build my project after adding the lib to the dependencies.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> Android resource linking failed
>      C:\Users\letrindadem\.gradle\caches\transforms-3\be22925a905b66686face568a15b1fe3\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

Here are some info about my project:
Android Gradle Plugin Version 4.0.2
Gradle Version 6.8
compileSdkVersion 31
minSdkVersion 23
targetSdkVersion 30

I've tried adding
`implementation "androidx.core:core-ktx:1.7.0"` and version 1.6.0 but the error persists.
Also tested adding:
```
configurations.all {
   resolutionStrategy {
        force 'androidx.core:core-ktx:1.7.0'
    }
}
```

**Expected Behavior:**

Expected the project to at least build after adding the library depency so that I can test and use it...

**Comment by skydoves** [comment]
Hey, make sure your AGP version is `7.1.2` and the Gradle version is `7.4.2`, probably the compile SDK must be 32 at least. This is not a library issue, so I will close this for now.
