### ISSUE TITLE
Arrow unable to reach the edge with ArrowPositionRules.ALIGN_ANCHOR

### ISSUE THREAD

**Issue by GC-Xi** [skydoves/Balloon#363]
**Please complete the following information:**
- Library Version [e.g. v1.4.7]
- Affected Device(s) [OnePlus 6T with Android 11, OnePlus 8T with Android 12]
 
**Describe the Bug:**
Issue 1
When using ArrowPositionRules.ALIGN_ANCHOR, the arrow cannot get close to the edge of the ballon with `setArrowPosition(1f)` or `setArrowPosition(0f)`.

Issue 2
When using ArrowPositionRules.ALIGN_ANCHOR, the left and right padding aren't even with `setArrowPosition(1f)` and `setArrowPosition(0f)`.

![Screenshot_20220907-181117](https://user-images.githubusercontent.com/34244941/188853072-29a17018-1139-4886-bf67-4169472ac712.jpg)

**Expected Behavior:**
1. Have an anchor view with layout_width="match_parent"
2. Create a balloon with `setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)` and `setArrowPosition(0f)`
3. Show the balloon using `showAlignTop()` and position it at the left more edge

Expect: the arrow should be very close to the edge of the balloon.
Actual: the is a large space between the arrow and the edge of the balloon.

Please see https://github.com/GC-Xi/ArrowPosition as example.

**Comment by skydoves** [comment]
Hey, this is expected behavior. You shouldn't use the `ArrowPositionRules` and set the arrow position explicitly, such as `setArrowPosition`. The `setArrowPosition` method fixes arrow position as a constant, and it's the highest criterion to decide arrow position.

**Comment by GC-Xi** [comment]
Hi @skydoves , 

Actually, it has been working nicely expect it being on the edge.

https://user-images.githubusercontent.com/34244941/188890675-8bde8e24-6cf7-4eb2-b3dc-1e74d6abf5ba.mp4

If you look at the video, the arrow points to the exact location except when it gets to the very edge where the arrow won't travel anymore.

In this case, I used the bottom RecyclerView as the anchor and used `setArrowPosition(position / screen width)` and `showAlignTop(viewBinding.bottomThumbnailsBar, calculatedOffset)`. It would be perfect only if the arrow can travel a bit further to the edge.

**Comment by skydoves** [comment]
Hey @GC-Xi, I'm sorry for the very delayed response. I'm not sure if this solution is still helpful to you, but here is a very simply way to resolve this issue:

```kotlin
.setArrowAlignAnchorPaddingRatio(1.0f)
```

Thanks for reporting this issue and great to know this great use cases!

**Comment by skydoves** [comment]
Hey @GC-Xi, I'm sorry for the very delayed response. I'm not sure if this solution is still helpful to you, but here is a very simply way to resolve this issue:

```kotlin
.setArrowAlignAnchorPaddingRatio(1.0f)
```

Thanks for reporting this issue and great to know this great use cases!
