### ISSUE TITLE
Initialize arrow crashes while trying to get the color from the balloon

### ISSUE THREAD

**Issue by ozaneb** [skydoves/Balloon#365]
**Please complete the following information:**
- Library Version: 1.4.5

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/17740560/191002279-7b7ffb9e-dbd2-4d64-a638-43590244fa4d.png">

Hello @skydoves, our app with Balloon version 1.4.5 suffers from a crash that occurs when the app is in background. I could not reproduce the error,  do you have any idea why would this happen and how could we fix this crash?

**Comment by ozaneb** [comment]
I will try setting the arrow color manually instead of matching the balloon color. I will keep you posted.

**Comment by ozaneb** [comment]
related, but a different crash.

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/17740560/191447235-eb10d6bd-dac4-4af4-ac1f-0acbd214b9ec.png">

**Comment by skydoves** [comment]
Hey @ozaneb, thank you for reporting this issue. I'm wondering if you use the `arrowColorMatchBalloon` attribute to build your balloon.

**Comment by ozaneb** [comment]
Hi, yes I was using as `setArrowColorMatchBalloon(true)`.

**Comment by skydoves** [comment]
Hi @ozaneb, can I see your `Balloon.Builder` class? Thanks!

**Comment by ozaneb** [comment]
the relevant part was like this
 
 ```    val builder = Balloon.Builder(context)
        .setWidth(BalloonSizeSpec.WRAP)
        .setMinWidth(216)
        .setMaxWidth(300)
        .setHeight(BalloonSizeSpec.WRAP)
        .setBackgroundColor(resources.getColor(R.color.white_a90))
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .setArrowSize(10)
        .setArrowPosition(0.5f)
        .setCornerRadius(8f)
        .setMargin(8)
        .setLayout(R.layout.my_balloon_layout)
        .setArrowColorMatchBalloon(true)
        .setBalloonAnimation(BalloonAnimation.OVERSHOOT)
        .setLifecycleOwner(lifecycleOwner)
        .setDismissWhenClicked(true)
        .setDismissWhenTouchOutside(false)
        .setDismissWhenLifecycleOnPause(dismissOnPause)```

after the change I made it became 

```
    val builder = Balloon.Builder(context)
        .setWidth(BalloonSizeSpec.WRAP)
        .setMinWidth(216)
        .setMaxWidth(300)
        .setHeight(BalloonSizeSpec.WRAP)
        .setBackgroundColor(resources.getColor(R.color.white_a90))
        .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        .setArrowSize(10)
        .setArrowPosition(0.5f)
        .setCornerRadius(8f)
        .setMargin(8)
        .setLayout(R.layout.my_balloon_layout)
        .setArrowColorMatchBalloon(false)
        .setArrowColor(resources.getColor(R.color.white_a90))
        .setBalloonAnimation(BalloonAnimation.OVERSHOOT)
        .setLifecycleOwner(lifecycleOwner)
        .setDismissWhenClicked(true)
        .setDismissWhenTouchOutside(false)
        .setDismissWhenLifecycleOnPause(dismissOnPause)```

As far as I understand from your code, if I set `arrowColorMatchBalloon` to false, the operation that causes the crash will not run.

**Comment by skydoves** [comment]
@ozaneb Sorry for the late response. This issue happens while creating a bitmap image that matches the arrow's color. Still, I don't know if I can resolve this error from my side because an old device assigns low memory capabilities. 

If you still face this issue on old devices, you may consider adding `android:largeHeap="true"`, but I don't recommend it. For now, there's nothing I can do this from my side; I'm closing this issue. Thank you!
