### ISSUE TITLE
ClassNotFoundException on App StartUp

### ISSUE THREAD

**Issue by sdoward** [skydoves/Balloon#37]
- Library Version [e.g. v1.1.4]
- Affected Device(s) : Emulator]
 
**Describe the Bug:**

`AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.AppCompatImageView" `

I presume this is caused by your dependency on the alpha version of the appcompat lib. Is it possible to use the stable version?

**Expected Behavior:**
App doesn't crash

**Comment by skydoves** [comment]
@sdoward 
Hi, could you let me know your project's `material` and `appcompat` dependency version?

**Comment by sdoward** [comment]
Both are `1.1.0`

For anybody experiencing the same issue the fix is to exclude the libs dependency..

```
    implementation(Libraries.balloon)  {
        exclude("androidx.appcompat", "appcompat")
    }
```

**Comment by skydoves** [comment]
@sdoward 
Sorry for the late reply.
The new version [1.1.6](https://github.com/skydoves/Balloon/releases/tag/1.1.6) is released and you can check it!
Thank you for your issue :)
