### ISSUE TITLE
Custom view + elevation = layout size bug

### ISSUE THREAD

**Issue by Stan-K0** [skydoves/Balloon#370]
- Library Version: 1.4.3
- Affected Device(s): any
 
Library calculates the size of wrapper Balloon incorrectly if use custom view and elevation has been set. 
At least this is true for the width but I'm pretty sure the same is true for height. 
In my case the width of the custom view is fixed and its 180dps and I've set balloon elevation to 4dps. So if I set balloon width to 180dps then a right side of my view is cutted by elevation x2 dps. If I set balloon width to WRAP_CONTENT balloon squeezes my custom view to 172dps by the width (180 - elevation x2). 
The quick workaround is to set balloon with to 188dp e.g. my custom view is 180dps and elevation is 4dps.

**Expected Behavior:**

Balloon view should count elevation like layout_margin and extend its size by elevation*2 dps since elevation works like view edges margin. Since there is a method setWidthResource() accepting a value from dimens.xml and this value expected to be shared for layout and for the balloon setup.

**Comment by skydoves** [comment]
Hi @Stan-K0, sorry for the late response. I think Android's measuring view system doesn't include the elevation value. Also, it's quite expensive to trace all view hierarchies to trace view elevations in your custom view. In this case, I would recommend you give a particular width/height size as you said, or you can add the padding size according to the elevation sizes. Thanks!
