### ISSUE TITLE
`VectorTextView`'s  `balloon_drawableTintColor` using the resource id instead a color int.

### ISSUE THREAD

**Issue by saulmm2** [skydoves/Balloon#373]
**Please complete the following information:**
- Library Version 1.4.7
 
 
**Describe the Bug:**

When using a layout file for inflating a balloon, which contains a `VectorTextView` specifying the tint color of the icon as:

```xml
<?xml version="1.0" encoding="utf-8"?>
<com.skydoves.balloon.vectortext.VectorTextView 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    [...]
    app:balloon_drawableEnd="@drawable/ic_close_regular"
    app:balloon_drawableTintColor="@color/gray5"
    />
```

```
<color name="gray5">#4A4A4A</color>
```

The actual color used is not the color int, but the resource id. Resulting in an icon wrongly tinted.

<img width="78" alt="image" src="https://user-images.githubusercontent.com/80626152/196730227-29f702b6-8a13-4ef9-8915-55094dac2cba.png">

https://github.com/skydoves/Balloon/blob/main/balloon/src/main/kotlin/com/skydoves/balloon/extensions/DrawableExtension.kt#L34

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/80626152/196728789-50013e21-afe4-4e59-8385-b13690046e11.png">

<img width="833" alt="image" src="https://user-images.githubusercontent.com/80626152/196727974-a22cf7c8-9720-4306-bc35-ae06a529f967.png">

<img width="296" alt="image" src="https://user-images.githubusercontent.com/80626152/196730881-e43667ab-2dfb-4bba-a05d-d16f798d0c1b.png">

**Expected Behavior:**

The resourceId should be resolved into the color int. 

i.e for the color `#4A4A4A` it should resolve to `-11908534` not  to `2131099991` which is the resource id reference.

**Comment by skydoves** [comment]
Hey @saulmm2, Thanks for reporting this issue! This will be fixed in the next release.
