### ISSUE TITLE
Sequential balloons with ability to go back and forth, and to show more then one View as highlighted

### ISSUE THREAD

**Issue by chaimgross** [skydoves/Balloon#377]
As a developer I would like to be able to use the lib to display an intro for the app first user, where I highlight different parts of home page. I would like to seamlessly go between highlighting  different components (without showing the Home Screen in between highlights) and would like the ability for user to go back to previous balloon. I also would like the ability to highlight multiple components simultaneously. 
I tried managing myself and not using the relay (because with relay can't highlight more then one item, and can't go back), but between dismissing one ballon and showing next the Home Screen flashes and does not look good. 
Any ideas or recommendations would be appreciated.

**Comment by skydoves** [comment]
Hey, @chaimgross. I'm so sorry for the delayed response. In the next release, you'll able to use a very nice relay function with Coroutines like the example below:

```kotlin
balloon.awaitAlignTop(anchor)
balloon.awaitAlignBottom(anchor)
..
```

Thank you for filing this issue!

**Comment by skydoves** [comment]
The new version 1.6.0 has been released, and you'll be able to achieve this by using `await__` methods. Thanks for reporting this issue!
