### ISSUE TITLE
How to use a Balloon inside a RecyclerView item?

### ISSUE THREAD

**Issue by gcocce** [skydoves/Balloon#383]
<div type='discussions-op-text'>

## How to use a Balloon inside a RecyclerView item?

Tried creating a balloon inside the ViewHolder in different ways with no visible effect.

```
        val balloon = Balloon.Builder(ItemView.context)
            .setWidthRatio(1.0f)
            .setHeight(BalloonSizeSpec.WRAP)
            .setText("Edit your profile here!")
            .setTextSize(15f)
            .setArrowPositionRules(ArrowPositionRules.ALIGN_BALLOON)
            .setArrowSize(10)
            .setElevation(4)
            .setArrowPosition(0.5f)
            .setPadding(12)
            .setCornerRadius(8f)
            .setDismissWhenClicked(true)
            .setDismissWhenTouchOutside(false)
            .setFocusable(true)
            .setBalloonAnimation(BalloonAnimation.NONE)
            //.setLifecycleOwner(ItemView.findViewTreeLifecycleOwner())
            .build()
```

Also tried next one with the lifecycle of the fragment containing the RecyclverView

`val balloon by lazy {  BalloonUtils.getEditBalloon(context, lifecycleOwner) }`

After one of those tried different variations of showAlign inside onBindViewHolder with no visible effect.

`holder.balloon.showAlignRight(holder.imageView)`

## So, Mandalorians, which is the way?

</div>

**Comment by skydoves** [comment]
Hey @gcocce, please check out the [sample code](https://github.com/skydoves/Balloon/blob/main/app/src/main/kotlin/com/skydoves/balloondemo/recycler/SampleAdapter.kt#L53).
