### ISSUE TITLE
Overlay not moving

### ISSUE THREAD

**Issue by BlueCobold** [skydoves/Balloon#384]
**Please complete the following information:**
- Library Version v1.4.7
- Affected Device(s) - Nexus 5X
 
When using the overlay and showing a balloon on a scrollable item via long-tap, the item/scrollview can still be moved and the balloon moves along, but the overlay stays static.
In the screenshot, you can see the balloon was shown via long-tap and the finger not released, but moved a little bit to the left.

<img width="281" alt="image" src="https://user-images.githubusercontent.com/4488101/207603133-9c50ae39-d4c5-4d34-8d9e-146122e32771.png">

**Expected Behavior:**

Either
1) The scroll-/touch is being cancelled, so the underlying element stops moving
or
2) The overlay moves along with the shown item

**Comment by skydoves** [comment]
Hey @BlueCobold, thanks for reporting this issue. I would not recommend building this kind of UI/UX system. The main reason is tracing the absolute x, and y positions of the movable item on RecyclerView and drawing the entire overlay bitmap following the item requires really expensive costs. Especially, large screen devices, such as tablet requires much more resources to achieve that. I can research this when I have a moment but don't expect so much. Thanks!

**Comment by BlueCobold** [comment]
@skydoves Well, for myself, I blocked the scrolling until the balloon gets closed, because that's what I find more logical. However, needing custom code around this, feels just wrong.

**Comment by skydoves** [comment]
@BlueCobold Thanks for sharing your experience! Anyway, I'm closing this issue because I don't have additional plans for this right now. If I update this, I will let you know. Thanks!
