### ISSUE TITLE
Unable to show custom layout

### ISSUE THREAD

**Issue by shahwaiz90** [skydoves/Balloon#392]
**Please complete the following information:**
- Library Version v1.4.8
- Affected Device(s) [RedMi 9A - Android 10]
 
**Describe the Bug:**

I try to add the custom layout but it shown black screen and doesn't load my custom layout.

**Expected Behavior:**

Custom layout should be shown in the tooltip.

My Code:

```
class CustomBalloon : Balloon.Factory() {
    override fun create(context: Context, lifecycle: LifecycleOwner?): Balloon {
        return createBalloon(context) {
                setLayout(R.layout.company_registeration)
                .setArrowSize(10)
                .setArrowOrientation(ArrowOrientation.TOP)
                .setArrowPosition(0.5f)
                .setWidthRatio(0.55f)
                .setHeight(250)
                .setCornerRadius(4f)
                .setBackgroundColor(ContextCompat.getColor(context, R.color.black))
                .setBalloonAnimation(BalloonAnimation.CIRCULAR)
                .setLifecycleOwner(lifecycleOwner)
                .build()
        }
    }
}
```

**Expected Result (my custom layout xml):**

<img width="313" alt="Screenshot 2022-12-25 at 7 59 53 PM" src="https://user-images.githubusercontent.com/410180/209476383-9f6acb0b-6302-404e-a7dd-4eee5a406d9b.png">

**Current Behaviour:**
<img width="335" alt="Screenshot 2022-12-25 at 7 59 08 PM" src="https://user-images.githubusercontent.com/410180/209476306-81b92da5-cd87-4d4e-84df-60cf90a51bf6.png">

**Comment by skydoves** [comment]
Hey @shahwaiz90, could you share the details of your custom layout? And you should remove all dots and `.build()` if you create the balloon inside of the `createBalloon ` extension:

```kotlin
 return createBalloon(context) {
                setLayout(R.layout.company_registeration)
                setArrowSize(10)
                setArrowOrientation(ArrowOrien ..
```
