### ISSUE TITLE
setArrowOrientationRules(ArrowOrientationRules.ALIGN_ANCHOR) does not work on a custom layout.

### ISSUE THREAD

**Issue by MKadykov** [skydoves/Balloon#397]
**Please complete the following information:**
- Library Version 1.4.8
- Affected Device(s) Huawei P20
 
**Describe the Bug:**

Maybe I'm wrong, but I understand that when I set ArrowOrientationRules.ALIGN_ANCHOR, the arrow should automatically turn towards the "anchor", is that right? At the same time, setArrowOrientation should either be omitted or ignored. But, in this case, I always have an arrow at the bottom, although, the anchor object is located on the right.

**Comment by skydoves** [comment]
Hey @MKadykov, could you share any screenshots or the layouts that should be shown with the balloon? I guess the size of your anchor view is already huge so the balloon keeps showing on the top side. And in most cases, if the layout is not dynamically changed, I would recommend you fix the position of the arrow.

**Comment by MKadykov** [comment]
Thanks for the quick response!
Yes, I had to set a fixed arrow position. But this position is different for portrait and landscape orientation, so I had to write additional code. But it's not scary.
But I'm just wondering why setArrowOrientationRules(ArrowOrientationRules.ALIGN_ANCHOR) doesn't work for me. This is how it should look like (the position of the arrow is fixed)

![image](https://user-images.githubusercontent.com/121889948/210631179-4bbd93e1-6b12-455a-9c7f-96ebc8b68c33.png)

And this is what happens if the arrow is not fixed

![image](https://user-images.githubusercontent.com/121889948/210631291-e1a55ffb-6adc-4ef6-8c8c-bce0324189fc.png)

**Comment by skydoves** [comment]
@MKadykov Thanks for sharing the details! I see this is kind of a bug, so let me fix the issue in the next release. Thank you!

**Comment by MKadykov** [comment]
Hello!

Many thanks for the quick bug fix!
If I may, I would like to give some suggestions about using a custom
layout. The first is when I set a custom layout
.setLayout(R.layout.balloon_view), then when requesting
balloon.getContentView() I expect to get exactly this layout. But I get a
parent layout that is not quite clear, similar to FrameLayout. I understand
that it can be useful in normal use, but then maybe add an additional
function that returns exactly the custom layout?
Secondly, is it possible to expand the description of using a custom layout
with additional examples? For example, what kind of layout do you recommend
as a root layout? I tried using ConstraintLayout, but got big problems with
balloon height. I am currently using LinearLayout, but it is having
problems when placing ImageView and VideoView. Perhaps you have tips and
examples for the correct application of a custom layout?
Thank you in advance!

Sincerely, Michael

пт, 6 янв. 2023 г. в 05:30, Jaewoong Eum ***@***.***>:

**Comment by MKadykov** [comment]
Sorry, but with the upgrade to 1.5.1, the problem has not disappeared. The arrow does not readjust to the anchor, but always at the bottom.

**Comment by engzia** [comment]
Hi, I am facing the same issue. ALIGN_ANCHOR doesn't work with showAlignLeft() and showAlignRight(). My balloon is able to show in the correct side of the anchor but the arrow is always pointing to the bottom.

**Comment by sixtsense** [comment]
Sorry for writing in a closed issue, but this bug indeed is still not fixed. I'm using balloon 1.6.4 and as stated by @engzia showAlignLeft and showAlignRight do not position the arrow correctly.
