### ISSUE TITLE
Usage inside recyclerview item

### ISSUE THREAD

**Issue by Lemedon** [skydoves/Balloon#4]
**Is your feature request related to a problem?**

Hi, I've been struggling with the problem of using your library inside recyclerview item. For example I would like to display tooltip after click on circle avatar image at your sample project. It's popups balloon at different items or sometimes just nothing happens after a click event. My implementation is very simple I've used `showAlignBottom` method inside viewholder.

**Describe the solution you'd like:**

Could you provide some simple solution how to use you library with recyclerview? 

Thanks!

**Comment by skydoves** [comment]
@Lemedon 
Hi, thank you for your interesting!
I wrote some sample codes for explaining to implement balloon tooltips inside viewholder.

Here is a [SampleViewHolder](https://github.com/skydoves/Balloon/blob/master/app/src/main/java/com/skydoves/balloondemo/recycler/SampleViewHolder.kt).

Firstly, declare a balloon property like below.
BalloonUtils is an object class for providing balloon instance.
```kotlin
private val balloon by lazy { BalloonUtils.getProfileBalloonForViewHolder(context(), lifecycleOwner) }
```
And show using `showXX` method.
You can set the itemView or any child views as a target.
```kotlin
balloon.showAlignBottom(itemView)
```
Thank you :)

**Comment by Lemedon** [comment]
Perfect, now works like a charm. Thanks!

**Comment by i-schuetz** [comment]
@skydoves Is it possible to prevent that the tooltip sticks at the top / bottom when scrolling? I'd like it to just scroll out of the screen together with the cell.

**Comment by skydoves** [comment]
@i-schuetz 
Unfortunately, the tooltips can't move once it appears.

**Comment by dharamveer-appyhigh** [comment]
> @Lemedon Hi, thank you for your interest! I wrote some sample codes for explaining to implement balloon tooltips inside viewholder.
> 
> Here is a [SampleViewHolder](https://github.com/skydoves/Balloon/blob/master/app/src/main/java/com/skydoves/balloondemo/recycler/SampleViewHolder.kt).
> 
> Firstly, declare a balloon property like below. BalloonUtils is an object class for providing balloon instance.
> 
> ```kotlin
> private val balloon by lazy { BalloonUtils.getProfileBalloonForViewHolder(context(), lifecycleOwner) }
> ```
> 
> And show using `showXX` method. You can set the itemView or any child views as a target.
> 
> ```kotlin
> balloon.showAlignBottom(itemView)
> ```
> 
> Thank you :)

[SampleViewHolder](https://github.com/skydoves/Balloon/blob/master/app/src/main/java/com/skydoves/balloondemo/recycler/SampleViewHolder.kt) is not accessible.
