### ISSUE TITLE
Option for changing text alignment.

### ISSUE THREAD

**Issue by gavingt** [skydoves/Balloon#41]
The text is always centered in the Balloon without any way to change it. I think left-aligned text looks better for large chunks of text, so I'd like an option to set this.

I've tried doing this with a custom layout, but the text always gets cut off after one line (unless I explicitly set the height, which isn't feasible for me).

EDIT: nevermind, I was able to hack around it:

        TextView textView = balloon.getContentView().findViewById(R.id.balloon_text);
        textView.setGravity(Gravity.LEFT);

**Comment by icarapovic** [comment]
I just opened an enhancement as I needed the same thing. Although it would work I would prefer official API as there is always the possibility that the internal IDs might change in the future and it would break you "hack" if you update the library. As seen that its not hard to do, I would prefer an official method that can basically do the exact thing above to align the text.
