### ISSUE TITLE
setArrowSize doesn't work as expected 

### ISSUE THREAD

**Issue by UmairKhalid786** [skydoves/Balloon#413]
**Please complete the following information:**
- Library Version v1.5.2
- Affected Devices (Android TV 1080p API 31, Pixel 3XL API 28)

**Describe the Bug:**
 
When you set the arrow size using the setArrowSize method and try to align the arrow with the anchor 
setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)

it doesn't align with the anchor 

**Expected Behavior:**
The tooltip arrow should center align even when we try to set the arrow size

**Comment by skydoves** [comment]
Hey @UmairKhalid786, could you expand on this? You titled `setArrowSize doesn't work but the description says `setArrowPositionRules` doesn't work as your expectation.

**Comment by UmairKhalid786** [comment]
Let me explain how **setArrowSize** effects **setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)**

When tooltip size is set, arrow alignment is disturbed 

Code snippet 
`   val balloon = Balloon.Builder(this)
            .setWidthRatio(1.0f)
            .setHeight(BalloonSizeSpec.WRAP)
            .setText("Edit your profile here!")
            .setTextSize(15f)
            .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
            .setArrowSize(30)
            .setPadding(12)
            .setCornerRadius(8f)
            .setBalloonAnimationStyle(R.style.Balloon_Slide_Up_Anim)
            .setLifecycleOwner(this)
            .build()
            
      actionView?.showAsDropDown(balloon)`
      
      **Generates** 

![Screenshot_1674309271](https://user-images.githubusercontent.com/21205138/213870081-cbb16052-0b5e-404d-86ca-1a8830957ffa.png)

**Comment by sigma-stochanskyi** [comment]
Hey, having the same issue, didn't find any way to change size and make anchor work with it. Hope it will be fixed soon!

**Comment by skydoves** [comment]
Hey @UmairKhalid786, this issue has been fixed in the recent release, 1.6.4. Please update your library version, and please reopen this issue if you still face the same problem. Thank you for reporting this issue!
