### ISSUE TITLE
Support for different shape of views.

### ISSUE THREAD

**Issue by humxamoghal** [skydoves/Balloon#414]
### Problem

For now we can only highlight a view shaped as rectangle with or without some rounded corners, circle and oval shape. What if we have a custom view or item shaped as hexagon or shapped as heart or star ?

### Solution

AutoShapeBallon which detemines the anchor view shape and highlight the view according or its shape.

**Comment by skydoves** [comment]
Hey @humxamoghal, for this, you can get the `overlayWindow` property from a balloon instance and set your custom overlay view like the example below:

```kotlin
balloon.overlayWindow.contentView = Your custom overlay view
```

Thanks!
