### ISSUE TITLE
Issue in Bottom Navigation View - I Need to show balloon popup aligned above an bottom navigation item when the application start (without click or select navigation item)

### ISSUE THREAD

**Issue by Elsobkey** [skydoves/Balloon#417]
**Is your feature request related to a problem?**

A clear and concise description of what the problem is.

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

**Comment by Elsobkey** [comment]
I believe that I found  the solution:

 val bottomNavigationMenuView: BottomNavigationMenuView =
            bottomNavView.getChildAt(0) as BottomNavigationMenuView
        val v = bottomNavigationMenuView.getChildAt(0)
        val itemView =  v as BottomNavigationItemView

Then,

balloon.showAlignTop(itemView)

**Comment by skydoves** [comment]
Hey @Elsobkey, you can show a balloon on an anchor view without user actions like the code below:

```kotlin
itemView.showAlignTop(balloon)
```

Thanks!

**Comment by MrSatan** [comment]
i want to do the same , after an event fired from view model , show the balloon on navigation in **jetpack compose**
could you give me a hand

**Comment by Elsobkey** [comment]
@skydoves 
Thanks for this awesome library, appreciate

**Comment by Elsobkey** [comment]
@MrSatan 

You can try to convert my above solution to Jetpack compose

**Comment by MrSatan** [comment]
@Elsobkey i don't know how to get reference to a view in jetpack compose , i guess it is not possible

**Comment by skydoves** [comment]
Hey @MrSatan, I'm not sure how you implemented the bottom navigation in Jetpack Compose. If you're using `BottomAppBar`, you should wrap the `BottomNavigationItem` with the `Balloon` composable function and show up the balloon following your event streams. Check out the [gist](https://gist.github.com/skydoves/c56c73a8a57b9197120abe6da5270e31#file-balloonwindow-kt) about showing & dismissing the balloon following your event states in Jetpack Compose.
