### ISSUE TITLE
Using multiple versions of the Android Gradle plugin(7.1.0, 7.3.1) in the same build is not allowed.

### ISSUE THREAD

**Issue by moslem7342** [skydoves/Balloon#418]
**Please complete the following information:**
- Library Version [e.g. v1.0.0] : 1.4.2
- Affected Device(s) redmi Android 12.
 
**Describe the Bug:**
after adding this library to project , and run app

**Comment by skydoves** [comment]
Hey @moslem7342, could you please provide more information about this? And please rebuild your project after upgrading your Gradle Plugin to `7.3.1` or higher version + Gradle 7.6 (in your gradle wrapper file.)

**Comment by moslem7342** [comment]
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.skydoves:balloon:1.4.2.
     Required by:
         project :app
      > Could not determine whether value 7.1.0 is compatible with value 7.3.1 using AgpVersionCompatibilityRule.
         > Using multiple versions of the Android Gradle plugin(7.1.0, 7.3.1) in the same build is not allowed.

i can't write english good ,sorry
today i use few other library without error , but just after  add implementation 'com.github.skydoves:balloon:1.4.2' to the gradle file
and sync gradle , then run app . this is the error

**Comment by moslem7342** [comment]
thank you 
i copy that from android arsenal
[Balloon](https://android-arsenal.com/details/1/7769)
