### ISSUE TITLE
[Suggestion] Change lifecycle-runtime version to 2.6.0

### ISSUE THREAD

**Issue by CAIOS0922** [skydoves/Balloon#419]
**Please complete the following information:**
- Library Version v1.5.2
 
**Suggestion content:**

Could you please update the version of `androidx.lifecycle:lifecycle-runtime-ktx` to 2.6.0?
Other libraries, such as dagger-hilt, use version 2.6.0, resulting in the following warning.
Probably because the supertype of `DefaultLifecycleObserver` was changed from `FullLifecycleObserver` to `LifecycleObserver`.

![image](https://user-images.githubusercontent.com/56629437/216746678-3fde36fa-5cc3-4441-bac2-46eda405fb37.png)

**Comment by skydoves** [comment]
Hey @CAIOS0922, `2.6.0` is still alpha and Hilt uses `2.5.1` according to maven central: https://mvnrepository.com/artifact/com.google.dagger/hilt-android/2.44.2. Please check out if you're using other unstable libraries.

**Comment by vfurkana** [comment]
2.6.0 is no more alpha and this is still an issue with 2.6.1

**Comment by phazei** [comment]
I just installed this library, been trying to use it, using ext.lifecycle_version = '2.6.1', keeps getting the same error :(
