### ISSUE TITLE
Layout bug with compose when using FlowRow

### ISSUE THREAD

**Issue by vamshinagamalla** [skydoves/Balloon#424]
**Please complete the following information:**
- Library Version 1.5.2
- Affected Device(s): Tested it on Pixel 4 API 33

Hey there, I'm noticing this issue with Balloon in compose, here is the [video](https://streamable.com/wrbqnx)

code: 
   
    val values = remember { mutableStateListOf<String>() }

    val balloonBuilder = rememberBalloonBuilder {
        setArrowSize(10)
        setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        setArrowPosition(0.5f)
        setWidth(BalloonSizeSpec.WRAP)
        setHeight(BalloonSizeSpec.WRAP)
        setBalloonAnimation(BalloonAnimation.NONE)
        setIsVisibleOverlay(true)
        setDismissWhenClicked(true)
    }

    MaterialTheme {
        Column(modifier = Modifier
            .padding(start = 18.dp, end = 18.dp)
            .background(color = Color.White, RoundedCornerShape(6.dp))
            .requiredHeightIn(28.dp, 170.dp)
            .defaultMinSize(minHeight = 44.dp)
            .border(1.dp, Color.LightGray, RoundedCornerShape(6.dp))
            .padding(8.dp)) {
            FlowRow {
                repeat(values.size) { position ->
                    Balloon(
                        builder = balloonBuilder,
                        balloonContent = {
                            Text(text = "message in balloon")
                        }) {
                        Text(
                            text = values[position],
                            modifier = Modifier.clickable {
                                it.showAsDropDown()
                            },
                            color = Color.Black
                        )
                    }
                }
                BasicTextField(value = input.collectAsState().value,
                    modifier = Modifier
                        .wrapContentWidth(),
                    onValueChange = {
                        input.value = it
                        if (it.endsWith(" ")) {
                            values.add(it)
                            input.value = ""
                        }
                    })
            }
        }
    }

**Expected Behavior: Flickering is not good, looks like the fields are rearranging when adding values to FlowRow when I use Balloon**

**Comment by skydoves** [comment]
Hey @vamshinagamalla, sorry for the very delayed response. A new version 1.6.0 has been released, please check it out the new version still produces the same issue. Thank you!

**Comment by skydoves** [comment]
I will close this issue since this issue has been fixed in version 1.6.0. Thanks for reporting this issue!
