### ISSUE TITLE
What is the standard for determining the width of the balloon?

### ISSUE THREAD

**Issue by tkdgusl94** [skydoves/Balloon#426]
**Please complete the following information:**
- Library Version v1.5.2
- Affected Device(s) Samsung Galaxy s22 with Android 13.0
 
**Describe the Bug:**
Hello, I'm using the balloon library well.
I found a problem. The width value of the balloon window depends on the placement of the composable in Row.
I will attach the sample code.

**Sample A**
~~~
@Preview
@Composable
fun Sample() {
    Row(
        modifier = Modifier.fillMaxWidth()
    ) {
        Text(
            text = "what is the difference between A and B?"
        )
        Balloon(
            builder = rememberBalloonBuilder {
                setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
            },
            balloonContent = {
                Text(
                    text = "long text long text long text long text long text long text",
                    color = Color.White,
                )
            }
        ) {
            Image(
                painter = painterResource(id = R.drawable.icon_tooltip),
                contentDescription = null,
                modifier = Modifier
                    .size(24.dp)
                    .clickable {
                        it.showAlignBottom()
                    }
            )
        }
    }
}
~~~

**Sample B**
~~~
@Preview
@Composable
fun Sample() {
    Row(
        modifier = Modifier.fillMaxWidth()
    ) {
        Text(
            text = "what is the difference between A and B?",
            modifier = Modifier
                .weight(1f, false)
        )
        Balloon(
            builder = rememberBalloonBuilder {
                setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
            },
            balloonContent = {
                Text(
                    text = "long text long text long text long text long text long text",
                    color = Color.White,
                )
            }
        ) {
            Image(
                painter = painterResource(id = R.drawable.icon_tooltip),
                contentDescription = null,
                modifier = Modifier
                    .size(24.dp)
                    .clickable {
                        it.showAlignBottom()
                    }
            )
        }
    }
}
~~~

| Sample A | Sample B |
|--|--|
|![KakaoTalk_Photo_2023-02-21-18-44-48 001](https://user-images.githubusercontent.com/46221990/220308639-edb782c0-93e3-47da-8516-dc994e961f2e.jpeg)|![KakaoTalk_Photo_2023-02-21-18-44-48 002](https://user-images.githubusercontent.com/46221990/220308693-e5ae9a38-4a9b-4275-985c-3f4a20faad3b.jpeg)|

If you add weight to the text modifier, this is how you make the difference. I don't understand how this works.
I would really appreciate your help!

**Expected Behavior:**
A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Hey @tkdgusl94 @Monabr @mikescamell guys, sorry for the very delayed response.

A new version 1.6.0 has been released, please check it out the new version still produces the same issue. Thank you!

**Comment by skydoves** [comment]
I'm closing this issue since the new release includes fixes. If you still face the same problem in version 1.6.0, please reopen this thread. Thanks!
