### ISSUE TITLE
Compose Version Relay Show

### ISSUE THREAD

**Issue by myounis97** [skydoves/Balloon#429]
- Library Version v1.5.2
- All Devices

Relay show doesn't work only balance window is shown

```
val tutorialBuilder = tutorialBuilder()

var balanceWindow by remember {
    mutableStateOf<BalloonWindow?>(null)
}

var rechargeWindow by remember {
    mutableStateOf<BalloonWindow?>(null)
}

LaunchedEffect(balanceWindow, rechargeWindow) {
    safeLet(balanceWindow, rechargeWindow) { balance, recharge ->
        balance.relayShowAlignBottom(recharge.balloon)
        balance.showAlignBottom()
    }
}
```

Could you please help me making this to work on compose version

**Comment by abhiemanyu87** [comment]
I was wondering too how to sequentially show balloon with compose.

**Comment by skydoves** [comment]
Hey @myounis97 @abhiemanyu87 @Monabr guys,

Sorry for the very delayed response. In the new version 1.6.0, you're able to use `await__` functions instead of relay functions like the example below:

```kotlin
LaunchedEffect(balanceWindow, rechargeWindow) {
    safeLet(balanceWindow, rechargeWindow) { balance, recharge ->
        balance.awaitAlignStart()
        recharge.awaitAlignBottom()
    }
}
```

Please leave any comments if you face any problems with using these new functions. Thanks!
