### ISSUE TITLE
 Binary XML file line #65 in com.myDemo.app:layout/layout_balloon_library_skydoves: Error inflating class <unknown>

### ISSUE THREAD

**Issue by pratistha-05** [skydoves/Balloon#441]
I have released my app in playstore and it often crashes at runtime.I cannot replicate this issue. What can be the possible solution?
<img width="1156" alt="Screenshot 2023-04-11 at 4 41 17 PM" src="https://user-images.githubusercontent.com/60975387/231145773-2daa7471-3897-4b6d-8bca-829079648a3c.png">

**Comment by skydoves** [comment]
Hey @pratistha-05, would you share the version you're using with me? Thanks!

**Comment by pratistha-05** [comment]
com.github.skydoves:balloon:1.3.6 ,not able to migrate to 1.5.3 due to lower version(32) of compile SDK which is configure with my project

**Comment by skydoves** [comment]
Interesting. It seems your proguard rule encrypted or R8 removed a drawable resource for the arrow. What is the min sdk of your app? And 1.3.x version is too old. Please update the library as much as possible even 1.4.x.

**Comment by skydoves** [comment]
Hey @pratistha-05, I'm closing this issue now, because there's nothing much that I can do for very old version.

**Comment by pratistha-05** [comment]
hi @skydoves I upgraded it to 1.5.0 still crashes are seen, and also gradle plugin in 8.5
