### ISSUE TITLE
Animations enhancement and parametrization

### ISSUE THREAD

**Issue by PawelZarzycki** [skydoves/Balloon#442]
**Is your feature request related to a problem?**

As a user I would be confused with a tooltip with Heartbeat animation set to pulse so much and so fast. With a custom layout it's hard to read the content.

**Describe the solution you'd like:**

https://user-images.githubusercontent.com/8467737/233222131-3efbf912-50d8-453a-900a-783ad29dcc34.mov

It would be great to be able to specify the animation duration as well as the enlargement size. Or disabling the enlargement.
For breath animation there could also be a parameter if the animation should be dimmed.

Otherwise we can add more animations but the ones that do not influence readability of the text.

**Comment by skydoves** [comment]
Hey @PawelZarzycki, you can customize the animation with `setBalloonHighlightAnimationResource` function.

**Comment by skydoves** [comment]
You can reference the original animation when you create your custom animation.

```xml
<set xmlns:android="http://schemas.android.com/apk/res/android"
  android:interpolator="@android:anim/linear_interpolator">
  <scale
    android:duration="800"
    android:fromXScale="100%"
    android:fromYScale="100%"
    android:pivotX="50%"
    android:pivotY="50%"
    android:repeatCount="infinite"
    android:repeatMode="reverse"
    android:toXScale="90%"
    android:toYScale="90%" />
</set>
```
