### ISSUE TITLE
Arrow not it the right place on Android 23

### ISSUE THREAD

**Issue by AndreyBulgakow** [skydoves/Balloon#45]
- Library Version 1.1.5
- Affected Device: Emulator, Nexus S, API 23
 
Bug:

With the following code the arrow is always miss-placed on the devices with smaller screen, API 23 (please see the screenshot attached).  It does not happen for example on the emulator Pixel 3, API 29.

Here is the Kotlin dsl I use:

```
val balloon = createBalloon(requireContext()) {
            setArrowSize(10)
            setArrowOrientation(ArrowOrientation.TOP)
            setPaddingTop(16)
            setPaddingRight(21)
            setPaddingBottom(16)
            setPaddingLeft(21)
            setCornerRadius(4f)
            setAlpha(0.85f)
            setText("12")
            setTextColorResource(R.color.black)
            setBackgroundColorResource(R.color.white)
            setLifecycleOwner(lifecycleOwner)
        }
```
It would be really nice if someone could help me with this :(

Emulator, Nexus S, API 23:
![Bildschirmfoto 2020-05-07 um 22 22 25](https://user-images.githubusercontent.com/15124418/81341091-42a5e180-90b1-11ea-9ced-00f2135bc319.png)

Emulator Pixel 3a, API 29
![Bildschirmfoto 2020-05-07 um 22 21 41](https://user-images.githubusercontent.com/15124418/81341106-48032c00-90b1-11ea-98bc-2bcbf389d32d.png)

**Comment by AndreyBulgakow** [comment]
@skydoves do you have any idea what it could be? I stuck in the middle of the project and would really appreciate some help on this one.

**Comment by meikefelicia** [comment]
@AndreyBulgakow I'm also stuck with the mis-placed views for Nexus 6 API 23. Did you find a solution?

**Comment by skydoves** [comment]
Hi, @AndreyBulgakow.
The new version [1.1.6](https://github.com/skydoves/Balloon/releases/tag/1.1.6) is released and you can check it!
Thank you for your issue :)
