### ISSUE TITLE
Balloon tooltip doesn't go enough to the left to center over a button on the bottom bar

### ISSUE THREAD

**Issue by Digipom** [skydoves/Balloon#452]
- Library Version: 1.0.5
- Affected Device(s): All

The culprit appears to be lines 459 to 463 of Balloon.kt, specifically, `getDoubleArrowSize()`:
```
 when {
              position <= getDoubleArrowSize() -> minPosition
              position > getMeasuredWidth() - getDoubleArrowSize() -> maxPosition
              else -> position
            }
```

Code to reproduce:
```
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            BalloonBugTheme {
                Scaffold(
                    bottomBar = {
                        BottomAppBar(actions = {
                            val backgroundColor = MaterialTheme.colorScheme.primaryContainer
                            val builder = rememberBalloonBuilder {
                                setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
                                setPadding(16)
                                setCornerRadius(12f)
                                setBackgroundColor(backgroundColor)
                                setDismissWhenTouchOutside(false)
                            }
                            Balloon(
                                builder = builder,
                                balloonContent = {
                                    Text(
                                        color = MaterialTheme.colorScheme.onPrimaryContainer,
                                        text = "Hello, world!"
                                    )
                                }
                            ) { balloonWindow ->
                                IconButton(
                                    onClick = { }) {
                                    Icon(
                                        imageVector = Icons.Default.MoreVert,
                                        contentDescription = null
                                    )
                                }
                                LaunchedEffect(Unit) {
                                    balloonWindow.showAlignTop()
                                }
                            }
                        })
                    }
                ) {
                    Greeting(modifier = Modifier.padding(it), name = "Android")
                }
            }
        }
    }
}

@Composable
fun Greeting(name: String, modifier: Modifier = Modifier) {
    Text(
        text = "Hello $name!",
        modifier = modifier
    )
}
```
Screenshot attached.
![image](https://github.com/skydoves/Balloon/assets/2005192/6da87a92-c218-4fe7-beb1-ba31d9d7e527)

**Comment by skydoves** [comment]
Hey @Digipom, would you be able to attach a proper image? Thanks!

**Comment by Digipom** [comment]
Hi @skydoves, please let me know if this works:
![240366828-6da87a92-c218-4fe7-beb1-ba31d9d7e527](https://github.com/skydoves/Balloon/assets/2005192/8cb1782a-2a72-4585-8c76-31cca9818a87)

**Comment by skydoves** [comment]
Hey @Digipom, Would you add the method inside the builder? `setArrowPosition(0.5f)`

**Comment by Digipom** [comment]
That didn't seem to help.

In any case, I believe that it's better to handle this natively with Compose rather than trying to retrofit an Android View-based system into Compose. I ended up using a native solution that doesn't use this library.

I'm happy to share the code in case it could help you with porting the library to Compose. Here's the gist: https://gist.github.com/Digipom/ffab09bca7c2a61b6fb215f6709fc69b

**Comment by skydoves** [comment]
@Digipom Hmm, interesting. Let me look into the details when I have a moment. 

Btw what is the exact definition of "native"? 😄 If look into the details of your "native" `Popup`, the internal side will not be so much different uses windows at the end. Anyway, thanks for sharing your solution. Let me also take a look at the code.

**Comment by Digipom** [comment]
@skydoves Yes that's a good point. ;) I found that by using Compose to do the shape drawing that we have better results with the shadow also.
