### ISSUE TITLE
Sometime OverlayColorResource of tooltip is not working

### ISSUE THREAD

**Issue by HypnoticLemon** [skydoves/Balloon#453]
**Please complete the following information:**
- Library Version v1.5.3
- Affected Devices - 

1. Samsung Galaxy S21FE  with Android 13
2. One Plus 9 with Android 11
3. Samsung Galaxy S22  with Android 13

 
**Describe the Bug:**

While displaying a tool-tip over any Android view element (such as a button or Recycler View), the background is not blurring properly. I have set the `setOverlayColorResource`  property, but sometimes it does not work properly. This is very random behavior; sometimes it will appear properly, and sometimes it will not display the overlay color.

**Expected Behavior:**

Overlay color should display every time

**Comment by skydoves** [comment]
Hey @HypnoticLemon, would you attach any screenshots or something?

**Comment by HypnoticLemon** [comment]
[https://drive.google.com/file/d/1Ie99t-qn1zD6AsDB8wwzqPhVfXJezIy5/view?usp=sharing](url)

**Comment by HypnoticLemon** [comment]
here is the screenshot with the overlay issue
<img width="183" alt="issue screenshot" src="https://github.com/skydoves/Balloon/assets/14808713/8114a7b5-038a-41f7-a094-613c03d3147d">

**Comment by HypnoticLemon** [comment]
Screenshot with missing background overlay 
<img width="183" alt="issue screenshot" src="https://github.com/skydoves/Balloon/assets/14808713/5552b683-ae0d-4044-bebc-3dd33032df95">

**Comment by skydoves** [comment]
@HypnoticLemon Hmm. Would you provide your `Balloon.Builder`?

The demo project like the one below works well from my side:

```kotlin
      .setIsVisibleOverlay(true)
      .setOverlayColorResource(R.color.overlay)
      .setOverlayPaddingResource(R.dimen.editBalloonOverlayPadding)
      .setBalloonHighlightAnimation(BalloonHighlightAnimation.SHAKE)
      .setOverlayShape(
        BalloonOverlayRoundRect(
          R.dimen.editBalloonOverlayRadius,
          R.dimen.editBalloonOverlayRadius
        )
      )
```

**Comment by skydoves** [comment]
I will close this issue for now, @HypnoticLemon. Please comment on this thread again if you still face the same issue. Thanks!
