### ISSUE TITLE
Issue with rotated views

### ISSUE THREAD

**Issue by Equin** [skydoves/Balloon#456]
- Library Version [e.g. v1.5.3]
 
**Describe the Bug:**

When showing balloon over rotated view with showAlignTop, balloon displayed not at top of Bounding box, but relative to top of view. How i can achive normal behaviour? 

its without rotation
https://prnt.sc/xBRzmDYTdbmc

this one with rotation
https://prnt.sc/9DRjuz9GxSNo

**Expected Behavior:**

Balloon displayed always on top of View not depending on rotation of view. 

should be like this but horizontaly it still not centered. 
https://prnt.sc/0ivpUQ13hJcS

builder: 
     val balloonB: Balloon.Builder = Balloon.Builder(view.context)
                    .setDismissWhenClicked(dismissWhenClicked)
                    .setDismissWhenTouchOutside(false)
                    .setIsVisibleArrow(false)
                    .setHeight(height.toInt())
                    .setElevation(0)
                    .setDismissWhenShowAgain(true)
                    .setLayout(KRDrawSelectorView(view.context))
                    .setBackgroundColor(ContextCompat.getColor(view.context, R.color.krSmoke))
                    .setBalloonAnimation(BalloonAnimation.FADE)
                    .setLifecycleOwner(view.context as LifecycleOwner)
    
    if (isFoolScreen) {
        balloonB
            .setWidthRatio(1f)
            .setCornerRadius(0f)
    } else {
        balloonB
            .setWidth(width.toInt())
            .setCornerRadius(10f)
    }

showing like this 
  balloon.showAlignTop(view, yOff = yOffset)

**Comment by Equin** [comment]
@skydoves  thanks, but its little bit complicated. Library calculates width and height of view by getMeasuredWidth/getMeasuredHeight. so when view rotated width and height didnt change. 
also i have zooming feature, so it became more complicated to calculate correct offsets.   

i did like this (maybe there is easier way), and it works good for first displaying/ but  when i use balloon.update when i change location or size of element it doesnt place ballon on top of element. and content of balloon doubles. 

befor balloon.update -> https://prnt.sc/gzRuIEGBKVZl
after ballon.update -> https://prnt.sc/ZQyVfPewwjaw

maybe you have advice how to fix it ? 


code for calculating offset. 
`        fun getBalloonOffset(zoomRegion: ZoomedRegionLocation?, view:View):PointF {
            var offsetX = 0f
            var offsetY = 0f

            zoomRegion?.let {
                val scale = it.zoomFactor

                val originalRect = Rect()
                val location = IntArray(2)
                view.getLocationInWindow(location)

                view.getGlobalVisibleRect(originalRect)

                val oldWidth = view.measuredWidth
                val newWidth = originalRect.width()
                val boundingBoxWidthDelta = oldWidth - newWidth

                val scaledWidth = originalRect.width() * scale
                val deltaScaledW = (scaledWidth - originalRect.width()) / 2

                val logicalX: Float = originalRect.left.toFloat()
                val logicalY: Float = originalRect.top.toFloat()

                val adjustedLogicalX: Float = logicalX - zoomRegion.left
                val adjustedLogicalY: Float = logicalY - zoomRegion.top

                val physicalX = adjustedLogicalX * scale
                val physicalY = adjustedLogicalY * scale

                val deltaOriginalViewXWithScaledViewX = physicalX - logicalX
                val deltaOriginalViewYWithScaledViewY = physicalY - logicalY

                val zoomRegionTopOffset = zoomRegion.zoomRegionTopOffset

                offsetX =
                    deltaOriginalViewXWithScaledViewX + deltaScaledW + (originalRect.left - location[0]) - boundingBoxWidthDelta / 2
                offsetY =
                    deltaOriginalViewYWithScaledViewY + (originalRect.top - location[1]) + zoomRegionTopOffset
            }

            return PointF(offsetX, offsetY)
        }`

**Comment by skydoves** [comment]
Hey @Equin, I'm sorry for the delayed response. I'm not sure if this works but want to suggest a tricky solution:

If you can measure the size of the `zoomRegion` view, you can simply add the exact same size of the vacant (invisible overlay) view, such as [GhostView](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/GhostView.java) over your `zoomRegion` view. Even if the size of the original view is changed, you can keep reflecting it on the overlay view and use it as an anchor view to display Balloon.
