### ISSUE TITLE
Balloon content update if data changes

### ISSUE THREAD

**Issue by rezafaraji93** [skydoves/Balloon#458]
**Is your feature request related to a problem?**

No

**Describe the solution you'd like:**

I have implemented the ballon on the thumb of slider in jetpack compose and I want to update the text inside ballon as the slider value is changing. Please help to achieve this.

**Comment by skydoves** [comment]
Hey @rezafaraji93, you can update the content by using `key` parameter. 

```kotlin
Balloon(
  key = sometihng
)
```
