### ISSUE TITLE
Jetpack Compose: Wrong calculation of the height of the Balloon view!

### ISSUE THREAD

**Issue by Monabr** [skydoves/Balloon#460]
**Please complete the following information:**
- Library Version: 1.5.3
- Affected Device(s): Every device
 
**Describe the Bug:**

The height of the Balloon starts from big and than jump to normal. Here is schema from Paint to describe.

![image](https://github.com/skydoves/Balloon/assets/30532666/e95af2f7-060d-43cf-a4e4-72641eb3dbdf)

**Expected Behavior:**

The height should be the same as the target view height. No height jumps should be presents.

**Comment by skydoves** [comment]
Hey @Monabr, sorry for the very delayed response. A new version 1.6.0 has been released, please check it out the new version still produces the same issue. Thank you!

**Comment by skydoves** [comment]
I will close this issue since this issue has been fixed in version 1.6.0. Thanks for reporting this issue!
