### ISSUE TITLE
Can not show multiple tooltips in a Row

### ISSUE THREAD

**Issue by dr-lobo** [skydoves/Balloon#464]
**Please complete the following information:**
- Library Version 1.5.4
- Affected Device(s) All devices
**Describe the Bug:**

I have a row, with several items on that row that have tool tip associated to them then only the first balloon is correctly rendered.
All the other balloons when item is clicked does not render. 

Add a clear description about the problem.

I have just taken code from the sample app demo but instead of putting it into a Box I have placed the items into a Row (removed the placement modifiers). 

When you run this code, click on the first button. check that it renders correctly. Then click on the other buttons you will see that the non of the content of the balloon is displayed at all.

@Composable
fun ToolTipDemo() {

    val builder = rememberBalloonBuilder {
        setArrowSize(10)
        setWidth(BalloonSizeSpec.WRAP)
        setHeight(BalloonSizeSpec.WRAP)
        setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        setArrowPosition(0.5f)
        setPadding(12)
        setMarginHorizontal(12)
        setTextSize(15f)
        setCornerRadius(8f)

        setBalloonAnimation(BalloonAnimation.ELASTIC)
        setIsVisibleOverlay(true)

        setBalloonHighlightAnimation(BalloonHighlightAnimation.SHAKE)

        setDismissWhenClicked(true)
    }

    Row(modifier = Modifier.fillMaxSize()) {
        Balloon(
            modifier = Modifier
                .padding(20.dp),
            //    .align(Alignment.Center),
            builder = builder,
            balloonContent = {
                Text(
                    text = "Now you can edit your profile1 profile2 profile3 profile4",
                    textAlign = TextAlign.Center,
                    color = Color.White
                )
            }
        ) { balloonWindow ->
            Button(
                modifier = Modifier.size(160.dp, 60.dp),
                onClick = { balloonWindow.showAlignTop() }
            ) {
                Text(text = "showAlignTop")
            }
        }

        Balloon(
            modifier = Modifier
                .padding(20.dp),
       //         .align(Alignment.TopStart),
            builder = builder,
            balloonContent = {
                Text(
                    text = "Now you can edit your profile!",
                    textAlign = TextAlign.Center,
                    color = Color.White
                )
            }
        ) { balloonWindow ->
            Button(
                modifier = Modifier.size(160.dp, 60.dp),
                onClick = { balloonWindow.showAlignTop() }
            ) {
                Text(text = "wrap balloon")
            }
        }

        Balloon(
            modifier = Modifier
                .padding(20.dp),
          //      .align(Alignment.TopEnd),
            builder = builder,
            balloonContent = {
                Box(modifier = Modifier.fillMaxWidth()) {
                    Box(
                        modifier = Modifier
                            .size(50.dp)
                            .align(Alignment.CenterStart)
                            .background(Color.Blue)
                    )
                    Box(
                        modifier = Modifier
                            .size(50.dp)
                            .align(Alignment.Center)
                            .background(Color.Blue)
                    )
                    Box(
                        modifier = Modifier
                            .size(50.dp)
                            .border(2.dp, Color.Red)
                            .align(Alignment.CenterEnd)
                            .background(Color.Blue)
                    )
                }
            }
        ) { balloonWindow ->
            Button(
                modifier = Modifier.size(160.dp, 60.dp),
                onClick = { balloonWindow.showAlignBottom() }
            ) {
                Text(text = "alignments")
            }
        }
    }
}

**Comment by xpressivecode** [comment]
We're running into the same issue as well. 2 balloons show up fine, but >= 3 render an elongated balloon with no content

**Comment by kostapostolakis** [comment]
I have the same problem too. Please fix it.

**Comment by skydoves** [comment]
Hey @dr-lobo @xpressivecode @kostapostolakis guys, sorry for the very delayed response.

A new version 1.6.0 has been released, please check it out the new version still produces the same issue. Thank you!

**Comment by skydoves** [comment]
@kostapostolakis I'm happy to hear that! Thanks for raising this issue.
