### ISSUE TITLE
Balloon-Compose height issue

### ISSUE THREAD

**Issue by isansc** [skydoves/Balloon#469]
### Discussed in https://github.com/skydoves/Balloon/discussions/468

<div type='discussions-op-text'>

<sup>Originally posted by **isansc** August 15, 2023</sup>
I'm trying to use the compose version of balloon and its height seems to have some limit. It seems to be the same problem that the xml version faced in this issue: https://github.com/skydoves/Balloon/issues/148

It doesn't work even when I set a height value (e.g. 500)

But in my case I'm using the Compose version.

Below is the simple code I'm using based on the Medium arcticle:

`
    val context = LocalContext.current
    // ToolTip Builder:
    val builder = rememberBalloonBuilder {
        setArrowSize(16)
        setArrowColorMatchBalloon(true)
        setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
//        setArrowPosition(0.5f)
        setTextColor(Color.Black)
        setWidth(BalloonSizeSpec.WRAP)
        setHeight(BalloonSizeSpec.WRAP)
        setPadding(12)
        setCornerRadius(12f)
        setBackgroundColor(White)
        setBalloonAnimation(BalloonAnimation.ELASTIC)
        setIsVisibleOverlay(true)
        setOverlayColor(Overlay)
        setBalloonHighlightAnimation(BalloonHighlightAnimation.NONE)
        setDismissWhenClicked(true)
    }

[...]

            IconButton(onClick = { /* Empty while testing */ }
            ) {

                Box(modifier = Modifier.fillMaxSize()) {

                    Balloon(
                        modifier = Modifier.wrapContentHeight(),
                        builder = builder,
                        balloonContent = {
                                Column() {
                                    Text(
                                        modifier = Modifier.fillMaxWidth().wrapContentHeight(),
                                        text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                                        textAlign = TextAlign.Start,
                                        color = Color.Gray,
                                        fontSize = 14.sp
                                    )
                                    Row(
                                        modifier = Modifier
                                            .padding(0.dp, 4.dp)
                                    ) {
                                        Button(
                                            onClick = {
                                                Toast.makeText(
                                                    context,
                                                    "Primary!",
                                                    Toast.LENGTH_LONG
                                                )
                                                    .show()
                                            },
                                            modifier = Modifier
                                                .wrapContentHeight()
                                                .wrapContentWidth(),
                                            shape = RoundedCornerShape(size = 8.dp),
                                            colors = ButtonDefaults.buttonColors(backgroundColor = GreenPersonalization)
                                        ) {
                                            Text(
                                                modifier = Modifier
                                                    .padding(
                                                        start = 4.dp,
                                                        end = 4.dp,
                                                        top = 16.dp,
                                                        bottom = 16.dp
                                                    ),
                                                text = "Primary",
                                                color = White,
                                                textAlign = TextAlign.Center,
                                                fontSize = 18.sp,
                                            )
                                        }
                                        Spacer(modifier = Modifier.height(8.dp))
                                        Button(
                                            onClick = {
                                                Toast.makeText(
                                                    context,
                                                    "Secondary!",
                                                    Toast.LENGTH_LONG
                                                )
                                                    .show()
                                            },
                                            modifier = Modifier
                                                .wrapContentHeight()
                                                .wrapContentWidth(),
                                            border = BorderStroke(2.dp, Grey),
                                            shape = RoundedCornerShape(size = 8.dp),
                                            colors = ButtonDefaults.buttonColors(backgroundColor = White)
                                        ) {
                                            Text(
                                                modifier = Modifier
                                                    .padding(
                                                        start = 4.dp,
                                                        end = 4.dp,
                                                        top = 16.dp,
                                                        bottom = 16.dp
                                                    ),
                                                text = "Secondary",
                                                color = Grey,
                                                textAlign = TextAlign.Center,
                                                fontSize = 18.sp,
                                            )
                                        }
                                    }
                                }
                            }
                        }
                    ) { balloonWindow ->

                        if (showTooltip) {
                            balloonWindow.showAlignBottom()
                        }

                        IconButton(
                            modifier = Modifier.size(60.dp, 60.dp),
                            onClick = { balloonWindow.showAlignBottom() }
                        ) {
                            Box {
                                Image(
                                    modifier = Modifier
                                        .width(24.dp)
                                        .height(24.dp),
                                    painter = painterResource(id = R.drawable.ic_logo_svg),
                                    contentDescription = "TEST TOOLTIP",
                                    colorFilter = ColorFilter.tint(Red)
                                )
                            }
                        }
                    }
                }
            

`

</div>

**Comment by kostapostolakis** [comment]
I mention here this comment describing the same issue.
https://github.com/skydoves/Balloon/issues/148#issuecomment-1680278313

**Comment by isansc** [comment]
Good! Exactly the same issue I'm facing, and I'm using it in a TopAppBar too, it may be related to the bar. 
I did some tests:
- I cloned the repository and put a long text in the sample app and it worked fine
- Then I copied the sample implementation to my app (using on a button inside TopAppBar) and the issue appeared

**Comment by gaborrosta** [comment]
I have a similar issue.
I have some checkboxes with balloons in a Column. The text for the first ballon has 3 lines but only 2 are visible and the next ballon has a different string which has 3 lines as well and the whole text is visible.
If I add padding to the text inside the balloonContent and if without it the text would fit into 2 lines, the text is cut. But if I add the padding in the builder, the same happens. Without padding the whole text is displayed.
My current workaround is to add a `"\n"` to the text.

**Comment by skydoves** [comment]
Hey @isansc lobo @kostapostolakis @gaborrosta  guys, sorry for the very delayed response.

A new version 1.6.0 has been released, please check it out the new version still produces the same issue. Thank you!

**Comment by gaborrosta** [comment]
@skydoves
I've tried the new version. It is still not working.

**Comment by skydoves** [comment]
With the given example by @isansc, it seems to work well. @gaborrosta Would you give me any other examples? You can provide any samples with gist. 

![Screenshot 2023-09-19 at 7 57 19 AM](https://github.com/skydoves/Balloon/assets/24237865/8d28c0fd-311e-42c9-8fb9-ae81b974ead3)

**Comment by gaborrosta** [comment]
@skydoves
This is an example of my situation. I also attached a screenshot of how it is displayed on my phone.

```kotlin
@Composable
fun Example() {
    val interactionSource = remember { MutableInteractionSource() }

    val backgroundColor = MaterialTheme.colors.secondary.toArgb()
    val builder = rememberBalloonBuilder {
        this.backgroundColor = backgroundColor
        this.setHeight(BalloonSizeSpec.WRAP)
    }

    Balloon(
        builder = builder,
        balloonContent = {
            Text(
                text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
                modifier = Modifier
                    .padding(all = 8.dp),
            )
        },
    ) { balloonWindow ->
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .clickable(
                    interactionSource = interactionSource,
                    indication = LocalIndication.current,
                    onClick = {},
                )
                .padding(end = 8.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Checkbox(
                checked = true,
                onCheckedChange = null,
                modifier = Modifier
                    .padding(all = 12.dp),
            )

            Text(
                text = "Lorem ipsum",
                modifier = Modifier
                    .weight(weight = 1f),
            )

            IconButton(
                onClick = { balloonWindow.showAlignBottom() },
            ) {
                Icon(
                    imageVector = Icons.Filled.Info,
                    contentDescription = "Info",
                )
            }
        }
    }
}
```

![Screenshot](https://github.com/skydoves/Balloon/assets/32847735/90c9322b-d466-4176-bf2d-1567455522cf)

**Comment by kostapostolakis** [comment]
> Hey @isansc lobo @kostapostolakis @gaborrosta guys, sorry for the very delayed response.
> 
> A new version 1.6.0 has been released, please check it out the new version still produces the same issue. Thank you!

It was fixed in compose. Thanks!

**Comment by skydoves** [comment]
@kostapostolakis Thanks for checking this issue!

**Comment by skydoves** [comment]
@gaborrosta Are you sure you're using 1.6.0?

My Samsung devices (S10, S23) works really work:

<img width="426" alt="Screenshot 2023-09-20 at 3 52 51 PM" src="https://github.com/skydoves/Balloon/assets/24237865/a477c022-1534-4364-ba51-fb05d51cdb37">

**Comment by skydoves** [comment]
@gaborrosta I hope you try the builder below:

```kotlin
      val builder = rememberBalloonBuilder {
        setArrowSize(10)
        setWidth(BalloonSizeSpec.WRAP)
        setHeight(BalloonSizeSpec.WRAP)
        setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        setArrowPosition(0.5f)
        setPadding(12)
        setMarginHorizontal(12)
        setTextSize(15f)
        setCornerRadius(8f)
        setBackgroundColorResource(R.color.skyBlue)
        setBalloonAnimation(BalloonAnimation.ELASTIC)
        setIsVisibleOverlay(true)
        setOverlayColorResource(R.color.overlay)
        setOverlayPaddingResource(R.dimen.editBalloonOverlayPadding)
        setBalloonHighlightAnimation(BalloonHighlightAnimation.SHAKE)
        setOverlayShape(
          BalloonOverlayRoundRect(
            R.dimen.editBalloonOverlayRadius,
            R.dimen.editBalloonOverlayRadius,
          ),
        )
        setDismissWhenClicked(true)
      }
```

**Comment by gaborrosta** [comment]
> @gaborrosta Are you sure you're using 1.6.0?
> 
> My Samsung devices (S10, S23) works really work:
> 
> <img alt="Screenshot 2023-09-20 at 3 52 51 PM" width="426" src="https://user-images.githubusercontent.com/24237865/269188517-a477c022-1534-4364-ba51-fb05d51cdb37.png">

@skydoves Yes.
But the text must be able to fit into two rows without padding. And then if padding is added, it will need 3 lines but only 2 will be visible.
You need to alter my example a little bit to get the same result on your devices.

**Comment by skydoves** [comment]
That's weird.. 

```kotlin
        Balloon(
          modifier = Modifier
            .padding(20.dp)
            .align(Alignment.Center),
          builder = rememberBalloonBuilder {
            setBackgroundColorResource(R.color.skyBlue)
            setHeight(BalloonSizeSpec.WRAP)
          },
          balloonContent = {
            Text(
              text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
              modifier = Modifier
                .padding(all = 8.dp),
            )
          },
        ) { balloonWindow ->
          Button(
            modifier = Modifier.size(160.dp, 60.dp),
            onClick = { balloonWindow1.showAlignTop() },
          ) {
            Text(text = "showAlignTop")
          }
        }
```

Result: (Pixel 4a API 32)

![Screenshot 2023-09-21 at 1 57 31 PM](https://github.com/skydoves/Balloon/assets/24237865/79c41bff-6699-4b1a-a769-399c7b22049f)

**Comment by gaborrosta** [comment]
@skydoves 
I've tried again, but still not working. I took screenshots (Honor 20), so the text is properly displayed without `8.dp` padding like this:

![no padding](https://github.com/skydoves/Balloon/assets/32847735/757b6f30-1ca3-4488-b169-fae17106760a)

But if I add padding even in the `builder` or inside the `Text` Composable inside `balloonContent`, I get this:

![padding](https://github.com/skydoves/Balloon/assets/32847735/8404759a-d47d-4c87-80c8-f39693280deb)

Interestingly, I tried with different padding rather than `8.dp` in both places. With padding`12.dp` (as in your previously sent `builder`) and `9.dp` it is working properly, but I get the same problem with `7.dp`.

I hope this explanation helps you with finding the solution.

**Comment by JoseAsunsolo98** [comment]
Hi @skydoves ,
I have the same problem with the height and I will try to give the most detailed information possible.

`
data class WalkThroughTexts(
    val title: String = "Title",
    val body: String = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
    val button: String = "Next"
)
`
This is my Balloon composable:

`
@Composable
fun WalkthroughTooltip(
    modifier: Modifier = Modifier,
    showTooltip: Boolean,
    showAlignTop: Boolean = false,
    tooltipConfiguration: TooltipConfiguration = TooltipConfiguration(),
    tooltipContent: @Composable (() -> Unit),
    content: @Composable () -> Unit
) {
    val toolTipBuilder = buildTooltip(tooltipConfiguration)
    Balloon(
        modifier = modifier,
        builder = toolTipBuilder,
        balloonContent = {
            //tooltipContent()
            WalkThroughTooltipInfo(walkThroughTexts = WalkThroughTexts()) {}
        }
    ) {
        content()
        it.setOnBalloonDismissListener(tooltipConfiguration.onDismiss)
        if (showTooltip) {
            when {
                showAlignTop -> it.showAlignTop()
                else -> it.showAlignBottom()
            }
        } else it.dismiss()
    }
}
`
With the next builder:

`
rememberBalloonBuilder {
        setArrowSize(10)
        setArrowPosition(0.5f)
        setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        setMarginHorizontal(12)
        setCornerRadius(8f)
        setWidth(BalloonSizeSpec.WRAP)
        setHeight(BalloonSizeSpec.WRAP)
        setBackgroundColor(backgroundColor)
        setBalloonAnimation(BalloonAnimation.ELASTIC)


        setIsVisibleOverlay(true)
        setOverlayColor(overlayBackgroundColor)
        setOverlayPaddingColor(overlayPaddingColor)
        setBalloonOverlayAnimation(BalloonOverlayAnimation.FADE)
        setDismissWhenOverlayClicked(tooltipConfiguration.setDismissWhenOverlayClicked)
        setOverlayShape(overlayShape)
    }
`

The WalkThroughTooltipInfo composable code is:

`
@Composable
fun WalkThroughTooltipInfo(
    walkThroughTexts: WalkThroughTexts?,
    onNextClick: () -> Unit
) {
    Column(
        modifier = Modifier
            .width(240.dp)
            .height(IntrinsicSize.Max)
            .padding(top = spacing16, start = spacing16, end = spacing16)
            .background(purple_600)
    ) {
        Row(modifier = Modifier.height(IntrinsicSize.Max)) {
            Text(
                modifier = Modifier.weight(1f),
                text = walkThroughTexts?.title.orEmpty(),
                style = typoBodyBold,
                color = white
            )
            Image(
                painter = painterResource(id = R.drawable.n_ic_close_white),
                contentDescription = null,
                modifier = Modifier
                    .size(dimen16)
            )
        }
        Text(
            modifier = Modifier
                .padding(end = spacing4, top = spacing8)
                .wrapContentHeight(),
            text = walkThroughTexts?.body.orEmpty(),
            style = typoCaption.copy(color = white)
        )
        Spacer(modifier = Modifier.height(spacing16))
        Row(
            modifier = Modifier
                .height(IntrinsicSize.Max)
                .fillMaxWidth(), horizontalArrangement = Arrangement.End
        ) {
            WhiteBorderButton(
                modifier = Modifier.height(dimen24),
                buttonBorderConfiguration = BorderButtonConfiguration(
                    textColor = { purple_600 },
                    textSize = { textSize10 },
                    contentPadding = PaddingValues(
                        vertical = dimen4,
                        horizontal = dimen24
                    )
                ),
                buttonText = walkThroughTexts?.button.orEmpty(),
                onClick = {
                    onNextClick()
                }
            )
        }
        Column(
            modifier = Modifier
                .padding(bottom = 16.dp)
                .background(purple_600)
        ) {

        }
    }
}
`
And here the result:

![wrong_tooltip](https://github.com/skydoves/Balloon/assets/150072401/4e9fea66-8071-43b1-85d2-85d6d93e052e)

As you can see, it does not calculate the height correctly and the content is cut.

I have tried to do several things and I have realized that when implementing the texts without my WalkThrougTexts class, directly in the function the component is displayed correctly. This leads me to think that there may be some kind of problem when processing the height when the sizes are variable, since when putting fixed texts the size calculation is faster. Hope that helps

`
@Composable
fun WalkThroughTooltipInfo(
    walkThroughTexts: WalkThroughTexts?,
    onNextClick: () -> Unit
) {
    Column(
        modifier = Modifier
            .width(240.dp)
            .height(IntrinsicSize.Max)
            .padding(top = spacing16, start = spacing16, end = spacing16)
            .background(purple_600)
    ) {
        Row(modifier = Modifier.height(IntrinsicSize.Max)) {
            Text(
                modifier = Modifier.weight(1f),
                text = "Text",
                style = typoBodyBold,
                color = white
            )
            Image(
                painter = painterResource(id = R.drawable.n_ic_close_white),
                contentDescription = null,
                modifier = Modifier
                    .size(dimen16)
            )
        }
        Text(
            modifier = Modifier
                .padding(end = spacing4, top = spacing8)
                .wrapContentHeight(),
            text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
            style = typoCaption.copy(color = white)
        )
        Spacer(modifier = Modifier.height(spacing16))
        Row(
            modifier = Modifier
                .height(IntrinsicSize.Max)
                .fillMaxWidth(), horizontalArrangement = Arrangement.End
        ) {
            WhiteBorderButton(
                modifier = Modifier.height(dimen24),
                buttonBorderConfiguration = BorderButtonConfiguration(
                    textColor = { purple_600 },
                    textSize = { textSize10 },
                    contentPadding = PaddingValues(
                        vertical = dimen4,
                        horizontal = dimen24
                    )
                ),
                buttonText = "Next",
                onClick = {
                    onNextClick()
                }
            )
        }
    }
`

I attach evidence:

![right_tooltip](https://github.com/skydoves/Balloon/assets/150072401/6d743a66-debe-462e-aade-588565d93bc4)

**Comment by JoseAsunsolo98** [comment]
Hi @skydoves ,
I have the same problem with the height and I will try to give the most detailed information possible.

```kotlin
data class WalkThroughTexts(
    val title: String = "Title",
    val body: String = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
    val button: String = "Next"
)
```
This is my Balloon composable:

```kotlin
@Composable
fun WalkthroughTooltip(
    modifier: Modifier = Modifier,
    showTooltip: Boolean,
    showAlignTop: Boolean = false,
    tooltipConfiguration: TooltipConfiguration = TooltipConfiguration(),
    tooltipContent: @Composable (() -> Unit),
    content: @Composable () -> Unit
) {
    val toolTipBuilder = buildTooltip(tooltipConfiguration)
    Balloon(
        modifier = modifier,
        builder = toolTipBuilder,
        balloonContent = {
            //tooltipContent()
            WalkThroughTooltipInfo(walkThroughTexts = WalkThroughTexts()) {}
        }
    ) {
        content()
        it.setOnBalloonDismissListener(tooltipConfiguration.onDismiss)
        if (showTooltip) {
            when {
                showAlignTop -> it.showAlignTop()
                else -> it.showAlignBottom()
            }
        } else it.dismiss()
    }
}
```

With the next builder:

```
rememberBalloonBuilder {
        setArrowSize(10)
        setArrowPosition(0.5f)
        setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        setMarginHorizontal(12)
        setCornerRadius(8f)
        setWidth(BalloonSizeSpec.WRAP)
        setHeight(BalloonSizeSpec.WRAP)
        setBackgroundColor(backgroundColor)
        setBalloonAnimation(BalloonAnimation.ELASTIC)
        setIsVisibleOverlay(true)
        setOverlayColor(overlayBackgroundColor)
        setOverlayPaddingColor(overlayPaddingColor)
        setBalloonOverlayAnimation(BalloonOverlayAnimation.FADE)
        setDismissWhenOverlayClicked(tooltipConfiguration.setDismissWhenOverlayClicked)
        setOverlayShape(overlayShape)
    }   
```

The WalkThroughTooltipInfo composable code is:

```
@Composable
fun WalkThroughTooltipInfo(
    walkThroughTexts: WalkThroughTexts?,
    onNextClick: () -> Unit
) {
    Column(
        modifier = Modifier
            .width(240.dp)
            .height(IntrinsicSize.Max)
            .padding(top = spacing16, start = spacing16, end = spacing16)
            .background(purple_600)
    ) {
        Row(modifier = Modifier.height(IntrinsicSize.Max)) {
            Text(
                modifier = Modifier.weight(1f),
                text = walkThroughTexts?.title.orEmpty(),
                style = typoBodyBold,
                color = white
            )
            Image(
                painter = painterResource(id = R.drawable.n_ic_close_white),
                contentDescription = null,
                modifier = Modifier
                    .size(dimen16)
            )
        }
        Text(
            modifier = Modifier
                .padding(end = spacing4, top = spacing8)
                .wrapContentHeight(),
            text = walkThroughTexts?.body.orEmpty(),
            style = typoCaption.copy(color = white)
        )
        Spacer(modifier = Modifier.height(spacing16))
        Row(
            modifier = Modifier
                .height(IntrinsicSize.Max)
                .fillMaxWidth(), horizontalArrangement = Arrangement.End
        ) {
            WhiteBorderButton(
                modifier = Modifier.height(dimen24),
                buttonBorderConfiguration = BorderButtonConfiguration(
                    textColor = { purple_600 },
                    textSize = { textSize10 },
                    contentPadding = PaddingValues(
                        vertical = dimen4,
                        horizontal = dimen24
                    )
                ),
                buttonText = walkThroughTexts?.button.orEmpty(),
                onClick = {
                    onNextClick()
                }
            )
        }
        Column(
            modifier = Modifier
                .padding(bottom = 16.dp)
                .background(purple_600)
        ) {

        }
    }
}
```

And here the result:

![wrong_tooltip](https://github.com/skydoves/Balloon/assets/150072401/4e9fea66-8071-43b1-85d2-85d6d93e052e)

As you can see, it does not calculate the height correctly and the content is cut.

I have tried to do several things and I have realized that when implementing the texts without my WalkThrougTexts class, directly in the function the component is displayed correctly. This leads me to think that there may be some kind of problem when processing the height when the sizes are variable, since when putting fixed texts the size calculation is faster. Hope that helps

```
@Composable
fun WalkThroughTooltipInfo(
    walkThroughTexts: WalkThroughTexts?,
    onNextClick: () -> Unit
) {
    Column(
        modifier = Modifier
            .width(240.dp)
            .height(IntrinsicSize.Max)
            .padding(top = spacing16, start = spacing16, end = spacing16)
            .background(purple_600)
    ) {
        Row(modifier = Modifier.height(IntrinsicSize.Max)) {
            Text(
                modifier = Modifier.weight(1f),
                text = "Text",
                style = typoBodyBold,
                color = white
            )
            Image(
                painter = painterResource(id = R.drawable.n_ic_close_white),
                contentDescription = null,
                modifier = Modifier
                    .size(dimen16)
            )
        }
        Text(
            modifier = Modifier
                .padding(end = spacing4, top = spacing8)
                .wrapContentHeight(),
            text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
            style = typoCaption.copy(color = white)
        )
        Spacer(modifier = Modifier.height(spacing16))
        Row(
            modifier = Modifier
                .height(IntrinsicSize.Max)
                .fillMaxWidth(), horizontalArrangement = Arrangement.End
        ) {
            WhiteBorderButton(
                modifier = Modifier.height(dimen24),
                buttonBorderConfiguration = BorderButtonConfiguration(
                    textColor = { purple_600 },
                    textSize = { textSize10 },
                    contentPadding = PaddingValues(
                        vertical = dimen4,
                        horizontal = dimen24
                    )
                ),
                buttonText = "Next",
                onClick = {
                    onNextClick()
                }
            )
        }
    }
```

I attach evidence:

![right_tooltip](https://github.com/skydoves/Balloon/assets/150072401/6d743a66-debe-462e-aade-588565d93bc4)

**Comment by skydoves** [comment]
Hey guys, a new version, 1.6.4, has been released. I'm wondering if this issue still happens in the new version. Thank you for your time in advance!

**Comment by gaborrosta** [comment]
@skydoves I've tried the new version and it seems it is working now. Thank you for the fix!

**Comment by skydoves** [comment]
@gaborrosta Thanks for checking this! I'm closing this issue now. If you still face any similar issue with this, please reopen this issue anytime.

**Comment by TomTruyen** [comment]
@skydoves This issue should be reopened. When setting the "setWidthRatio" to for example: 0.8f it breaks again
