### ISSUE TITLE
Option to have arrow point at (center of) anchor view

### ISSUE THREAD

**Issue by Waboodoo** [skydoves/Balloon#47]
**Is your feature request related to a problem?**

From what I can tell, by default the arrow of the balloon is rendered in the center of the balloon, and the balloon is center aligned with the anchor view when shown. This means that normally, the arrow points at the center of the anchor view. However, if there is not enough space to display the balloon this way (because the balloon reaches the edge of the screen), the balloon is automatically shifted, which also shifts the arrow, causing it to no longer point at the center of the anchor view. While it is possible to change where on the balloon the arrow is displayed by specifying a ratio other than the default 0.5, it is currently not possible to tell the balloon to render the arrow so that it always points at the anchor view. This results in the problem that, if the balloon is too big and the anchor view is small, the arrow does not point at the anchor view at all.

**Describe the solution you'd like:**

I would love to have an option to, instead of specifying a ratio of where the arrow should be, to specify that the arrow should point at the center of the anchor view (or optionally at a certain offset from the anchor view's center).

Something like

```kotlin
enum class ArrowPositionMode {
    ALIGN_WITH_BALLOON, // this will place the arrow in the center of the balloon, or shifted if setArrowPosition is used
    ALIGN_WITH_ANCHOR // this will place the arrow in the center of the anchor view, or shifted if setArrowPosition is used
}

Balloon.Builder(context)
    .setArrowPositionMode(ArrowPositionMode.ALIGN_WITH_ANCHOR)
```

**Describe alternatives you've considered:**

I tried to dynamically compute the arrow ratio when showing the balloon based on where the anchor view is, but for that I'd first have to create the balloon to measure its width, calculate what the arrow position should be, then destroy the balloon again and create a new one with the calculated arrow position (because the arrow position cannot be changed once the balloon is created).

**Comment by mck182** [comment]
This would be fantastic to have! 👍 

I just wanted to add - the arrow should also switch
sides if the tooltip is rendered above or below the
anchor view, depending on the available space.

So for example, if the tooltip is shown by using
`showAlignBottom(..)` but it's actually shown
on top of the view due to the space constraints,
the arrow should switch as well.

**Comment by gavingt** [comment]
This would be great. I'm not using the arrows at all currently because they don't point to the right place if the text is long enough.

**Comment by skydoves** [comment]
Hi guys!
I think the suggestion looks good for positioning easier based on an anchor, so I implemented a `ArrowConstraints` functionality.

```kotlin
/**
 * ArrowConstraints determines the constraints of the arrow positioning.
 * [ArrowConstraints.ALIGN_BALLOON]: aligning based on the balloon.
 * [ArrowConstraints.ALIGN_ANCHOR]: aligning based on the anchor.
 */
enum class ArrowConstraints {
  /** Aligning based on the balloon. */
  ALIGN_BALLOON,

  /** Aligning based on the anchor. */
  ALIGN_ANCHOR
}
```

You can use like below:
```kotlin
setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
```

Please check out the new feature works well in your environments, version `1.1.8-alpha01`.

[ ![Download](https://api.bintray.com/packages/devmagician/maven/balloon/images/download.svg?version=1.1.8-alpha01) ](https://bintray.com/devmagician/maven/balloon/1.1.8-alpha01/link)

**Comment by Waboodoo** [comment]
I tried out `1.1.8-alpha01`. The arrow placement seems to work fine in general, but I'm encountering a problem when trying to have the arrow point at a menu item in a toolbar (I'm using `androidx.appcompat.widget.Toolbar` from `androidx.appcompat:appcompat:1.2.0-alpha01`). In that case, the arrow position is off.

Here's a screenshot (I'm trying to have the arrow point at the item with the red background):
![Screenshot from 2020-06-14 18-21-41](https://user-images.githubusercontent.com/2445563/84598588-247b9000-ae6c-11ea-93ae-519d86d648f3.png)

This is the code I use to show the balloon:
```kotlin
val menuItemView = toolbar.findViewById<View>(R.id.my_menu_item)
Balloon.Builder(context)
    .setText("Click here to get started. It's gonna be fun!")
    .setPadding(16)
    .setTextSize(14f)
    .setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
    .setArrowOrientation(ArrowOrientation.TOP)
    .build()
    .showAlignBottom(menuItemView)
```

This might just be an oddness caused by the toolbar view.

**Comment by skydoves** [comment]
@Waboodoo 
Hi, thanks for checking it!
I just released another version `1.1.8-alpha02`, the problem seems that the actual position of x should be calculated on the basis of the screen. I will also keep debugging use this new version :)

**Comment by Waboodoo** [comment]
Cool. I tried `1.1.8-alpha02` and it seems to fix my issue :+1:. Thanks

**Comment by skydoves** [comment]
@Waboodoo 
This issue is included in the new version [1.1.8](https://github.com/skydoves/Balloon/releases/tag/1.1.8) !
Thank you for your issue :)

**Comment by gastsail** [comment]
This also worked for me !

**Comment by Waboodoo** [comment]
Thanks. I will try it out in my app once I have the time :+1:

**Comment by znakeeye** [comment]
I'm experiencing this toolbar offset problem with version 1.1.9.

From within my fragment, I get hold of the anchor view like this:

```
final View button = requireActivity().findViewById(R.id.menu_item_settings);        
```

Could it be that I call `setSupportActionBar(myToolbar)` in my activity?

**Comment by 4shutosh** [comment]
If anyone is wondering, It's `ArrowPositionRules` in the latest versions.
