### ISSUE TITLE
TalkBack support when setFocusable(false)

### ISSUE THREAD

**Issue by alashow** [skydoves/Balloon#470]
Re-opening https://github.com/skydoves/Balloon/issues/407 since the issue is still there

**Please complete the following information:**
- Library Version 1.5.4
- Affected Device Pixel 7 Pro, samsung SM-X700
 
**Describe the Bug:**

Using `setFocusable(false)` allows touching other views without having to click twice ( if `setFocusable(true)`, need to click once outside balloon to dismiss ballon and another to click for intended view)

However, `setFocusable(false)` disables TalkBack behavior when balloon is shown. Only after clicking the ballon window TalkBack service announces ballon windows text.

**Comment by skydoves** [comment]
Hey @alashow, sorry for the delayed response. What if you call the function below to the balloon's content view like the example below?

```kotlin
balloon.bodyWindow.contentView.sendAccessibilityEvent(AccessibilityEvent.TYPE_VIEW_FOCUSED)
```
