### ISSUE TITLE
[Proposal] Add optional key parameter into rememberBalloonBuilder

### ISSUE THREAD

**Issue by egorikftp** [skydoves/Balloon#475]
**Is your feature request related to a problem?**

I faced some issue when I switch app theme inside compose application.
I pass bgColor and textColor into `Balloon.Builder` and after change theme I need to update this values.

Dark mode
<img width="1075" alt="image" src="https://github.com/skydoves/Balloon/assets/16294951/3cebe085-75c2-40ed-8dd4-daa34f73e127">

Light mode (wrong)
<img width="1114" alt="image" src="https://github.com/skydoves/Balloon/assets/16294951/08d7c81b-3d94-41d2-bcbe-59e3953ee6e6">

Light mode (expected)
<img width="1127" alt="image" src="https://github.com/skydoves/Balloon/assets/16294951/70af500e-3de3-4a56-9ee2-4b20d7518bab">

Source code: https://github.com/egorikftp/GrodnoRoads/blob/43fcdea90af3233a29912d196d2ae53e5323855f/features/map/map-ui/src/main/kotlin/com/egoriku/grodnoroads/map/foundation/UsersCount.kt#L32

**Describe the solution you'd like:**

I suggest to add optional key parameter

```kotlin
@Composable
fun rememberBalloonBuilder(
    key: Any? = null,
    context: Context = LocalContext.current,
    block: Balloon.Builder.() -> Unit
): Balloon.Builder = remember(key) {
    Balloon.Builder(context).apply(block)
}
```

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

**Comment by skydoves** [comment]
This is a really great example. Thank you for raising the issue and sharing your sample project! 👍

**Comment by skydoves** [comment]
Merged. This feature will be included in the next release. For now, you can also use it by importing snapshot version. Thanks!
