### ISSUE TITLE
Setting arrow LEFT messes view for custom layouts

### ISSUE THREAD

**Issue by AndriusRimk** [skydoves/Balloon#48]
- Version: 1.1.5
- Devices:  API 29 Emulator and OnePlus5
- Describe the Bug:
If I set left arrow for custom layout content the layout is shifted to left and corners are messed up.
The builder calls I am using

```
createBalloon(context) {
            setLayout(R.layout.view_sign_up_popup_password_hint)
            setArrowOrientation(ArrowOrientation.LEFT)
            setCornerRadius(4f)
            setBackgroundColorResource(R.color.background_popup_grey)
            setLifecycleOwner(lifecycle)
}
```

The result is:
![login_popup_arrow_left](https://user-images.githubusercontent.com/19285955/81653058-2f8e6b00-943d-11ea-86cc-790768039781.jpg)
If I set Arrow to TOP
![login_popup_arrow_top](https://user-images.githubusercontent.com/19285955/81652131-ee498b80-943b-11ea-9200-b219fb442f56.jpg)

- How to reproduce: change in Balloon demo ProfileBalloonFactory change from TOP to LEFT and the same behavior is happening.
![balloon_demo_arrow_left](https://user-images.githubusercontent.com/19285955/81652132-eee22200-943b-11ea-8b45-5cf3516adc46.jpg)

- Expected behaviors:
Setting arrow left I would expect the balloon is rendered correctly and not distorted.

**Comment by skydoves** [comment]
@AndriusRimk 
Hi, I just check the issue and it will be fixed on the next release.
Thank you for submitting the issue :)
