### ISSUE TITLE
Error on build api 34

### ISSUE THREAD

**Issue by massimilianochiodi** [skydoves/Balloon#482]
Android resource linking failed
it.fca.myeasywallbox.app-mergeMain_f2m_prodReleaseResources-61:/values/values.xml:6609: error: resource anim/elastic_center_balloon_library (aka com.f2m.esolution.free2charge:anim/elastic_center_balloon_library) not found.
it.fca.myeasywallbox.app-mergeMain_f2m_prodReleaseResources-61:/values/values.xml:6610: error: resource anim/fade_out_balloon_library (aka com.f2m.esolution.free2charge:anim/fade_out_balloon_library) not found.
it.fca.myeasywallbox.app-mergeMain_f2m_prodReleaseResources-61:/values/values.xml:6609: error: resource anim/elastic_center_balloon_library (aka com.f2m.esolution.free2charge:anim/elastic_center_balloon_library) not found.
it.fca.myeasywallbox.app-mergeMain_f2m_prodReleaseResources-61:/values/values.xml:6610: error: resource anim/fade_out_balloon_library (aka com.f2m.esolution.free2charge:anim/fade_out_balloon_library) not found.
error: failed linking references.

**Comment by skydoves** [comment]
Hey, which version do you use?

**Comment by massimilianochiodi** [comment]
implementation 'com.github.skydoves:balloon:1.5.4' 

... 
JavaVersion.VERSION_17
API 34 
kotlin_version = '1.9.0'

distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip

**Comment by skydoves** [comment]
Alright, thanks for sharing the details. Let me deliver some fixes in the next release.

**Comment by skydoves** [comment]
in the meantime, would you test the snapshot (1.5.5-SNAPSHOT) version works well on your side?

**Comment by massimilianochiodi** [comment]
YEP !
Thank !

**Comment by skydoves** [comment]
Hmm, this is interesting. Because your error stack indicates different resources names from the library ones:

- elastic_center_balloon_library
- fade_out_balloon_library

But the actual resource name is like so:

- balloon_ealstic_center
- balloon_fade_out

Have you ever includes an old version of Balloon dependencies one of your modules or tweaked the resource names?

**Comment by skydoves** [comment]
If you're trying to update the library version, you may need to clean and rebuild your project.

**Comment by massimilianochiodi** [comment]
I cleaned the project, maybe not enough. i try my last hope... delete the .gradle folder from my home

**Comment by skydoves** [comment]
Those resources that I mentioned actually used a very old version of Balloon.

- elastic_center_balloon_library
- fade_out_balloon_library

I feel like there are some resources have crashed. If you can't find any other old dependencies in your modules + still don't work after cleaning up your project, you can just add those unfound files manually.

anim/elastic_center_balloon_library.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android"
  android:interpolator="@android:anim/bounce_interpolator">
  <scale
    android:duration="250"
    android:fromXScale="0.5"
    android:fromYScale="0.5"
    android:pivotX="50%"
    android:pivotY="50%"
    android:toXScale="1.0"
    android:toYScale="1.0" />
</set>
```

anim/fade_out_balloon_library.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android"
  android:interpolator="@android:anim/linear_interpolator">
  <alpha
    android:duration="200"
    android:fromAlpha="1.0"
    android:toAlpha="0" />
</set>
```

**Comment by massimilianochiodi** [comment]
I clear all ... also .gradle ... but not working .. same error. 
now added manually anim files ... and work fine.

**Comment by skydoves** [comment]
@massimilianochiodi I will close this issue if there are no further problems. Thanks for raising this great issue!
