### ISSUE TITLE
Popup was not dismissed when we tap on the margin space created using setMarginLeft().

### ISSUE THREAD

**Issue by NaveenKadiyala** [skydoves/Balloon#486]
- Library Version - 1.5.4
- Affected Device(s) - Emulator PIXEL 6 - API 33.
 
**Bug Description**

As per documentation, whenever you click on anywhere outside of the Balloon Popup, the pop should be closed. This was working fine when margin was not applied. but whenever I apply some margin to the left of the popup & try to tap on the space created due to margin, the popup was not dismissed.

**Expected Behavior:**

The Popup must be dismissed even if we tap on the margin space.

**Additional Info**
Please check the screenshot attached to see the margin space created using setMarginLeft().
![image](https://github.com/skydoves/Balloon/assets/35886352/85fe8f31-43d5-4734-b0e2-31f871f0f308)

**Comment by skydoves** [comment]
Hey @NaveenKadiyala, thanks for raising this issue. Would you share your code about `Balloon.Builder` as well? It must be very helpful to diagnose this issue.

**Comment by nkhar** [comment]
Hello @NaveenKadiyala 

I might be able to help with your problem.

As you can see `public var dismissWhenTouchOutside: Boolean = true` dismissWhenTouchOutside is set to true. However touching outside means outside of a PopupWindow not outside the content. Here is the code snippet from Balloon.kt for clarity:
`public fun setOnBalloonOutsideTouchListener(onBalloonOutsideTouchListener: OnBalloonOutsideTouchListener?,) {`
`    this.bodyWindow.setTouchInterceptor(`
`      object : View.OnTouchListener {`
`        @SuppressLint("ClickableViewAccessibility")`
`        override fun onTouch(view: View, event: MotionEvent): Boolean {`
`          if (event.action == MotionEvent.ACTION_OUTSIDE) {`
`            if (builder.dismissWhenTouchOutside) {`
`              this@Balloon.dismiss()`
`           }`
`           onBalloonOutsideTouchListener?.onBalloonOutsideTouch(view, event)`
`           return true`
`          }`
          
**this.bodyWindow** is the PopupWindow inside of which the layout is inflated: balloon_layout_body.xml. Here is the snippet from layout:
`<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"`
`  xmlns:app="http://schemas.android.com/apk/res-auto"`
`  xmlns:tools="http://schemas.android.com/tools"`
`  android:id="@+id/balloon"`
`  android:background="#FF0000"`
`  android:layout_width="match_parent"`
`  android:layout_height="match_parent">`

`  <FrameLayout`
`    android:id="@+id/balloon_wrapper"`
`    android:layout_width="match_parent"`
`    android:layout_height="match_parent"`
`    android:focusable="true"`
`    tools:ignore="UselessParent">`

`    <FrameLayout`
`      android:id="@+id/balloon_content"`
`      android:layout_width="match_parent"`
`      android:layout_height="match_parent"`
`      android:layout_gravity="center"`
`      android:clipChildren="false"`
`     android:clipToPadding="false"`
`      android:padding="10dp">`

When the balloon is initialised marginLeft is set as the left layout margin of balloon_wrapper. Here is the code:
`private fun initializeBalloonRoot() {`
`    with(binding.balloonWrapper) {`
`      (layoutParams as ViewGroup.MarginLayoutParams).setMargins(`
`        builder.marginLeft,`
`        builder.marginTop,`
`        builder.marginRight,`
`        builder.marginBottom,`
`      )`
`    }`
`  }`

When you click on the margin you are clicking outside of balloon_content and balloon_wrapper, but you are still inside the balloon and PopupWindow.

To solve this issue we would need to add something like this code inside of setOnBalloonOutsideTouchListener function:
`if (event.action == MotionEvent.ACTION_UP) {`
`            if(binding.balloonWrapper.getViewPointOnScreen().x > event.rawX) {`
`              if (builder.dismissWhenTouchOutside) {`
`                this@Balloon.dismiss()`
`              }`
`              onBalloonOutsideTouchListener?.onBalloonOutsideTouch(view, event)`
`              return true`
`            }`
`          }`
This only deals with leftMargin, other margins would require additional code.

**Comment by skydoves** [comment]
Hey @NaveenKadiyala, this issue has been addressed in the new version, 1.6.4. Thank you for reporting this issue and your patience!
