### ISSUE TITLE
1.6.0 version not work for Java

### ISSUE THREAD

**Issue by MKadykov** [skydoves/Balloon#495]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Hey @MKadykov, would you share a clearer explanation for this? I'm also wondering which version of Java you use. Within 1.6.0, you should use Java 11 or higher.

**Comment by MKadykov** [comment]
Hello!

I set the value to Java 11, but it didn't help. When I change the Balloon
version to 1.6.0, Android Studio does not see this library.
[image: image.png]
I am using the following configuration:

Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Sincerely, Michael

ср, 20 сент. 2023 г. в 09:46, Jaewoong Eum ***@***.***>:

**Comment by skydoves** [comment]
Hmm, this is very weird. I've never seen this issue before in my Java projects. Have you installed a newer version of Android Studio? I recommend you using at least Android Studio Giraffe: https://developer.android.com/studio/releases

**Comment by MKadykov** [comment]
Thanks!
Updating Android Studio to Giraffe helped!

пт, 22 сент. 2023 г. в 03:59, Jaewoong Eum ***@***.***>:

**Comment by skydoves** [comment]
I'm happy to hear that! Thanks for reporting this issue.
