### ISSUE TITLE
Full screen width is not applied

### ISSUE THREAD

**Issue by alexanderfilipzik** [skydoves/Balloon#499]
- Library Version [v1.6.0]
- Affected Device(s) [every device]
 
**Describe the Bug:**

- try to display a popover with full width
````
val builder = rememberBalloonBuilder {
    setArrowSize(arrowSize)
    setWidthRatio(1f)
    setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
  }

Balloon(
      builder = builder,
      balloonContent = {
        Column(
          modifier = Modifier.fillMaxWidth(),
          horizontalAlignment = Alignment.CenterHorizontally,
        ) {
          Text("test")
        }
      },
    ) { balloonWindow ->
      ....

````
Brown is background of the screen, grey is the background from AndroidStudio.
<img width="410" alt="image" src="https://github.com/skydoves/Balloon/assets/47328778/48be0232-c390-4e8b-a249-e4582d97a4ff">

i think the issue is coming from this line here https://github.com/skydoves/Balloon/blob/e8c82119d3de8f5eef0ce72eeed086773d5ad8ce/balloon-compose/src/main/kotlin/com/skydoves/balloon/compose/Balloon.kt#L135

**Expected Behavior:**

When i use `balloonWindow.showAlignTop()` or `balloonWindow.showAlignBottom()` the arrowSize shouldn't be substracted

**Comment by skydoves** [comment]
Hey @alexanderfilipzik, the new release 1.6.1 resolves this issue. Thanks for reporting this issue!
