### ISSUE TITLE
Balloon width no longer shrinks to fit text.

### ISSUE THREAD

**Issue by gavingt** [skydoves/Balloon#50]
On versions prior to 1.17, if we didn't set a specific width or width ratio, the Balloon's width would match the text contained inside it. As of 1.17, not specifying a width or width ratio sets the Balloon's width to about 90% of the screen.

I'd like it to work like a Toast, where I don't have to specify the width beforehand. 

![Screenshot_1589730637](https://user-images.githubusercontent.com/24281417/82153344-b5366000-981b-11ea-8548-154842064dd5.png)

**Comment by skydoves** [comment]
Hi, @gavingt 
I just re-published the `1.1.7` version.
Please run below command and rebuild your project.
```
./gradlew build --refresh-dependencies
```

**Comment by gavingt** [comment]
Fixed! Thanks for your hard work and your quick solution.
