### ISSUE TITLE
Latest 1.1.7 version is not on jitpack

### ISSUE THREAD

**Issue by NikoBoerger** [skydoves/Balloon#51]
Hi,
thank you for republishing the 1.1.7 version and fixing my issue. I just downloaded the jar directly from jitpack (https://jitpack.io/com/github/skydoves/Balloon/1.1.7/Balloon-1.1.7-sources.jar) and it is still the old 1.1.7 version, where getMeasureTextWidth() in Balloon.kt does not have a parameter yet.

Do you know, why that is the case?

Thank you!

**Comment by skydoves** [comment]
Could you build again using the [aar file](https://github.com/skydoves/Balloon/releases/tag/1.1.7)?

**Comment by NikoBoerger** [comment]
Yes I can do that later, but of course I would rather use it from jitpack. Will the 1.1.7 version on jitpack remain the older version?

**Comment by skydoves** [comment]
I recommend you to download the library from the [maven](https://bintray.com/devmagician/maven/balloon/1.1.7) instead of jitpack.

**Comment by NikoBoerger** [comment]
Okay, thank you!
