### ISSUE TITLE
Compose: arrow position is wrong

### ISSUE THREAD

**Issue by alexanderfilipzik** [skydoves/Balloon#514]
**Please complete the following information:**
- v1.6.1
- all?
maybe related to https://github.com/skydoves/Balloon/issues/413
 
**Describe the Bug:**

The arrow is not correctly pointing to the middle of anchor.

**Expected Behavior:**

The arrow is correctly pointing to the middle of anchor.

```
      val builder = rememberBalloonBuilder {
        setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        setArrowPosition(0.5f)
        setMarginHorizontal(12)
      }

      var balloonWindow1: BalloonWindow? by remember { mutableStateOf(null) }

      Column {
        Spacer(modifier = Modifier.height(300.dp))
        Box(
          modifier = Modifier
            .padding(horizontal = 12.dp) // changing this to a larger value like 36.dp will work for the arrow
        ) {
          Balloon(
            builder = builder,
            balloonContent = {
              Text(
                modifier = Modifier.fillMaxWidth(),
                text = "Now you can edit your profile1 profile2 profile3 profile4",
                color = Color.White,
              )
            },
          ) { balloonWindow ->
            LaunchedEffect(key1 = Unit) {
              balloonWindow1 = balloonWindow
            }

            Button(
              modifier = Modifier


                .padding(horizontal = 0.dp)
                .size(48.dp, 48.dp),
              onClick = { balloonWindow1?.showAlignTop(yOff = 20) },
            ) {
              Text(text = "|")
            }
          }
        }
      }
```
12.dp:
<img width="621" alt="Bildschirmfoto 2023-10-19 um 09 54 24" src="https://github.com/skydoves/Balloon/assets/47328778/e33ba7ed-e5ac-4d0b-b5ca-5ebdd3d8d378">

36.dp:
<img width="631" alt="Bildschirmfoto 2023-10-19 um 09 54 40" src="https://github.com/skydoves/Balloon/assets/47328778/75446800-6b7a-45f1-ad2f-af7ad1dfee23">

**Comment by alexanderfilipzik** [comment]
heyho @skydoves  :) do you have any news on that - the impact is huge if you have more padding in the inside and have larger text and other content on the screen. Happens more often than you expect

**Comment by skydoves** [comment]
Hery @alexanderfilipzik, sorry for the delayed response. A new version 1.6.4 has been released, and I'm wondering if this issue still happens in that version.
