### ISSUE TITLE
How to Fix Popup Position When Scroll?

### ISSUE THREAD

**Issue by jminie-o8o** [skydoves/Balloon#519]
**Is your feature request related to a problem?**

I show Popup, make it stay(make it not dissmiss) regardless of touch by giving it both `setDismissWhenTouchOutside` and `setDismissWhenClicked` values of `false`

Then I scroll, but tooltip moves with scrolling.

I want tooltip to be pinned at the screen.

Is There any way to tooltip to be pinned at the screen?

<br>

Problem Vidio

https://github.com/skydoves/Balloon/assets/79504043/0b99965a-4924-4d17-9036-9e54e03c67f6

**Comment by skydoves** [comment]
Hi @jminie-o8o, could you please provide more details about the example? Specifically, when you mention "pinning on the screen," do you mean fixing the popup to the entire mobile screen, or should it be anchored to a specific view?

I'm also curious about the anchor view you used to display the balloon. By default, the balloon popup should be fixed to specific coordinates depending on your anchor view and contained within that view's window. This means the balloon popup should be movable, especially when using an anchor view rendered inside a scrollable component, as shown in the image below:

![balloon-scrollview](https://github.com/skydoves/Balloon/assets/24237865/00e5fe5e-b84e-46bf-9d1b-99ba4a09120f)

However, if you want to fix the balloon to the screen, you should use the scrollview as an anchor view. In that case, the expected result should be like this:

![balloon-over-scrollview](https://github.com/skydoves/Balloon/assets/24237865/e18dc4eb-2497-491d-89f7-ff784e8e9e96)

So the key part is which anchor view you use decides the entire behavior.

I hope my response can assist you in resolving your issue. Thank you!

**Comment by jminie-o8o** [comment]
Hi Thank you for answer @skydoves  

The yellow balloon at second video is exactly I want!!! 

Can you tell me how to do that?

**Comment by skydoves** [comment]
Hey @jminie-o8o, as I replied in an email, this issue has been addressed in the recent release (1.6.4). There's another janky issue related to this, as you've created on #570; I will take a look at it once I have some time. Thank you for your reporting this issue!

**Comment by jminie-o8o** [comment]
@skydoves Thanks a lot!
