### ISSUE TITLE
Compose: provide the way to get the end of the sequentially showed balloons. 

### ISSUE THREAD

**Issue by Monabr** [skydoves/Balloon#525]
I need to show tooltips after first open app only one time. I am using "Show up Balloon Sequentially" but how can I get the end of this? I need to write it only after last balloon is dismissed. This is because of recomposition. The last balloon will be canceled too early because of my property will change view in compose.

**Comment by skydoves** [comment]
Hey @Monabr, you can control sequential balloons more accurately by using `await_` functions.

```kotlin
coroutineScope.launch {
  customListBalloon.awaitAlignBottom(anchorView)
  customProfileBalloon.awaitAlignBottom(circleImageView, 0, 0)
  customTagBalloon.awaitAlignTop(bottomNavigationView, 130, 0)
}
```

**Comment by skydoves** [comment]
You can use the `setOnBalloonDismissListener` for listening a specific balloon was closed. You can only set the listener for the last one.

**Comment by skydoves** [comment]
Ah, then this should be reported as a bug. I will let you know for the updates soon.

**Comment by skydoves** [comment]
This issue has been fixed in the current [snapshot version](https://github.com/skydoves/Balloon#snapshot). It will be contained in the next stable release. Thanks for reporting this!

**Comment by skydoves** [comment]
Thanks for pointing out this issue @Monabr. In the next release, you can use the `setOnDismissListener` regardless of the internal usage.

**Comment by skydoves** [comment]
@Monabr 1.6.3 has been released, and now `setOnDismissListener` works as you expected. Thanks for reporting this issue 👍
