### ISSUE TITLE
Device becomes unresponsive on Android 9 and below

### ISSUE THREAD

**Issue by jonasskold** [skydoves/Balloon#528]
**Please complete the following information:**
- Library Version v1.6.0
- Affected Device(s): Any device running Android 9.0 and below
 
**Describe the Bug:**

When showing a compose view that contains a Balloon with a compose balloonContent, the whole device gets unresponsive and/or restarts.

Snippet that reproduces the issue:
```
Balloon(
    builder = rememberBalloonBuilder {},
    balloonContent = {
        Text("Balloon")
    }
) {
    Text("Content")
}
```
The issue does not appear if I remove the `balloonContent` and set a text for the balloon in the `rememberBalloonBuilder` block.

Version 1.5.4 of the library does not have this issue.

**Expected Behavior:**

The device should not become unresponsive

**Comment by skydoves** [comment]
Hey @jonasskold, have you ever tried to build with over 1.6.0?

**Comment by jonasskold** [comment]
Hey! Yes, 1.6.1 has the same issue

**Comment by skydoves** [comment]
Hmm, this is interesting. Does any other Android devices work well with 1.6.1? Let me build with Android 9 later. I don't have any Android 9 device at the moment, maybe need to install an emulator.

**Comment by jonasskold** [comment]
All devices and emulators I've tried that runs Android 10+ works as expected with 1.6.1
