### ISSUE TITLE
.setDismissWhenTouchOutside(false) doesn't work

### ISSUE THREAD

**Issue by Testator** [skydoves/Balloon#53]
Hi

I am trying to disable dismiss altogether because i am using it to show delete progress.

.setDismissWhenTouchOutside(false) doesn't seem to work. I am able to still dismiss when touching outside.

Removing .setDismissWhenTouchOutside() has the same effect.

I can still dismiss when touch outside.

Please help

thanks in advance

**Comment by skydoves** [comment]
Use `setFocusable(false)`. Check this [release](https://github.com/skydoves/Balloon/releases/tag/1.1.6).
But I think the functionality must be fixed or removed on the next release.
Thanks :)
