### ISSUE TITLE
Bootlop using skydoves

### ISSUE THREAD

**Issue by zenyagami** [skydoves/Balloon#531]
**Please complete the following information:**
- Library Version: `1.6.1`
- Affected Device(s) couple of them mainly unkown/cheap brands
 
**Describe the Bug:**

I can't repdroduce the bug,it works fine on my device and most of device, but I have some people reporting that my app was causing a bootlop, I updated several libraries and I had to rollback, one user helped me, and I sent a lot of APKS and in each one I updated one of the libraries in order to see which one was causing the issue, apparently skydoves is the one causing the bootlop.
Sadly I can't get more logs because teh device reboots and I don't own any device where this happens so I Can't connect to my laptop and check the logs. Most of the users have a head unit so porbably something with the native code? or processor? I'm not sure here is one of the affected
Board: ums512_1h10
Database enabled :true
Brand: SPRD
Device: ums512_1h10
Manufacturer: sprd
Hardware: ums512_1h10
Model: ums512_1h10_Natv
Product: ums512_1h10_Natv

**Expected Behavior:**
version `1.5.4` was working correctly and without issues.

**Comment by skydoves** [comment]
@zenyagami 1.6.3 has been released, and it resolves this issue. Thanks for your reporting!
