### ISSUE TITLE
Showing balloon while typing

### ISSUE THREAD

**Issue by rezafaraji93** [skydoves/Balloon#534]
- Library Version [v1.6.2]
- Affected Device(s) [Android 7 - 14]
 
**Describe the Bug:**

I am showing the balloon on top of a textfield. I want to show balloon to user to view some instructions while user is typing, but whenever the balloon appears it blocks user from typing and entering anything.

**Expected Behavior:**

I want the balloon to be shown on my textfield and not blocking user from typing words into textfield.

**Comment by skydoves** [comment]
Hey @rezafaraji93, sorry for the late response. Is this about Jetpack Compose?

**Comment by rezafaraji93** [comment]
Yes, it is for Jetpack Compose.
@skydoves

**Comment by skydoves** [comment]
You can add these options to your `Balloon.Builder`.

```kotlin
setDismissWhenClicked(false)
setDismissWhenTouchOutside(false)
```

The balloon will not be dismissed while you're typing or doing any other interaction out of the balloon.

**Comment by rezafaraji93** [comment]
The problem is not that balloon dismisses, It just blocks users from entering keyboard and any character.

**Comment by skydoves** [comment]
Hmm, I got it. I think Balloon took a focus over the TextField. Would you give a focus on your TextField using `FocusRequester` after displaying Balloon??

**Comment by rezafaraji93** [comment]
I will try it!
