### ISSUE TITLE
Check box inside layout custom menu.

### ISSUE THREAD

**Issue by FacuBayo** [skydoves/Balloon#542]
Is it possible to place a checkbox inside a baloon menu? I want to make a menu similar to the one in the image but the checkboxes are not displayed.

![image](https://github.com/skydoves/Balloon/assets/54460617/6a2f4725-89f4-4ec8-bbb8-6d21b81eb368)

**Comment by skydoves** [comment]
You can use Checkbox inside Balloon by using a custom layout. Simply test by adding a checkbox with the demo app: https://github.com/skydoves/Balloon/tree/main/app
