### ISSUE TITLE
Shadow have its left and right shadow clipped

### ISSUE THREAD

**Issue by greg0702** [skydoves/Balloon#557]
**Please complete the following information:**
- Library Version: 1.5.2
- Affected Device(s): All 
 
**Describe the Bug:**

The shadow of balloon on the left and right side are being clipped after setting elevation. (Could it be we are not using the latest version?)

Code to reproduce:

```
Balloon.Builder(context)
                .setWidth(BalloonSizeSpec.WRAP)
                .setHeight(BalloonSizeSpec.WRAP)
                .setTextForm(text)
                .setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
                .setArrowOrientationRules(ArrowOrientationRules.ALIGN_ANCHOR)
                .setArrowSize(0)
                .setArrowPosition(0.6f)
                .setArrowOrientation(arrowPos)
                .setArrowElevation(0)
                .setPadding(12)
                .setCornerRadius(8f)
                .setElevation(12)
                .setBalloonAnimation(BalloonAnimation.FADE)
                .setLifecycleOwner(lifecycleOwner)
                .build()
```

Screenshot of issue faced

![image](https://github.com/skydoves/Balloon/assets/57178991/dba0b7c7-de27-4953-b043-7a7691b955f8)

**Expected Behavior:**

The shadow should not be clipped.

**Comment by nkhar** [comment]
> (Could it be we are not using the latest version?)

Hello @greg0702
I copied the snippet you have provided and could not reproduce it on my device.
Have you tried the latest version ([1.6.3](https://github.com/skydoves/Balloon/releases/tag/1.6.3)) to see if it fixes the problem?

**Comment by greg0702** [comment]
Hello @nkhar,

Thanks for the reply. We will try to get the latest version and check again soon.

Thank you.

**Comment by greg0702** [comment]
Hello @nkhar,

We have tested with the latest version, seems like if we set the arrow orientation to either start or end will cause the issue to happen. For now, we change the orientation to bottom or top and the clipping disappear. Not sure why this happen thou lol

**Comment by greg0702** [comment]
Hello @nkhar,

We have checked through the documentation and found that what have caused the problem is how we try to hide the arrow, we should have use setIsVisibleArrow(false) instead of trying to set the arrow size to 0. I will close this issue now and thanks for your time to check it out.

**Comment by nkhar** [comment]
Sorry for the late reply, had a long day at work. Glad to know you have managed to solve your issue.

At this point I am not sure why setting the arrow size to 0 would cause such behaviour. I will look farther into this and provide feedback here at some point in the future.
