### ISSUE TITLE
Arrow position in the center of the view. Wrap content

### ISSUE THREAD

**Issue by emilianocds** [skydoves/Balloon#56]
**Is your feature request related to a problem?**

1. I have a button and when I tap I want to display the ballon at the top. I added at the top of the button but I cannot set the arrow at the center of the button. How I can set the arrow at the center/top of the button? Without using arrow position, bc in some cases I do not know where is the position of the center of the button.

2. What value I have to set to see the ballon with width wrap content ? bc the text is cutting off.

**Describe the solution you'd like:**

-

**Describe alternatives you've considered:**

-

**Comment by skydoves** [comment]
duplicated #47
