### ISSUE TITLE
The balloon is swallowing keyboard input.

### ISSUE THREAD

**Issue by admund** [skydoves/Balloon#573]
**Please complete the following information:**
- Library Version 1.5.4
- Affected Device: Oppo A5 2020
 
**Describe the Bug:**

The balloon is swallowing keyboard input.

https://github.com/skydoves/Balloon/assets/1122606/b118f3e9-077b-4b62-a0ae-538a558f1a5f

**Expected Behavior:**

Do you think this is expected? I believe, at minimum, we should be able to close the balloon when the User starts typing.

**Comment by skydoves** [comment]
It's expected behaviors with the default settings. You can prevent the balloon from taking focusable and keep allow users to interact with the edit text by using the functions below:

```kotlin
setDismissWhenTouchOutside(false)
setDismissWhenClicked(false)
```

**Comment by skydoves** [comment]
I'm closing this issue now. If you still face the same problem with the suggestion above, please feel free to reopen this. Thanks!
