### ISSUE TITLE
can i set width and height dynamically? 

### ISSUE THREAD

**Issue by HanDongWookNoteing** [skydoves/Balloon#581]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

can i set width and height dynamically?

**Expected Behavior:**

For example, softkeyboard up/down, screen orientation change i want to change height of Balloon but i can't find any ways

**Comment by skydoves** [comment]
You can update width width and height size by using `balloon.update(..)` method.

**Comment by HanDongWookNoteing** [comment]
Thank you~

**Comment by HanDongWookNoteing** [comment]
can i update balloon width or height while balloon is visible?
