### ISSUE TITLE
Compose Balloon position is misplace 

### ISSUE THREAD

**Issue by waheedkhan-dev** [skydoves/Balloon#586]
**Please complete the following information:**
- Library Version [e.g. 1.6.4]
- Affected Device(s) [e.g. Samsung Galaxy s9 with Android 8.0]
 
**Describe the Bug:**

I am using Balloon in my compose project. Library is working fine on above android 10 but when i test it on android 8 it behave like this 

<img width="455" alt="image" src="https://github.com/skydoves/Balloon/assets/55230825/cca6fd23-0e3e-4720-8f6f-709edf502b60">

**Comment by skydoves** [comment]
Hey @waheedkhan-dev, thanks for reporting your issue.

Would you share your code base and the expected result? Thank you!

**Comment by waheedkhan-dev** [comment]
MY Balloon Content look like this 

 val builder = rememberBalloonBuilder {
        setArrowSize(10)
        setArrowPosition(0.5f)
        setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
        setWidth(BalloonSizeSpec.WRAP)
        setHeight(BalloonSizeSpec.WRAP)
        setPadding(12)
        setMarginHorizontal(12)
        setCornerRadius(8f)
        setIsVisibleOverlay(true)
        setBackgroundColorResource(R.color.white)
        setOverlayColorResource(R.color.app_secondary)
        setBalloonAnimation(BalloonAnimation.ELASTIC)

    }

    Balloon(
        builder = builder,
        balloonContent = {
            Text(
                toolTipText,
                style = TextStyle(
                    fontFamily = workSansFamily,
                    fontWeight = FontWeight.Normal,
                    fontSize = 12.sp,
                    color = MaterialTheme.colorScheme.secondary,
                    textAlign = TextAlign.Start
                )
            )
        }
    ) { balloonWindow ->
        IconButton(onClick = {
            balloonWindow.showAlignTop()
        }) {
            Icon(
                painter = icon,
                contentDescription = null,
                tint = MaterialTheme.colorScheme.secondary
            )
        }
    }

Expecxted result 
<img width="296" alt="image" src="https://github.com/skydoves/Balloon/assets/55230825/e321d686-b078-47a2-9286-6fcee92fbdf3">

**Comment by TomTruyen** [comment]
@skydoves it seems that since the latest version something with the positioning has broken. 

I had to upgrade to 1.6.4 to get the setWidthRatio to work as it didn't before, but since 1.6.4 the alignment does not work correctly anymore

**Comment by jasminvucelj** [comment]
Can confirm, offsets and positions are broken on 1.6.4 with Compose, had to downgrade to 1.6.3 to get it to work.

**Comment by skydoves** [comment]
Hey guys, balloon 1.6.5 has been released. Would you please check it out to see if this issue still occurs? Thank you!

**Comment by waheedkhan-dev** [comment]
Ok let me check
