### ISSUE TITLE
Compose elements with `fillMaxWidth()` are cut on the edge

### ISSUE THREAD

**Issue by admund** [skydoves/Balloon#587]
**Please complete the following information:**
- Library Version: 1.6.4
- Affected Device: Oppo A5
 
**Describe the Bug:**

My ballonContent
```
@Composable
fun BalloonContent() {
  Column {
    Text(text = "description")
    Text(
      modifier = Modifier
        .fillMaxWidth()
        .padding(end = 0.dp),
      text = "fillMaxWidth",
      textAlign = TextAlign.End
    )
    Box(
      modifier = Modifier
        .fillMaxWidth()
        .padding(end = 0.dp),
      contentAlignment = Alignment.CenterEnd
    ) {
      Text(text = "centered end")
    }
    Box(
      modifier = Modifier.fillMaxWidth(),
      contentAlignment = Alignment.CenterEnd
    ) {
      Button(onClick = { }) {
        Text(text = "button")
      }
    }
  }
}
```

Looks like that:
![Screenshot 2024-01-30 at 09 38 10](https://github.com/skydoves/Balloon/assets/1122606/8eca4002-3ce8-4d0f-8742-1d411f53a944)
![Screenshot 2024-01-30 at 09 38 25](https://github.com/skydoves/Balloon/assets/1122606/7dd46f5c-22a7-4ae3-9f21-cdb8b4b84ae8)

I used a sample app from this lib.

It looks like a Compose issue, but maybe somebody found a workaround for that (different than adding padding on the end).

I have a similar problem with our production app but with height. Not able to reproduce it in the sample app.
<img width="457" alt="Monosnap Samsung Galaxy J7 Prime v8 1 2024-01-29 10-31-27" src="https://github.com/skydoves/Balloon/assets/1122606/c7915c89-2ef4-48d6-9868-6df18c6baf41">

**Expected Behavior:**

Compose elements are not cut on edge 😏

**Comment by thproflord** [comment]
Getting similar results with long texts
![image](https://github.com/skydoves/Balloon/assets/23272313/4d3f4b8a-b48b-42f1-a4ec-e46b2d6e8d16)
![image](https://github.com/skydoves/Balloon/assets/23272313/2f30b0bb-1a1a-4941-a793-3db971e6df47)

maybe somethiing I'm missing?

`var balloonWindow: BalloonWindow? by remember { mutableStateOf(null) }
                    val builder = rememberBalloonBuilder {
                        setArrowSize(20)
                        setWidthRatio(0.8f)
                        setHeight(BalloonSizeSpec.WRAP)
                        setArrowOrientation(ArrowOrientation.TOP)
                        setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
                        setPadding(12)
                        setMarginHorizontal(12)
                        setCornerRadius(8f)
                        setBackgroundColor(Color.White)
                        setIsVisibleOverlay(true)
                        setOverlayShape(BalloonOverlayCircle(radius = 48f))
                        setOverlayColor(lc.getColor(R.color.ballonOverlay))
                    }
                    Box(Modifier.padding(end = 8.dp)) {
                        Balloon(
                            builder = builder,
                            onBalloonWindowInitialized = { balloonWindow = it },
                            balloonContent = {
                                Column {
                                    Text(
                                        text = LanguageManager.getString(
                                            LanguageManager.languageManager?.calendar?.main?.tooltip?.title,
                                            lc.resources.getString(R.string.calendar_tooltip_title)),
                                        fontSize = 16.sp,
                                        color =  Color.Black,
                                        fontFamily = FontFamily(
                                            Font(R.font.gds_bold)
                                        )
                                    )
                                    Text(
                                        text = LanguageManager.getString(
                                            LanguageManager.languageManager?.calendar?.main?.tooltip?.body_singular,
                                            lc.resources.getString(R.string.calendar_tooltip_body_singular)),
                                        fontSize = 16.sp,
                                        color =  Color.Black,
                                        fontFamily = FontFamily(
                                            Font(R.font.gds_regular)
                                        )
                                    )
                                }

                            },
                        ) {
                            Box(modifier = Modifier.size(36.dp)) {
                                IconButton(onClick = { viewModel.onUIEvent(CalendarViewModel.CalendarUiEvent.OnNotificationsPressed) }) {
                                    Icon(
                                        modifier = Modifier.size(28.dp),
                                        imageVector = Icons.Outlined.Notifications,
                                        contentDescription = "Localized description"
                                    )
                                }
                                if (upcomingEventCount > 0) {
                                    if(viewModel.showBallon) {
                                        viewModel.showBallon = false
                                        balloonWindow?.showAlignBottom()
                                    }
                                    Badge(
                                        modifier = Modifier.align(Alignment.TopEnd),
                                        containerColor = Color(lc.getColor(tech.atlabs.gds.R.color.red_badge)),
                                        contentColor = Color.White

                                    ) {
                                        Text(text = "$upcomingEventCount")
                                    }
                                }
                            }
                        }
                    }`

**Comment by thproflord** [comment]
same problem with the height

**Comment by yigitozgumus** [comment]
Hello, @thproflord . I came across the same issue earlier. After looking through the codebase, I saw that elevation value is also added to the overall padding of `Balloon`. I guess to make the shadow visible on all sides, padding operations takes `elevation` into the consideration.

```kotlin
private fun initializeBalloonContent() {
  val paddingSize = builder.arrowSize - SIZE_ARROW_BOUNDARY
  val elevation = builder.elevation.toInt()
  with(binding.balloonContent) {
    when (builder.arrowOrientation) {
      ArrowOrientation.START -> setPadding(paddingSize, elevation, paddingSize, elevation)
      ArrowOrientation.END -> setPadding(paddingSize, elevation, paddingSize, elevation)
      ArrowOrientation.TOP ->
        setPadding(elevation, paddingSize, elevation, paddingSize.coerceAtLeast(elevation))

      ArrowOrientation.BOTTOM ->
        setPadding(elevation, paddingSize, elevation, paddingSize.coerceAtLeast(elevation))
    }
  }
}
```

so setting elevation to 0 should make the balloonContent cover the whole width of the screen.

<img width="673" alt="image" src="https://github.com/user-attachments/assets/64d6a356-9bc9-49bb-88a5-af1dcdca57f8">

**Comment by thproflord** [comment]
hello @yigitozgumus just trying your suggestion, worked like a charm. Fixed Width and Height issues, so thank you su much

**Comment by skydoves** [comment]
Hi everyone, the new release 1.6.7 has fixed this issue. Thank you so much for figuring out the solution, @yigitozgumus!

**Comment by maggud** [comment]
@skydoves after this fix I noticed that the elevation is now cropped if you add margin. I can't give a good sample right now, but I would think it might be worth investigating if the elevation padding should be moved somewhere else, like to the balloonWrapper, instead of just setting it to 0, because setting it to 0 will leave no room for elevation shadows :)
