### ISSUE TITLE
Corner radius not set properly 

### ISSUE THREAD

**Issue by vijay81** [skydoves/Balloon#595]
**Please complete the following information:**
- Library Version [v1.6.3]
 
**After set corner radius programmatically than some of that corner color not reflet**

Add a clear description about the problem.

**Expected**:
**Set corner radius as passed without any other background color**

```
new Balloon.Builder(context)
                .setLayout(customView)
                .setCornerRadius(10.0F)
                .setHeight(getHeight())
                .setWidth(getWidth())
                .setWidthRatio(widthRatio)
                .setIsVisibleArrow(isArrowVisible)
                .setArrowSize(16)
                .setArrowColor(ContextCompat.getColor(context, R.color.bg_side_menu))
                .setArrowPositionRules(ArrowPositionRules.ALIGN_BALLOON)
                .setBalloonAnimation(BalloonAnimation.OVERSHOOT)
                .setIsVisibleOverlay(true)
                .setDismissWhenClicked(true)
                .setDismissWhenTouchOutside(false)
                .setDismissWhenOverlayClicked(false)
                .setOverlayColorResource(R.color.transparent)
                .setOnBalloonOverlayClickListener(() -> {
                    dismiss();
                    listener.onBottomSheetClick(-1, null, null);
                })
                .setLifecycleOwner(lifecycleOwner);
```

![image](https://github.com/skydoves/Balloon/assets/13793449/69531a0e-e4c2-40fc-9ca5-156f2889bbd8)

**Comment by skydoves** [comment]
Hey @vijay81, it's highly recommended that you use the same background color and content color while building your popup as much as possible. You can fix this with the `setBackgroundColor` or `setBackgroundColorResource` method by aligning the background color and the content color.

**Comment by vijay81** [comment]
@skydoves thanks for response.
