### ISSUE TITLE
JDK8 dependency

### ISSUE THREAD

**Issue by Waboodoo** [skydoves/Balloon#60]
It seems that with [this commit](https://github.com/skydoves/Balloon/commit/15daa88954416e8ba6fbd7e66aceb312e2ba52bc#diff-170cb3b36df498b4877c940c9cb1a03e), which is part of version 1.1.7, you added a dependency that makes the library only work with Java 8 and newer. This is a bit problematic, especially for a patch version update, as it breaks the library for older versions of Android which do not support Java 8 language features.

I have not tested it yet, but I assume this can be fixed by following the steps [here](https://developer.android.com/studio/write/java8-support), but I don't see that mentioned in your library's documentation. If that approach does not work then I will be unable to use this library in my project.

I recommend to either update the documentation, remove the dependency on Java 8 language features, or to change the minSDK version of your library.

**Comment by skydoves** [comment]
Hi, thank you for your issue.
The common java8 SDK library will be changed as below dependency in the next release.
```gradle
androidx.lifecycle:lifecycle-compiler
```

**Comment by skydoves** [comment]
@Waboodoo 
It's also included in the new version [1.1.8](https://github.com/skydoves/Balloon/releases/tag/1.1.8).
Thank you for your issue :)
