### ISSUE TITLE
PopupWindow not seen By Appium

### ISSUE THREAD

**Issue by Wonderjack996** [skydoves/Balloon#600]
Hi.
We have noticed that PopupWindow are not identified by Appium and, in Android Layout Inspector, PopupWindow created with your library are in a different views tree from the page behind. Any idea on how to resolve the problem?
Thanks

**Comment by Susheelkaram** [comment]
Facing same issue, the balloon popup is not a visible in layout inspector, neither visually, nor in component tree.

**Comment by skydoves** [comment]
Hey @Wonderjack996. @Susheelkaram, I don't have experience using Appium yet. Then, how do you guys test any additional windows, such as the bottom sheet?

**Comment by skydoves** [comment]
Thanks for your explanation, @Wonderjack996! Then I will close this issue then.
