### ISSUE TITLE
Make popup reappear in `onResume` after being dismissed in `onPause`

### ISSUE THREAD

**Issue by skywalkerdude** [skydoves/Balloon#618]
**Is your feature request related to a problem?**

1) Enable `setDismissWhenLifecycleOnPause(true)`
2) Gesture up to bring up app drawer (essentially forcing `onPause`)
3) Choose the app
4) Pop up does not reappear

**Describe the solution you'd like:**

Could we have the popup come back in `onResume`, in addition to being dismissed in `onPause`?

**Describe alternatives you've considered:**

Have to manually add it into the fragment's `onResume` and `onPause` methods, which defeat the purpose of setting a `lifecycleOwner`

**Comment by skydoves** [comment]
Hey @skywalkerdude, the biggest purpose of the `setDismissWhenLifecycleOnPause` function is to prevent memory leaks by disposing of popups depending on lifecycle changes. So I'd recommend you just show the popup inside the `OnResume` method.
