### ISSUE TITLE
Balloon display with EditText caused wrong keyboard displaying

### ISSUE THREAD

**Issue by morgansamb** [skydoves/Balloon#62]
Library version: **1.1.7**

I have an EditText with an Input Number type. When the focus is on my EditText, I display the balloon. 
However, displaying the balloon closes the numeric keypad and opens a regular keyboard with characters.

I think the opening of the balloon changes focus and makes my EditText lose focus.

Is it a normal behaviour?

**Comment by skydoves** [comment]
Hi,
Could you run again after using the below method?
```kotlin
.setFocusable(false)
```

**Comment by morgansamb** [comment]
Didn't notice this method, it works as expected now!
Thank you for this!
