### ISSUE TITLE
How can I blur the overlay?

### ISSUE THREAD

**Issue by mehrdadmmb2** [skydoves/Balloon#636]
First, I would like to thank you for this useful and extremely flexible tool.

In the design I received from the UI team, the overlay has a blur effect, but I was only able to add a black color with transparency to it.

Please add the capability to apply a blur style to the overlay, for example:

`setOverlayBlur(radius)`

This would allow us to easily add a blur effect to the overlay.

**Comment by skydoves** [comment]
Duplicated with #634
