### ISSUE TITLE
 There is no way to set different sizes for Arrow

### ISSUE THREAD

**Issue by zuko125** [skydoves/Balloon#64]
I can't set the height and width of the arrow are different
I needed 10 height and 14 width, couldn't do it

I would like to have methods: setArrowHeight and setArrowWidth

tried to use the method
setArrowSize

**Comment by skydoves** [comment]
@zuko125 
Hi, thanks for your issue :)
I'm thinking about this issue, but the size of the arrow should be a square because of calculating the actual size of the popup. Instead, I will include settings of padding (left, top, right, bottom) of the arrow, so you can implement it with this: 14dp arrow size with 2dp left and right side of paddings.

**Comment by zuko125** [comment]
Hi, I saw that setArrowPaddingTop was also done, can I use it to reduce the block overlay on the arrow? The problem is that when I do alpha 0.9, the arrow is superimposed and does not look very good :(
I also wanted to know when the release will be
Sorry for my English, I don't know it well :)

**Comment by zuko125** [comment]
![image](https://user-images.githubusercontent.com/67089409/85100086-a414b080-b218-11ea-8fd2-d405bbaa451c.png)

**Comment by skydoves** [comment]
Hi, It is included in the new release [1.1.9](https://github.com/skydoves/Balloon/releases/tag/1.1.9).
I will consider the alpha issue in the next version.
Thank you for your issue.

**Comment by hayuki** [comment]
Hi @skydoves! First of all, thanks a lot for this library :) I've got a similar issue as @zuko125, and I just wanted to double-check with you: how do I achieve the result of a wide and short arrow, like in this screenshot? Let's say it's got width of 16px and height 8px.
![Imgur](https://i.imgur.com/LkrQRMb.png)

I've tried using the paddings (the arrow top padding helped achieve the space between the anchor view and the arrow 👍 ) but couldn't get the width of the arrow to be bigger than the height... I'd greatly appreciate any help!

**Comment by skydoves** [comment]
Hi, @hayuki.
Could you build again using the below options?
```kotlin
.setArrowSize(16) // should be the desired height size.
.setArrowLeftPadding(4)
.setArrowRightPadding(4)
```
We can shrink the width size of the arrow using the above methods.
### Result in the demo project
![screenshot1190054176](https://user-images.githubusercontent.com/24237865/91472284-2c2acc80-e8d2-11ea-96aa-8e4e18091c59.png)

**Comment by hayuki** [comment]
I've tried your suggestion, @skydoves, using this code:
```
setArrowSize(16)
setArrowTopPadding(4)
setArrowLeftPadding(4)
setArrowRightPadding(4)
```
But the result came our pretty much the opposite of what I'm trying to achieve: the arrow is tall and narrow, when I'm looking to make it short and wide. Here's the image comparison (you can ignore the position of the arrow, it's the arrow shape that I'm struggling with):
| Wanted  | Actual |
| ------------- | ------------- |
| ![Imgur](https://i.imgur.com/NEYhw5U.png)  | ![Imgur](https://i.imgur.com/MCRuOVw.png)  |

> We can shrink the width size of the arrow using the above methods.

I can see that working, but in my case I need to widen the width as opposed to shrinking...

**Comment by NikitaVashchenko** [comment]
> I'm thinking about this issue, but the size of the arrow should be a square because of calculating the actual size of the popup. Instead, I will include settings of padding (left, top, right, bottom) of the arrow, so you can implement it with this: 14dp arrow size with 2dp left and right side of paddings.

Hi @skydoves, As I know your suggestion lead to opposite result. Adding horizontal paddings makes arrow more narrow but issue is to make it wider with the same height

**Comment by vitkhudenko** [comment]
@skydoves,

Just encountered the very same issue. The problem - it is impossible to make the arrow triangle base wider than its height.

**Comment by skydoves** [comment]
@vitkhudenko

Could you try using the `setArrowTopPadding`?

```kotlin
.setArrowSize(16)
.setArrowTopPadding(8) // or .setArrowBottomPadding(8) based on the orientation
```

**Comment by vitkhudenko** [comment]
@skydoves, unfortunately this does not work for me. The effect I observe is that the arrow just gets bigger (following the 16 arrow size) with custom top/bottom padding being ignored:

![image](https://user-images.githubusercontent.com/198951/127304321-fce7ff41-a3ef-4fa6-8534-df2990d4ef20.png)
