### ISSUE TITLE
Ability to align text

### ISSUE THREAD

**Issue by icarapovic** [skydoves/Balloon#65]
As far as I can see there is no way to align text left or right, it is always centered. In cases when there are multiple lines of text it would be nice to have the text aligned left to make reading easier. 

`setTextAlignment(TextAlignment.LEFT)` or `setTextGravity(Gravity.LEFT)`

**Comment by skydoves** [comment]
@icarapovic Hi, thanks for your issue :)
The `setTextGravity(gravity: Int)` functionality will be included in next release!

**Comment by skydoves** [comment]
Hi, It is included in the new release [1.1.9](https://github.com/skydoves/Balloon/releases/tag/1.1.9)!
You can use `setTextGravity` function.
Thank you for your issue.

**Comment by icarapovic** [comment]
Thanks for implementing it!
