### ISSUE TITLE
Balloon content not visible in dark theme

### ISSUE THREAD

**Issue by Breens-Mbaka** [skydoves/Balloon#660]
**Please complete the following information:**
- Library Version [e.g. v1.5.2]
- Affected Device(s): All devices
 
**Describe the Bug:**
The content of the balloon isn't visible in the dark theme

**Expected Behavior:**
The content of the ballon should be visible both in dark and light theme

**Comment by skydoves** [comment]
Hey @Breens-Mbaka, would you describe the details? It would be good if you can contain several code snippets and the result (screenshot). Also, do you use Compose or XML?

**Comment by skydoves** [comment]
The [demo project](https://github.com/skydoves/Balloon/tree/main/app) works well in dark theme since I've only used dark theme on my devices.

**Comment by Breens-Mbaka** [comment]
I use Compose and the issue comes up when my settings default to dark theme the content inside that popup doesn't adapt to the dark theme. 

here is the code and screenshot of the balloon not adapting to the dark theme:

<img width="119" alt="Screenshot 2024-06-24 at 08 44 19" src="https://github.com/skydoves/Balloon/assets/72180010/4cd999da-4ea8-46a8-a73f-dc744cd10149">

<img width="540" alt="Screenshot 2024-06-24 at 08 46 52" src="https://github.com/skydoves/Balloon/assets/72180010/fc893ca8-c532-48d6-a21d-0de8e80c4bc2">

**Comment by skydoves** [comment]
They @Breens-Mbaka, Balloon doesn't apply any Compose theme (Material, Material3, or custom themes), due to providing flexibility to users. So you should apply background color or text color depending on your theme.

```kotlin
balloonContent = {
 Box(modifier = Modifier.background(MaterialTheme.colors.background)) {
  Text(
      color = //
   )
 }
}
```

**Comment by Breens-Mbaka** [comment]
Thanks @skydoves it has worked. I propose maybe this can be explicitly added to the README so that people who have a challenge like mine will be helped and avoid raising issues same issue again. What do you think ? I can create a PR for this if you are okay with it ?

**Comment by skydoves** [comment]
Hey @Breens-Mbaka, thank you for your report and feedback!
