### ISSUE TITLE
getMinArrowPosition brakes the alignment with an anchor

### ISSUE THREAD

**Issue by robertodries92** [skydoves/Balloon#67]
**Please complete the following information:**
- Library Version 1.1.8
- Affected Device(s)  all devices
 
**Describe the Bug:**
with an arrow position of 20 the minimum arrow position the minimum position is too big. lowering this number would fix it. 

![image](https://user-images.githubusercontent.com/3204626/85286135-5b682c00-b492-11ea-810e-16e9ee19b4ee.png)

**Expected Behavior:**
The arrow is correctly aligned above the anchor.

**Comment by skydoves** [comment]
Hi @robertodries92, thank you for your issue.
It seems to need additional functionality to control the margin/padding of the arrow position.
I will think about new functionality for it on next release :)

**Comment by skydoves** [comment]
Hi, It is included in the new release [1.1.9](https://github.com/skydoves/Balloon/releases/tag/1.1.9)!
You can use `setArrowAlignAnchorPadding`/`setArrowAlignAnchorPaddingRatio`.
Add `setArrowAlignAnchorPaddingRatio(1.5f)` or `setArrowAlignAnchorPadding(-15)` to your `Balloon.Builder`.
Thank you for your issue.
