### ISSUE TITLE
Crash Fatal Exception: java.lang.IllegalArgumentException The width of the balloon must bigger than zero.

### ISSUE THREAD

**Issue by kostapostolakis** [skydoves/Balloon#670]
**Please complete the following information:**
- Library Version: com.github.skydoves:balloon-compose:1.6.5
- Affected Device(s):
<img width="564" alt="image" src="https://github.com/user-attachments/assets/f42f31b7-5e9b-4acf-aa22-ae776b90ecc2">

 
**Describe the Bug:**
I have a crash reported in Firebase. I cannot reproduce it. Attached the stacktrace from firebase.
[balloon crash stacktrace.txt](https://github.com/user-attachments/files/16285349/balloon.crash.stacktrace.txt)

I have created this reusable view:

```
@Composable
fun SimpleTooltip(
    context: Context,
    showTooltip: Boolean = false,
    onTooltipDismiss: (() -> Unit)? = null,
    selectedElement: @Composable () -> Unit = {}
) {
    Balloon(
        balloonContent = {
            // Tooltip UI
        },
        builder = rememberBalloonBuilder {
            setWidth(BalloonSizeSpec.WRAP)
            setHeight(BalloonSizeSpec.WRAP)

            setArrowSize(10)
            setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)
            setArrowPosition(0.5f)

            setMarginHorizontal(8)

            setPadding(12)
            setCornerRadius(16f)
            setBackgroundColor(SharedRes.colors.surface.getColor(context))
            setBalloonAnimation(BalloonAnimation.ELASTIC)

            setIsVisibleOverlay(true)
            setOverlayColor(Color(SharedRes.colors.background.getColor(context)).copy(0.8f))
            setOverlayPadding(16f)

            setBalloonHighlightAnimation(BalloonHighlightAnimation.SHAKE)
            setOverlayShape(BalloonOverlayCircle(100f))
            setDismissWhenClicked(true)
        }
    ) { balloonWindow ->
        selectedElement.invoke()

        if (showTooltip) {
            balloonWindow.setOnBalloonDismissListener {
                onTooltipDismiss?.invoke()
            }

            balloonWindow.showAlignBottom()
        }
    }
}
```

**Expected Behavior:**
The app should not crash.

If that helps, all the crashes have been mentioned as "Early crashes", that means that they have occurred at the first 2" of the app launch. But the strange thing is that the class name is not from the name of the main  Activity. 🤔

**Comment by skydoves** [comment]
Hey @kostapostolakis, I don't think calling `showAlignBottom` function directly inside the content, because it can try to display balloon before completely initializing it. Give it a try below or add some delays using the `delay(100)` method.

```kotlin
        ) { balloonWindow ->

          LaunchedEffect(Unit) {
            balloonWindow.awaitAlignBottom()
          }
```

**Comment by kostapostolakis** [comment]
Oh I see. If I call it inside "onBalloonWindowInitialized"?

**Comment by kostapostolakis** [comment]
Trying this also crashes.

```
    var balloonWindow: BalloonWindow? by remember { mutableStateOf(null) }

    val builder = rememberBalloonBuilder {
        ...
    }

    Balloon(
        balloonContent = {
            ...
        },
        onBalloonWindowInitialized = { balloonWindow = it },
        builder = builder,
        content = {
            selectedElement.invoke()

            if (!showTooltip) {
                return@Balloon
            }

balloonWindow?.showAlignStart()
        }
    )
```

**Comment by skydoves** [comment]
@kostapostolakis would you try with the solution below?

```kotlin
      content = { balloonWindow ->
  
          LaunchedEffect(Unit) {
           delay(100) // remove or not
            balloonWindow.showAlignStart()
          }
     }
```

**Comment by kostapostolakis** [comment]
Your solution didn't work. Any other ideas?

**Comment by skydoves** [comment]
Would you able to provide the composable functions inside the `balloonContent` lambda?

**Comment by kostapostolakis** [comment]
I use it in many places, having something like this:

```
IconButton(onClick = { mainGameViewModel.showInstructions() }) {
                    Icon(
                        modifier = Modifier.size(24.dp),
                        painter = painterResource(id = SharedRes.images.outline_info_black_24.drawableResId),
                        contentDescription = null,
                        tint = getKmmColor(id = SharedRes.colors.primaryVariant)
                    )
                }
```

I tried everywhere to set a fixed size, but it did not work.

**Comment by skydoves** [comment]
Hey @kostapostolakis, I'm really not sure what really makes this issue, since I rarely see this issue on the crash reports. Would you please make a very simple project that reproduce this issue on your side?

**Comment by kostapostolakis** [comment]
I cannot reproduce the crash. I can only see it in Firebase.

**Comment by skydoves** [comment]
@kostapostolakis How's the frequency of that issue happens, such as affected device percentages. Does this issue only happens in Android 14 and Xiaomi devices?

**Comment by kostapostolakis** [comment]
The issue happens at 2-6% of the users. I think the percentage is very high. Below you can find the device models and the operation system that happens and it has variety in both of them.

![Screenshot_2024-09-21-11-49-58-161_com.android.chrome.jpg](https://github.com/user-attachments/assets/09ef5e36-3338-4392-8854-4d0580e5a4a9)

![Screenshot_2024-09-21-11-49-53-513_com.android.chrome.jpg](https://github.com/user-attachments/assets/5f51d40e-ec78-499d-b89d-0a750cd4eea2)

**Comment by skydoves** [comment]
@kostapostolakis is there any possibility of the content inside `balloonContent` can be empty with any conditions or something?

**Comment by kostapostolakis** [comment]
@skydoves no, I always add a view inside the content. I do not add conditions and when I do, I add an else statement.

**Comment by kostapostolakis** [comment]
@skydoves in content there is no possibility. In balloonContent there is a possibility, but it is very difficult. Do you want to try to upload a new version with not empty balloonContent?

**Comment by kostapostolakis** [comment]
I think this is the problem. I managed to reproduce the crash when I have no views in balloonContent or the views in the content has not a specific width (for example a Spacer without specifying the width).

I will upload a new version and I will inform you as soon as possible if the crash is still appearing.

**Comment by skydoves** [comment]
@skydoves Thanks for your updates. Please keep me updated if the issue is fixed

**Comment by kostapostolakis** [comment]
It seems that the crash has been resolved. We can close the issue and if it comes again, I will comment again to reopen it. Thank you very much for your support!

**Comment by skydoves** [comment]
@kostapostolakis I'm happy to help out your team!
