### ISSUE TITLE
Support gradient color of overlay padding

### ISSUE THREAD

**Issue by JuliaKostiunina** [skydoves/Balloon#672]
**Is your feature request related to a problem?**

I want to set drawable with gradient color to overlay padding, but currently in this library I can set only colorResource as overlay padding color. It would be great if the library had such an opportunity.

![image](https://github.com/user-attachments/assets/1be54fed-e394-49fe-80b1-af8776975b75)

**Comment by skydoves** [comment]
Hey @JuliaKostiunina, a new version 1.6.8 has been released and now you can achieve this by using the `setOverlayPaddingShader` method on the builder. thank you for your report!
