### ISSUE TITLE
Build afilure after adding ballon library

### ISSUE THREAD

**Issue by alijafari-gd** [skydoves/Balloon#679]
after adding implementation("com.github.skydoves:balloon:1.6.6") to my build.gradle , this happens :
`

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeExtDexMyketDebugAndroidTest'.
> Could not resolve all files for configuration ':app:myketDebugRuntimeClasspath'.
   > Failed to transform appcompat-resources-1.7.0.aar (androidx.appcompat:appcompat-resources:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\83a09bd83a47e2ea7f03ff2010a65ba1\transformed\jetified-appcompat-resources-1.7.0-runtime.jar.
         > Error while dexing.
   > Failed to transform appcompat-1.7.0.aar (androidx.appcompat:appcompat:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\e609751bde91f471739dff4efca4461e\transformed\appcompat-1.7.0-runtime.jar.
         > Error while dexing.
   > Failed to transform fragment-1.8.2.aar (androidx.fragment:fragment:1.8.2) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\f64fa842b7362979ce745b79b9dee703\transformed\fragment-1.8.2-runtime.jar.
         > Error while dexing.
   > Failed to transform fragment-1.8.2.aar (androidx.fragment:fragment:1.8.2) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\f64fa842b7362979ce745b79b9dee703\transformed\fragment-1.8.2-runtime.jar.
         > Error while dexing.
   > Failed to transform fragment-1.8.2.aar (androidx.fragment:fragment:1.8.2) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\f64fa842b7362979ce745b79b9dee703\transformed\fragment-1.8.2-runtime.jar.
         > Error while dexing.
   > Failed to transform fragment-1.8.2.aar (androidx.fragment:fragment:1.8.2) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\f64fa842b7362979ce745b79b9dee703\transformed\fragment-1.8.2-runtime.jar.
         > Error while dexing.
   > Failed to transform fragment-1.8.2.aar (androidx.fragment:fragment:1.8.2) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\f64fa842b7362979ce745b79b9dee703\transformed\fragment-1.8.2-runtime.jar.
         > Error while dexing.
   > Failed to transform lifecycle-livedata-core-2.8.4.aar (androidx.lifecycle:lifecycle-livedata-core:2.8.4) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\b1326c3c7223711478f44fe48f1c95a3\transformed\lifecycle-livedata-core-2.8.4-runtime.jar.
         > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeExtDexMyketDebug'.
> Could not resolve all files for configuration ':app:myketDebugRuntimeClasspath'.
   > Failed to transform appcompat-resources-1.7.0.aar (androidx.appcompat:appcompat-resources:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\83a09bd83a47e2ea7f03ff2010a65ba1\transformed\jetified-appcompat-resources-1.7.0-runtime.jar.
         > Error while dexing.
   > Failed to transform appcompat-1.7.0.aar (androidx.appcompat:appcompat:1.7.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\e609751bde91f471739dff4efca4461e\transformed\appcompat-1.7.0-runtime.jar.
         > Error while dexing.
   > Failed to transform fragment-1.8.2.aar (androidx.fragment:fragment:1.8.2) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\f64fa842b7362979ce745b79b9dee703\transformed\fragment-1.8.2-runtime.jar.
         > Error while dexing.
   > Failed to transform fragment-1.8.2.aar (androidx.fragment:fragment:1.8.2) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\f64fa842b7362979ce745b79b9dee703\transformed\fragment-1.8.2-runtime.jar.
         > Error while dexing.
   > Failed to transform fragment-1.8.2.aar (androidx.fragment:fragment:1.8.2) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\f64fa842b7362979ce745b79b9dee703\transformed\fragment-1.8.2-runtime.jar.
         > Error while dexing.
   > Failed to transform fragment-1.8.2.aar (androidx.fragment:fragment:1.8.2) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\f64fa842b7362979ce745b79b9dee703\transformed\fragment-1.8.2-runtime.jar.
         > Error while dexing.
   > Failed to transform fragment-1.8.2.aar (androidx.fragment:fragment:1.8.2) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\f64fa842b7362979ce745b79b9dee703\transformed\fragment-1.8.2-runtime.jar.
         > Error while dexing.
   > Failed to transform lifecycle-livedata-core-2.8.4.aar (androidx.lifecycle:lifecycle-livedata-core:2.8.4) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\AJ\.gradle\caches\transforms-3\b1326c3c7223711478f44fe48f1c95a3\transformed\lifecycle-livedata-core-2.8.4-runtime.jar.
         > Error while dexing.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

`

**Comment by skydoves** [comment]
Have you ever tried to build after cleaning your project?

**Comment by alijafari-gd** [comment]
version 1.4.7 works fine

my gradle is 7.4.2

**Comment by skydoves** [comment]
That makes sense since the recent version uses higher gradle versions.
