### ISSUE TITLE
Automatic arrow orientation

### ISSUE THREAD

**Issue by ezefire** [skydoves/Balloon#68]
**Is your feature request related to a problem?**

The problem is that when keyboard is shown or the scroll of the view makes show the tooltip in a different position the arrow still with the same orientation. 

**Describe the solution you'd like:**

Add an orientation "Auto" or something like this to make the tooltip detect where is the view and show the arrow with the correct orientation

**Describe alternatives you've considered:**

I think i have no alternatives

**Comment by skydoves** [comment]
Hi @ezefire, thank you for your issue.
The popup can not detect the position of the anchor view dynamically. Detecting changed of view status should be done by each environment, can not in the library. However, I will consider updating the position/orientation of the arrow when you invoke some functionalities like `updateAnchorPosition(view)`/`updateAnchorOrientation(ArrowOrientation)`.

**Comment by ezefire** [comment]
Hi, thanks for your response.
I know what you mean. I will see what can i do. Thank you very much.

**Comment by ezefire** [comment]
I've made a workaround to select where i want to show the tooltip. I think you can use something like that internally so you can have a better calculation using the popup size.

`      int[] screenPos = new int[2];
        this.getLocationInWindow(screenPos);
        int y = screenPos[1];
        boolean showAtBottom = true;
        if (y >= Tools.getScreenHeight(getContext()) / 2) {
            showAtBottom = false;
        }

…
         .setArrowOrientation(showAtBottom ? ArrowOrientation.TOP : ArrowOrientation.BOTTOM)
…
        if (showAtBottom) {
            balloon.showAlignBottom(this);
        } else {
            balloon.showAlignTop(this);
        }
…
`

**Comment by skydoves** [comment]
Thank you for your suggestion :)
Unfortunately, this way can not resolve the issue. 
Because your issue is a dynamic circumstance by showing up the keyboard. So the solution is for working only for the first time to show. (Popupwindow can't listen or observe the changing of the target view's position).

I think this kind of new functionalities could resolve your problem; 
- `allowArrowOrientationAutomatically()`: set anchor of the arrow automatically based on your target view.
- `updateArrowOrientation()`: update your anchor of the arrow based on the `automatic` function when you call manually.

Also, it needs to consider the orientation of the anchor.
Like, if the target view is enough far diagonally (right-bottom) from the balloon, which orientation should be adopted. (right or bottom)

**Comment by ubarua123** [comment]
Apart from keyboards, say we are in a scrollable environment. The anchor will move up and down based on the scroll. How do I calculate how much space is left for the popup and it aligns accordingly.

**Comment by skydoves** [comment]
@ubarua123 
I've been thinking about this problem a few days, the balloon popup is actually totally an independent window from the window of the target view. So I think I will try to implement `moveTo(x, y)` or `moveBy(x, y)` function, then we can update the shown position of the popup. We can update the position using calculated the height size of the keyboard or we can update the position based on the scroll position of the scroll view using this function.

**Comment by ubarua123** [comment]
Actually there are 2 cases:
1. Alignment of the popup above or below the anchor based on the position in the screen.
2. Direction of the arrow. If the position is above the anchor then arrow should point downwards and vice versa.

**Comment by skydoves** [comment]
Hi, it will be added `update(anchor: View)` function in the next release.
`updates popup and arrow position of the popup based on a new target anchor view.`

**Comment by skydoves** [comment]
Hi, @ezefire!
The new release [1.2.1] includes the above new functions.
Thank you for your issue and check it using the new version!
