### ISSUE TITLE
Overlay support for multiple view

### ISSUE THREAD

**Issue by iegemci** [skydoves/Balloon#682]
**Is your feature request related to a problem?**
Yes

A clear and concise description of what the problem is.
I want to add an overlay to my balloon view but need to highlight at least 2 views.

**Describe the solution you'd like:**
There should be a method for excluding views from overlay

To see multiple view on an overlay with 1 balloon view

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

**Comment by skydoves** [comment]
You can set the overlay for highlighting on multiple views.

![Screenshot 2024-09-17 at 9 52 36 PM](https://github.com/user-attachments/assets/827f925a-b562-45de-8243-95b7a9653597)

```kotlin
        editBalloon.showAlign(
          align = BalloonAlign.BOTTOM,
          mainAnchor = circleImageView,
          subAnchorList = listOf(it),
        )
```

Check out the [demo code](https://github.com/skydoves/Balloon/blob/main/app/src/main/kotlin/com/skydoves/balloondemo/CustomActivity.kt#L69).
