### ISSUE TITLE
Any way to customized the balloon animation when showing or dismissing (not the highlight animation)?

### ISSUE THREAD

**Issue by Jason-Lee-1001** [skydoves/Balloon#683]
**Is your feature request related to a problem?**

No

**Describe the solution you'd like:**

In addition to the preset animations, we can also customize the animations.

**Describe alternatives you've considered:**

Maybe more preset animations.

**Comment by skydoves** [comment]
Hey @Jason-Lee-1001, of course, you can apply your own custom animation like the code below:

```kotlin
profileBalloon.bodyWindow.contentView.startAnimation(..) 
```
