### ISSUE TITLE
Support for setting TypeFace type

### ISSUE THREAD

**Issue by michaelbukachi** [skydoves/Balloon#7]
Currently the `setTextTypeface` method takes a `Int` variable. This limits the situations where one wants to use a custom `TypeFace` object when using a custom font.
Can it be possible to add support for custom `TypeFace` objects, perhaps a `setTextTypeface` object which takes `TypeFace` parameter?

**Comment by skydoves** [comment]
@michaelbukachi 
Released the new version `1.0.6`!
Thank you for your issue :)

**Comment by michaelbukachi** [comment]
Awesome! Just tested it. It works perfectly. Thanks! 
I'll close this now.
