### ISSUE TITLE
Allow set text as CharSequence instead of String

### ISSUE THREAD

**Issue by ezefire** [skydoves/Balloon#70]
**Is your feature request related to a problem?**

I need to set a text with different styles(colors, bold, etc) in same text.

**Describe the solution you'd like:**

My suggested solution is to allow pass a CharSequence in the setText() method instead of passing a String.

**Describe alternatives you've considered:**

I have no alternatives to do that

**Comment by skydoves** [comment]
Thank you for your issue :)
Out of curiosity, how about using `SpannableStringBuilder` and `toString` method?

**Comment by ezefire** [comment]
Hi thanks for your response but using SpannableStringsBuilder.toString() makes me loose the wanted spans added to it. I get the default text as i can see in the android doc: "a string representation of the object." .

https://developer.android.com/reference/android/text/SpannableStringBuilder#toString()

**Comment by skydoves** [comment]
Thanks for your description :)
I will add new functionality or change the original `setText(String)` to `setText(CharSequence)` one.
Thanks!

**Comment by skydoves** [comment]
Hi, It is included in the new release [1.1.9](https://github.com/skydoves/Balloon/releases/tag/1.1.9)!
Thank you for your issue :)
