### ISSUE TITLE
Custom layout always same height

### ISSUE THREAD

**Issue by ezefire** [skydoves/Balloon#71]
**Please complete the following information:**
- Library Version 1.1.8
- Affected Device(s) Emulator Nexus 7 API 27
 
**Describe the Bug:**

When I use setLayout() method the view has always a single line height when the tooltip appears.
I create custom view with WRAP_CONTENT for layout_width annd layout_height. The width takes the good size but the heith is always the same even if text should take more than one line.

In the following example I set a normal TextView as custom layout and the text should have more than one line:

<img width="285" alt="Screenshot 2020-06-25 at 16 41 08" src="https://user-images.githubusercontent.com/4618466/85741621-df284f80-b702-11ea-8e3f-24f0d7787c02.png">

My configuration: 
`       Balloon balloon = new Balloon.Builder(getContext())
                .setLayout(tv)
                .setArrowSize(15)
                .setArrowOrientation(ArrowOrientation.TOP)
                .setArrowVisible(true)
                .setElevation(5)
                .setArrowDrawable(ContextCompat.getDrawable(getContext(),R.drawable.tooltip_arrow))
                .setArrowColorResource(android.R.color.transparent)
                .setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
                .setWidthRatio(Tools.isTabletSize() ? 0.7f : 1f)
                .setPadding(Tools.dip(10))
                .setOnBalloonDismissListener(new OnBalloonDismissListener() {
                    @Override
                    public void onBalloonDismiss() {
                        TooltipButton.this.setSelected(false);
                    }
                })
                .setBackgroundDrawableResource(R.drawable.bg_shadow_white)
                .setBalloonAnimation(BalloonAnimation.FADE)
                .build();`

**Expected Behavior:**

The expected behavior is that the Tooltip wraps the content of subview and not limits the height

**Comment by skydoves** [comment]
duplicated (#55)

**Comment by ezefire** [comment]
I've read the other #55 and i saw the suggestion of using a maxWidth. Isn't the property widthRatio the same thing? Cannot be used by you as a maxWidth?

**Comment by skydoves** [comment]
Oh, I see!
The `widthRatio` determines only a width size of the popup based on the device's screen size regardless of the content's size.
So it actually does not relate to the process of measuring content's width.

The popup's height will be measured by content's height size (so we can use without call setHeight manually),
But as you already know, we can't measure the height size of the textView when we don't know the specific width size of the textView.

From this issue, the popup's height size could be different from the measured content's height when we use textView in the custom layout.

**Comment by skydoves** [comment]
Hmm, maybe it can be possible if the balloon sets the custom layout's width as the same popup's one. 
I will think about this issue more :)

**Comment by ezefire** [comment]
I did what you suggested and it words. I set a maxWidth to custom view like this :
`tv.setMaxWidth((int)(0.7f * (Tools.getScreenWidth(getContext()))));`

I think, as you said, that you can verify if the custom view has already a max width and if not, set a max width based on width ratio and paddings.

**Comment by skydoves** [comment]
Hi, it is not the best way.
Traversing all of the view hierarchy for finding TextView and setting the maxWidth is too much costly.
I will think more about this issue. Thanks :)

**Comment by skydoves** [comment]
This is the best way to use `wrap_content` to width/height in your custom layout.

```kotlin
val myTextView = customProfileBalloon.getContentView().findViewById<TextView>(R.id.myTextView)
myTextView.maxWidth = customProfileBalloon.getMeasureWidth()
```

Just find your `TextView` manually and  set max width using `getMeasureWidth()` function.
If I found a better way I will let you know :)
