### ISSUE TITLE
Swipe target view with passTouchEventToAnchor issue

### ISSUE THREAD

**Issue by ahrybuk** [skydoves/Balloon#713]
I have swipeable button, that used as a target. I also set passTouchEventToAnchor = true. 

Problem - when I start swiping everything work as expected, button have actual swipeable state, but if I move finger outside target element I have not receive touch event. 
I think this can happened because of next part in lib

if (rect.contains(event.rawX.toInt(), event.rawY.toInt())) {
        anchor.rootView.dispatchTouchEvent(event)
        true
      } else {
        false
      }

So, whenever swipe goes out of target container I don't receive any event at all and my button "freeze" with "half-swipe" state, even I move my finger out of screen.

**Comment by ahrybuk** [comment]
@skydoves hi, thanks for quick response. 
I mean, it's delegate correctly while you swiping inside target container area, but if swipe starts going outside target area - swipeable button does not receive any event and think that user still touch button in the place, where swipe goes outside target container.

**Comment by skydoves** [comment]
@ahrybuk Thanks for the clarification! This will be fixed on the next release.

**Comment by ahrybuk** [comment]
Nice, thank you.
