### ISSUE TITLE
Make TextView fully configurable

### ISSUE THREAD

**Issue by ezefire** [skydoves/Balloon#72]
**Is your feature request related to a problem?**

I need to set a property directly on TextView, 'setMovementMethod', because i need to show a clickable span in a part of text. 

**Describe the solution you'd like:**

I think there are two posibilities, the first one, add a function specific for this property, 'setMovementMethod', or another solution is to allow access to the textView. I think other people will need configure many things in textView that we don't know.

**Describe alternatives you've considered:**

My alternative was to create a custom TextView, so i can access all properties and customize the whole textview.

**Comment by skydoves** [comment]
Hi, @ezefire sorry for the late reply.
You can get the content of the balloon, and you can access the textView like below.
```kotlin
val textView = balloon.getContentView().findViewById<TextView>(R.id.balloon_text)
```
