### ISSUE TITLE
[Compose] Preview pops up a container in first frame

### ISSUE THREAD

**Issue by GhulJr** [skydoves/Balloon#722]
**Please complete the following information:**

- Library Version: since v1.6.3 (last tested occurrence v1.6.7)
- Affected Device: n/a (it happens in `@Preview`)
 
**Describe the Bug:**

Hello! Recently I updated library to v1.6.7, noticed weird glitch where container pops up in `@Preview`. I thought it is just visual glitch in preview, but sadly it happened to mess up my screenshot tests (using `Paparazzi` + `Showkase` to generate tests from preview). last version without this problem was v1.6.2.

![image](https://github.com/user-attachments/assets/a0a8fb67-c84d-4089-ad11-38c777cfb3fa)

On Preview you can see container (white this time) popping up for a split of second whenever I made change to Composable (thus re-rendering preview).

https://github.com/user-attachments/assets/52c9f17b-da08-4cd4-811e-eec1750bd358

Ballon is wrapped around question mark icon:

```kotlin
Row {
 Text(...)
 Spacer(...)
 Balloon {
     Icon(...)
 } 
}
```

*Note* I don't know whether it happens only in preview or also in production code, didn't notice it, though.

**Expected Behavior:**

Container should not pop up in preview.

**Comment by skydoves** [comment]
Hey @GhulJr, new version 1.6.9 has been released, and it resolves this issue. Thank you for your report!
