### ISSUE TITLE
Different behavior of .setShouldPassTouchEventToAnchor (1.6.7 to 1.6.8)

### ISSUE THREAD

**Issue by RGregat** [skydoves/Balloon#728]
**Please complete the following information:**
- Library Version -> 1.6.8
- Affected Device(s) -> Pixel 6 Pro
 
**Describe the Bug:**
* With version **1.6.7** I was able to passthrough a click event to a button and to dismiss the popup if pressed outside.
* With the latest version **1.6.8** this isn't possible anymore. If I press outside of the popup nothing happens.
* My educated guess is, that this change is responsible for the new behavior (https://github.com/skydoves/Balloon/compare/1.6.7...1.6.8#diff-2f1d0cd206bb446f0d64bb11460fb1d7b4a18344783d7c6ff89b9e63e1641b9bL1833)
* And here is the corresponding Issue: https://github.com/skydoves/Balloon/issues/713

**Expected Behavior:**
* Be able to passthrough a click event to the underlying button and to dismiss the popup if pressed somewhere else.

**Comment by skydoves** [comment]
Hey @RGregat, this issue has been fixed on 1.6.10. Thank you so much for your report!
