### ISSUE TITLE
Arrow not placing first time at right position

### ISSUE THREAD

**Issue by sokolking** [skydoves/Balloon#74]
- Library Version 1.1.9
- Honor 10 Lite
 
So, it's happening not at all devices, but fo my Honor 10lite, when i create Ballon(i'm using lazy load) first time arrow going from start to correct place.
After tan, it's placing correct, but first time - not
![2](https://user-images.githubusercontent.com/13314954/86946793-91283880-c153-11ea-987a-de6d837de0ff.gif)

**Comment by sokolking** [comment]
`        return createBalloon(context) {
            setLayout(R.layout.layout_note)
            setArrowOrientation(ArrowOrientation.TOP)
            setArrowPosition(0.8f)
            setWidthRatio(1f)
            setHeight(context.px2dip(context.percentHeight(0.56F).toInt()).toInt())
            setCornerRadius(20f)
            setBackgroundColor(ContextCompat.getColor(context, R.color.white))
            setBalloonAnimation(BalloonAnimation.FADE)
            setLifecycleOwner(lifecycle)`

**Comment by sokolking** [comment]
return createBalloon(context) {
            setLayout(R.layout.layout_note)
            setArrowOrientation(ArrowOrientation.TOP)
            setArrowPosition(0.8f)
            setWidthRatio(1f)
            setHeight(context.px2dip(context.percentHeight(0.56F).toInt()).toInt())
            setCornerRadius(20f)
            setBackgroundColor(ContextCompat.getColor(context, R.color.white))
            setBalloonAnimation(BalloonAnimation.FADE)
            setLifecycleOwner(lifecycle)

**Comment by skydoves** [comment]
Hi, @sokolking!
Thank you for your issue and it seems to fixed now.
Could you run again using the [demo project](https://github.com/skydoves/Balloon/tree/master/app)?

**Comment by skydoves** [comment]
Hi, @sokolking!
It is fixed in the new version `1.2.0`!
Thank you for your issue :)
