### ISSUE TITLE
Small mistake regarding ArrowPositionRules in README documentation

### ISSUE THREAD

**Issue by ridcully99** [skydoves/Balloon#743]
**Please complete the following information:**

- Library Version 1.6.9
 
**Describe the Bug:**

The documentation on the README page says that ArrowPositionRules.ALIGN_ANCHOR is the default, but in reality the default value is ArrowPositionRules.ALIGN_BALLOON (https://github.com/skydoves/Balloon?tab=readme-ov-file#arroworientationrules)

**Expected Behavior:**

The comment `// Default` should be in the line with ALIGN_BALLOON.

**Comment by skydoves** [comment]
It has been fixed. Thank you @ridcully99 for your valuable contribution!
