### ISSUE TITLE
How to dismiss when touched?

### ISSUE THREAD

**Issue by ffolkes** [skydoves/Balloon#75]
Thank you for making this, and thank you for documenting it so well! Is there a way to make the balloon disappear when tapped inside?

**Comment by skydoves** [comment]
Hi, @ffolkes !
You can get the content of the balloon using the below method.
```kotlin
balloon.getContentView()
```
And you can add the `setOnClickListener` to the content view and you may dismiss or anything.
Thank you :)

**Comment by skydoves** [comment]
You can also use the below method.
```kotlin
.setOnBalloonClickListener(value: OnBalloonClickListener)
```
