### ISSUE TITLE
Keyboard becomes hidden when show Ballon

### ISSUE THREAD

**Issue by AbdElrahman-Rafaat-Amer** [skydoves/Balloon#756]
**Please complete the following information:**
- Library Version [e.g. v1.6.11]
- Affected Device(s) [Any Android Device]
 
**Describe the Bug:**
I have an issue with Ballon. When the balloon is shown, and the keyboard is shown, the keyboard becomes hidden. How can I fix it?

**Expected Behavior:**
The both Ballon & Keyboard should be shown at the same time

The video explains the issue

https://github.com/user-attachments/assets/6a7fc13d-cc90-49cd-b88e-cf87527a1cc5

**Comment by skydoves** [comment]
Hey @AbdElrahman-Rafaat-Amer, would you able to share the `Balloon.Builder` implementation? I'm also wondering if this issue still happens if you add the `setFocusable(false)` method.

**Comment by AbdElrahman-Rafaat-Amer** [comment]
@skydoves Thanks it works now after adding `setFocusable(false)`

This is my builder
```
       val endIcon = findViewById<View>(com.google.android.material.R.id.text_input_end_icon) as CheckableImageButton
        val balloon = Balloon.Builder(this)
            .setText("The name should be 5 chars and not contain numbers")
            .setArrowSize(10)
            .setWidthRatio(0.5f)
            .setHeight(65)
            .setCornerRadius(4f)
            .setAlpha(0.9f)
            .setTextColorResource(R.color.white)
            .setBackgroundColorResource(R.color.black)
            .setFocusable(false)
            .build()

        balloon.showAlignTop(endIcon, 0, 10.toPx().toInt())
```

**Comment by skydoves** [comment]
Awesome! I'm happy to help out with your issue :)
