### ISSUE TITLE
showAlignTop not respected

### ISSUE THREAD

**Issue by ezefire** [skydoves/Balloon#78]
**Please complete the following information:**
- Library Version : 1.1.9
- Affected Device(s) : Nexus 4 
 
**Describe the Bug:**

I'm using showAlignTop and showAlignBottom but it seems sometimes it is not respected and the balloon is shown in other position.

**Expected Behavior:**

The balloon is shown where I indicate

**Comment by ezefire** [comment]
I've made many tests and I saw that it seems the problem is there when the arrow is visible.

**Comment by skydoves** [comment]
Hi, @ezefire!
Could you explain more details about the issue or sample project?
I guess If there is not enough space for showing the balloon over the target view, the balloon will not show exactly on the top.

**Comment by ezefire** [comment]
Hi @skydoves,
I've made a logic to make the balloon appear where there is more space to be shown. I see where is positioned my target view in the screen at the moment of showing the balloon and bassed on that i use showAlingTop or showAlignBottom. 
After that, even if there is more space at the top than at the bottom the balloon is shown at the bottom.

**Comment by skydoves** [comment]
Hi, @ezefire!
It is released in the new release [1.2.1](https://github.com/skydoves/Balloon/releases/tag/1.2.1).
Please check the issue still happening if using the new functions.
Thank you for your issue.
