### ISSUE TITLE
Auto dismiss

### ISSUE THREAD

**Issue by Testator** [skydoves/Balloon#8]
Hi, thanks for the great feature!

Is there a way to auto dismiss or a way to show it for certain amount of time? I tried .setShowTime() but it doesn't work.

I can put it in a runnable but if there is already a way to do it, I rather not.

Thanks in advance.

**Comment by skydoves** [comment]
@Testator 
Hi, `setShowTime` means actually the count of the showings. If you set it as 3, it will be shown only 3 times. I think the naming convention makes confusing.
I recommend you use runnable with delay, but I will consider making feature the delay to show and dismiss.
Thank you :)

**Comment by khizzar** [comment]
Hi, I would also like this auto hide enhancement it will relieve so much coding. Would be very thankful for this.

**Comment by skydoves** [comment]
@Testator @khizzar 
Hi guys, it is released on version `1.0.9`.
You can reference the [setAutoDismissDuration](https://github.com/skydoves/balloon#show-and-dismiss) functionality.
Thank you for your issue!
