### ISSUE TITLE
class file for kotlin.jvm.functions.Function0 not found

### ISSUE THREAD

**Issue by znakeeye** [skydoves/Balloon#80]
In `Android Studio 4.0.1`, create a new **Java** project. Then modify it as follows.

**build.gradle**
```
dependencies {
    // ...
    implementation "com.github.skydoves:balloon:1.1.9"
}
```

**MainActivity.java**
```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // ...
    
    final Balloon balloon = new Balloon.Builder(this).build();
    balloon.setOnBalloonDismissListener(new OnBalloonDismissListener() {
        @Override
        public void onBalloonDismiss() {
        }
    });
}
```

Build the project, and observe the **compilation error**:
> ... MainActivity.java:24: error: cannot access Function0
>         balloon.setOnBalloonDismissListener(new OnBalloonDismissListener() {
>                ^
>   class file for kotlin.jvm.functions.Function0 not found

What am I missing here?

**Comment by skydoves** [comment]
Hi, @znakeeye!
It seems to need You should add Kotlin dependencies to your gradle.

```gradle
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

**Comment by znakeeye** [comment]
Thanks. I should have read the [docs](https://developer.android.com/kotlin/add-kotlin).
