### ISSUE TITLE
Can we get an isShownEvent?

### ISSUE THREAD

**Issue by fvermeulen** [skydoves/Balloon#81]
**Is your feature request related to a problem?**

I want to track the showing of the toolTip, therefore an IsShownListener or sth like this would be cool

**Comment by skydoves** [comment]
Hi, @fvermeulen.
There is no shown listener.
Instead, you can know the content view is inflated using below codes.
```kotlin
myBalloon.getContentView().post {
    Toast.makeText(this, "initialized!", Toast.LENGTH_SHORT).show()
}
```

**Comment by fvermeulen** [comment]
Oh yeah that works fine. Thanks

No listener needed

I will close this issue

Thank you for your help
