### ISSUE TITLE
 setBalloonAnimation(BalloonAnimation.CIRCULAR) seems to be a malfunction

### ISSUE THREAD

**Issue by mtjin** [skydoves/Balloon#85]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy a8 with Android 8.0]
 
**Describe the Bug:**
 When I used setBalloonAnimation(BalloonAnimation.CIRCULAR), 
1. I click view, then clickListener is happend 
2. balloon is shown 
3. I click view one more time
4. The balloon that was shown disappears
5. Then I click view again
6. The balloon is shown and disappears automatically immediately. -> I think it seems to be a malfunction

BalloonAnimation.FADE,  BalloonAnimation.ELASTIC, BalloonAnimation.OVERSHOOT work fine

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main2)

        val balloon = createBalloon(this@MainActivity) {
            setArrowSize(10)
            setWidthRatio(0.5f)
            setHeight(50)
            setWidth(70)
            setArrowOrientation(ArrowOrientation.LEFT)
            setCornerRadius(4f)
            setAlpha(0.9f)
            setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
            setText("EXAMPLE")
            setTextColorResource(R.color.colorWhite)
            setTextIsHtml(true)
            setIconDrawable(
                ContextCompat.getDrawable(
                    this@MainActivity,
                    R.drawable.ic_check_black_24dp
                )
            )
            setBackgroundColorResource(R.color.colorPrimary)
            setBalloonAnimation(BalloonAnimation.CIRCULAR)
            setLifecycleOwner(lifecycleOwner)
        }

        tv_example.setOnClickListener {
            //if(balloon.isShowing) balloon.dismiss()
            balloon.showAlignRight(it,12, 0)
        }
    }
``` 

**Expected Behavior:**
![GIF 2020-08-01 오후 9-15-39](https://user-images.githubusercontent.com/37071007/89101686-2eb61580-d43d-11ea-9453-0ef848c8bc51.gif)

A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Hi, @mtjin!
This issue is fixed in the new release [1.2.1](https://github.com/skydoves/Balloon/releases/tag/1.2.1).
Thank you for your issue and contribution to this library. 👍 
Have a good day.
