### ISSUE TITLE
Dismiss any visible tooltip

### ISSUE THREAD

**Issue by znakeeye** [skydoves/Balloon#87]
I noticed that tooltips might misbehave e.g. when animating a view - the tooltip will jump around a bit, and the arrow might end up in the wrong direction (not the Balloon's fault hehe).

Now, if I know that a certain user initiated intent will cause views to animate (or I just want to prepare for a screenshot etc), it makes sense to dismiss any tooltip.

It would be nice to have a simple static method, closing all visible Balloons:

```
Balloon.dismissAll();
```

**Motivation**
Certainly, this can be achieved by keeping track of all created balloons, but then I need to handle `setOnBalloonDismissListener` and this is where things become interesting:

```
balloon.setOnBalloonDismissListener(() -> mActiveBalloons.remove(balloon));
```

**UPDATE:** I was wrong about the following. The kotlin methods come from the Balloon library itself. Not much to do about that. But having the method above would still be very nice to have!

~~**That single line** requires me to include kotlin, which in turn adds some **8500 methods** to my dex. Not a problem in minified _release_ builds, but in _debug_ mode this puts me above the 64k boundary. Not so nice!~~

~~So, as you can see, implementing this feature in a Java app comes with a great cost.~~

Should be fairly easy to incorporate this in the Balloon library, no?

**Comment by skydoves** [comment]
Hi, @znakeeye, thank you for your issue!
How do you think managing all balloon instance to your local hashmap?
The balloon is an independent window that can not trace each instance.
So If we want to dismiss all balloons, eventually we should hold every instance of the balloon using like `Balloon.addBalloon(balloon)`. So it would not much different just making our local hashmap.
