### ISSUE TITLE
Arrow color and background gradient 

### ISSUE THREAD

**Issue by Glaurock** [skydoves/Balloon#88]
When using a background drawable with a color gradient, the arrow color won't adapt to the gradient depending on its position.

I want to achieve something like this (the arrow blue is adapted to the gradient color): 

<img width="340" alt="Screenshot 2020-08-11 at 10 47 10" src="https://user-images.githubusercontent.com/30554293/89883652-ba137180-dbc8-11ea-948b-e8bb974245ff.png">

Do you have a solution for applying the right color to the arrow ? 
Thank you and good job for that awesome lib

**Comment by skydoves** [comment]
Released a new snapshot `1.3.6-SNAPSHOT`. (#203)

**Comment by skydoves** [comment]
Released a new stable `1.3.6`!
