### ISSUE TITLE
Baloon showing in wrong place using in RecyclerView (GridLayoutManager).

### ISSUE THREAD

**Issue by Equin** [skydoves/Balloon#96]
**Please complete the following information:**
- Library Version  v1.2.1
- Emulator with android 10 and Xiaomi mi 9t pro (android 10)
 
**Describe the Bug:**
When using Baloon in recyclerView with GridLayout manager, on 2 last rows baloon not showing in correct place, jumping to the top of screen.

![image](https://user-images.githubusercontent.com/18736900/92241568-19faf080-eec7-11ea-9665-48b5efb1f795.png)

**Expected Behavior:**
Ballon with arrow should display correctly right above item. 
![image](https://user-images.githubusercontent.com/18736900/92241416-ddc79000-eec6-11ea-9f83-8a0d63ca1505.png)

```
 Balloon balloon = new Balloon.Builder(context)
                .setArrowSize(10)
                .setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
                .setArrowPosition(0.5f)
                .setArrowVisible(true)
                .setArrowOrientation(ArrowOrientation.BOTTOM)
                .setCornerRadius(10f)
                .setWidthRatio(1f)
                .setLayout(R.layout.view_attendance_note)
                .setBackgroundColor(ContextCompat.getColor(context, R.color.white))
                .setBalloonAnimation(BalloonAnimation.FADE)
                .setLifecycleOwner((LifecycleOwner) context)
                .build();

        balloon.showAlignTop(noteIconView);
        balloon.setOnBalloonInitializedListener((view) -> {
       
            imgEdit.setOnClickListener((c) -> {
                balloon.dismiss();
            });

            imgDelete.setOnClickListener((c) -> {
                balloon.dismiss();
            });

            notifyDataSetChanged();
        });

        balloon.setOnBalloonDismissListener(() -> {
            notifyDataSetChanged();
        });
```

**Comment by skydoves** [comment]
Hi, @Equin sorry for the late replay.
Could you explain the details where those codes are written? The Balloon builder is placed in your ViewHolder class?
I tested using the [demo](https://github.com/skydoves/Balloon/blob/master/app/src/main/java/com/skydoves/balloondemo/CustomActivity.kt) project with changed to `GridLayout`, it works fine to me.
