### ISSUE TITLE
RecyclerView content issue

### ISSUE THREAD

**Issue by ueen** [skydoves/Balloon#98]
I used the code from the README and created a layoutfile with just a RecyclerView and tried populate like this

`                          val itemAdapter = ItemAdapter<Item>()
                            val fastAdapter = FastAdapter.with(itemAdapter)

                            val rc: RecyclerView = balloon.getContentView().findViewById(R.id.rc)
                            rc.adapter = fastAdapter
                            rc.layoutManager = LinearLayoutManager(requireContext())
                            rc.addItemDecoration(
                                    DividerItemDecoration(
                                            requireContext(),
                                            LinearLayoutManager.VERTICAL
                                    )
                            )
                           balloon.showAlignBottom(v)`

This works as expected in another RecyclerView in the fragment but the Popup only shows the arrow.
It works if I set height and width but actually i want to wrap content and get the height depending on how many items i have...

**Comment by egorikftp** [comment]
The same issue

**Comment by skydoves** [comment]
Hi, I just tested using the demo project but It looks worked fine to me.

<img src="https://user-images.githubusercontent.com/24237865/93353177-9520b700-f876-11ea-9133-4a3821eb4b4c.png" width="34%" />

Here is the code. And you can test using the [demo](https://github.com/skydoves/Balloon/blob/master/app/src/main/java/com/skydoves/balloondemo/CustomActivity.kt#L64) with some changes like below.
```kotlin
// gets customListBalloon's recyclerView.
 val listRecycler: RecyclerView =
      customListBalloon.getContentView().findViewById(R.id.list_recyclerView)
 listRecycler.adapter = customAdapter
 listRecycler.addItemDecoration(DividerItemDecoration(this, LinearLayoutManager.VERTICAL))
this.customAdapter.addCustomItem(ItemUtils.getCustomSamples(this))
```

**Comment by ueen** [comment]
What size contraints did you apply? The issue for me was when i  set the item and the recycler view to match parent  and  left the popup builder unrestraint...

**Comment by skydoves** [comment]
I tested with the below attributes. For applying match parent, I used `.setWidthRatio(1.0f)` function.

```kotlin
override fun create(context: Context, lifecycle: LifecycleOwner?): Balloon {
    return Balloon.Builder(context)
      .setLayout(R.layout.layout_custom_list)
      .setArrowOrientation(ArrowOrientation.TOP)
      .setArrowConstraints(ArrowConstraints.ALIGN_ANCHOR)
      .setArrowPosition(0.5f)
      .setWidthRatio(1.0f)
      .setArrowSize(10)
      .setTextSize(12f)
      .isRtlSupport(BalloonUtils.isRtlLayout())
      .setCornerRadius(4f)
      .setMarginRight(12)
      .setElevation(6)
      .setBackgroundColorResource(R.color.background800)
      .setBalloonAnimation(BalloonAnimation.FADE)
      .setDismissWhenShowAgain(true)
      .setLifecycleOwner(lifecycle)
      .build()
  }
```
Could you test using the demo project and attach some screenshots?
Thanks!

**Comment by ueen** [comment]
what does setWidthRatio do?

**Comment by ueen** [comment]
A i see its according to screen width, thats a good idea, i dint add that, but cant the popup wrap the content without that?

**Comment by skydoves** [comment]
If you want to wrap your content, set `wrap_content` your RecyclerView and item layouts.
Or you want to apply `match_parent`, using the above function.

**Comment by skydoves** [comment]
@ueen Hi, Did you tried updating your layout's width to `wrap_content `?
